In [96]:
import pandas as pd
import numpy as np
from itertools import combinations
from scipy import stats

In [97]:
pd.set_option('display.max_columns', None)

In [98]:
all_weeks = pd.read_csv('./allweek_data.csv')

/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_97179/2261964023.py:1: DtypeWarning: Columns (23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  all_weeks = pd.read_csv('./allweek_data.csv')

In [99]:
all_weeks.head()

,Unnamed: 0,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status,Unnamed: 0.1
0,0,HAT YAI,LMDIA7364,2025-08-11 00:00:00.252,ปังสด (Fresh Bread),Bakery/Cake,LMF-250810-975102935,True,18.00,4.0,75.0,2442.0,5132.0,25,1009,536,257,1827,COMPLETED,2025-08-11,NaN,NaN,NaN,Bottom,2025-08-11,2025-08-15,No Incentive,1,793,793,0,793,0,0,0.220278,0.0,Lose,NaN
1,1,HAT YAI,LMDZUZ0WT,2025-08-11 00:00:00.252,ปังสด (Fresh Bread),Bakery/Cake,LMF-250810-975102935,False,18.00,4.0,75.0,2442.0,5132.0,25,1009,536,257,1827,COMPLETED,2025-08-11,NaN,NaN,NaN,Bottom,2025-08-11,2025-08-15,No Incentive,0,793,0,0,0,0,0,0.000000,0.0,Lose,NaN
2,2,KHONKAEN,LMDLHZCD5,2025-08-11 00:00:14.231,ย่าทองสุขหมูกรอบ&ทะเล เคหะมอ,Sukiyaki/Shabu,LMF-250811-292563297,True,21.38,2.0,163.0,2066.0,3573.2,16,344,981,246,1587,COMPLETED,2025-08-11,KHONKAEN,0.000,no-rain,Bottom,2025-08-11,2025-08-15,Streak Orders,1,1227,1227,0,1227,0,0,0.340833,0.0,Lose,NaN
3,3,NAKHONPATHOM,LMD72OXS6,2025-08-11 00:00:19.446,ร้านอร่อยลึก2...ตำยำ (ร้านอร่อย2...ลึก ส้มตำ ...,North East,LMF-250811-595853341,True,21.99,2.0,62.0,1555.0,513.7,13,17,472,270,772,COMPLETED,2025-08-11,NAKHONPATHOM,0.334,Light,Bottom,2025-08-11,2025-08-15,Streak Orders,1,742,742,0,742,0,0,0.206111,0.0,Lose,NaN
4,4,KHONKAEN,LMD0RCBKO,2025-08-11 00:00:22.885,ก๋วยเตี๋ยวแชมป์ตรงข้ามม.ภาค (สาขา2หน้ากสิกร) ก...,Noodles,LMF-250811-470853514,True,19.00,0.0,75.0,2393.0,2013.9,11,1761,500,406,2678,COMPLETED,2025-08-11,KHONKAEN,0.000,no-rain,Top,2025-08-11,2025-08-15,Streak Orders,1,906,906,0,906,0,0,0.251667,0.0,Lose,NaN

In [100]:
# Sort by driver_id and date to ensure chronological order
df = all_weeks.copy()
df = df.sort_values(['driver_id', 'date'])

# Forward-fill Rider Group within each driver_id group
df['Rider Group'] = df.groupby('driver_id')['Rider Group'].ffill()

In [101]:
df['Incentive'] = df['Incentive'].replace({
    'Streak Orders': 'SO',
    'Streak Hours': 'SH',
    'Daily Hours': 'DH',
    'Daily Orders': 'DO',
    'No Incentive': 'NI'
})

In [102]:
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['region', 'driver_id', 'date']).reset_index(drop=True)

In [103]:
# Driver-grouped summary
driver_summary_grouped = df.groupby(['Rider Group', 'date', 'region', 'Incentive', 'Status', 'driver_id']).agg(
    orders_completed=('daily_order_count', 'max'),  #gets the number of orders completed in a day
    acceptance_rate=('is_driver_accept', 'mean'), #how many orders does the driver accept compared to how many orders they get assigned
    hours_worked=('daily_cumulative_time_hr', 'max'), #how much did do they work a day (week 1)
    total_wage=('wage', 'sum'), #how much money do they make from the order directly (not including on_top_fare; need to clarify what on_top_fare is)
    avg_time_per_order_sec=('time_per_order_sec', 'mean'), #how much time they spend per order on average
    avg_drop_distance=('drop_off_distance', 'mean'), #how far do they go to drop off the order (further or closer locations preferred)
    closest_drop_distance=('drop_off_distance', 'min'), 
    furthest_drop_distance=('drop_off_distance', 'max'), 
    avg_rain = ('avg_rain', 'mean'), #does weather have an impact 
    avg_basket_size=('basket_size', 'mean'),
).reset_index()

driver_summary_grouped

,Rider Group,date,region,Incentive,Status,driver_id,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size
0,Bottom,2025-07-10,CHANTHABURI,NI,Lose,LMD15NFXT,6,1.000000,1.033611,120.00,620.166667,4063.500000,453.0,7224.0,0.37,143.986667
1,Bottom,2025-07-10,CHANTHABURI,NI,Lose,LMD3Q3J40,12,0.857143,2.335556,295.00,670.785714,4658.714286,168.0,10267.0,0.37,147.500000
2,Bottom,2025-07-10,CHANTHABURI,NI,Lose,LMD9IAIAR,32,0.941176,7.759167,632.20,899.235294,3594.352941,126.0,7392.0,0.37,152.852941
3,Bottom,2025-07-10,CHANTHABURI,NI,Lose,LMD9PE2C5,22,0.733333,4.289722,478.06,678.933333,2582.466667,279.0,6204.0,0.37,154.373333
4,Bottom,2025-07-10,CHANTHABURI,NI,Lose,LMDCNTS68,41,1.000000,9.154722,783.20,803.829268,3806.682927,733.0,9444.0,0.37,127.491220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153614,Top,2025-08-29,YASOTHON,DH,Win,LMDTJXX8P,1,1.000000,0.327222,20.00,1178.000000,2834.000000,2834.0,2834.0,2.94,65.000000
153615,Top,2025-08-29,YASOTHON,DH,Win,LMDU6D3TV,5,0.625000,1.192778,165.41,1003.000000,3661.500000,853.0,7605.0,2.94,179.282500
153616,Top,2025-08-29,YASOTHON,DH,Win,LMDVHQI9Z,7,1.000000,1.159444,152.11,596.285714,4045.571429,394.0,6648.0,2.94,128.857143
153617,Top,2025-08-29,YASOTHON,DH,Win,LMDVPJ6CI,3,0.600000,0.633056,89.47,974.200000,3642.200000,1171.0,4575.0,2.94,137.600000
153618,Top,2025-08-29,YASOTHON,DH,Win,LMDZLQXI8,48,0.631579,9.315000,1354.54,751.631579,3102.868421,119.0,9109.0,2.94,158.419079

In [104]:
#add the total orders completed and total hours worked each day to df 
df = df.merge(
    driver_summary_grouped[['driver_id', 'date', 'hours_worked', 'acceptance_rate', 'orders_completed']],
    on=['driver_id', 'date'],
    how='left'
)

In [105]:
#metrics to get ttest from
outcome_columns = ['time_per_order_sec', 'orders_completed', 'acceptance_rate', 'hours_worked']

In [106]:
OUTCOME_COL = 'orders_completed'   # outcome we want to measure ttest for

In [107]:
df = df.dropna(subset=['Incentive'])
df['Incentive'] = df['Incentive'].astype(str).str.strip()

In [108]:
# df['week'] = df['date'].dt.isocalendar().week
# df['year'] = df['date'].dt.isocalendar().year

In [109]:
# def build_sequences(df, outcome_col):
#     """
#     Returns a dict  {(incentive_1, incentive_2): [outcome_values]}
#     where outcome_values are measured during the SECOND incentive window.
#     Only counts sequences where both incentives are within the same region.
#     """
#     seq_outcomes = {}

#     for (region, driver_id), grp in df.groupby(['region', 'driver_id']):
#         grp = grp.sort_values(['year', 'week'])
#         incentives = grp['Incentive'].values
#         outcomes   = grp[outcome_col].values
#         regions    = grp['region'].values        # track region per row

#         for i in range(len(incentives) - 1):
#             # Only count sequence if both rows are in the same region
#             if regions[i] != regions[i + 1]:
#                 continue

#             seq = (incentives[i], incentives[i + 1])
#             val = outcomes[i + 1]
#             if pd.notna(val):
#                 seq_outcomes.setdefault(seq, []).append(val)

#     return seq_outcomes

# seq_outcomes = build_sequences(df, OUTCOME_COL)

# # Summary table
# rows = []
# for seq, vals in sorted(seq_outcomes.items()):
#     rows.append({
#         'sequence':   f"{seq[0]} → {seq[1]}",
#         'n':          len(vals),
#         'mean':       np.mean(vals),
#         'std':        np.std(vals, ddof=1),
#         'median':     np.median(vals),
#     })

# summary = pd.DataFrame(rows).sort_values('mean', ascending=False)

In [110]:
# Collapse to one row per driver per week
df['week'] = df['date'].dt.isocalendar().week
df['year'] = df['date'].dt.isocalendar().year

driver_periods = (
    df.groupby(['driver_id', 'region', 'year', 'week', 'Incentive'])
    .agg(
        period_start=('date', 'min'),
        outcome=(OUTCOME_COL, 'mean')
    )
    .reset_index()
    .sort_values(['driver_id', 'region', 'year', 'week'])
)

# Now build sequences on the collapsed data
def build_sequences(df, outcome_col='outcome'):
    seq_outcomes = {}

    for (region, driver_id), grp in df.groupby(['region', 'driver_id']):
        grp = grp.sort_values('period_start')
        incentives = grp['Incentive'].values
        outcomes   = grp[outcome_col].values

        for i in range(len(incentives) - 1):
            # Skip if same incentive consecutive (no real transition)
            if incentives[i] == incentives[i + 1]:
                continue
            seq = (incentives[i], incentives[i + 1])
            val = outcomes[i + 1]
            if pd.notna(val):
                seq_outcomes.setdefault(seq, []).append(val)

    return seq_outcomes

seq_outcomes = build_sequences(driver_periods)

# Should now be <= 25 keys (5x5, minus same→same which we skipped)
print(f"Unique sequences found: {len(seq_outcomes)}")
print(sorted(seq_outcomes.keys()))

Unique sequences found: 20
[('DH', 'DO'), ('DH', 'NI'), ('DH', 'SH'), ('DH', 'SO'), ('DO', 'DH'), ('DO', 'NI'), ('DO', 'SH'), ('DO', 'SO'), ('NI', 'DH'), ('NI', 'DO'), ('NI', 'SH'), ('NI', 'SO'), ('SH', 'DH'), ('SH', 'DO'), ('SH', 'NI'), ('SH', 'SO'), ('SO', 'DH'), ('SO', 'DO'), ('SO', 'NI'), ('SO', 'SH')]

In [111]:
# Summary table
rows = []
for seq, vals in sorted(seq_outcomes.items()):
    rows.append({
        'sequence':   f"{seq[0]} → {seq[1]}",
        'n':          len(vals),
        'mean':       np.mean(vals),
        'std':        np.std(vals, ddof=1),
        'median':     np.median(vals),
    })

summary = pd.DataFrame(rows).sort_values('mean', ascending=False)

In [112]:
summary.head()

   sequence     n       mean        std     median
3   DH → SO   386  25.520036  13.587759  23.893617
14  SH → NI   464  24.348016  14.163956  22.000000
19  SO → SH  1360  24.259019  14.121414  22.224483
5   DO → NI   509  24.256281  11.918946  23.769231
2   DH → SH  1109  23.876259  13.535247  22.631206

In [113]:
def stars(p):
    if p < 0.001: return '***'
    if p < 0.01:  return '**'
    if p < 0.05:  return '*'
    return 'ns'

In [114]:
# ── Pairwise t-tests: same predecessor, different successor ─────────────────
MIN_SAMPLES = 30

eligible = {s: v for s, v in seq_outcomes.items() if len(v) >= MIN_SAMPLES}

results = []

# Group sequences by their first incentive (predecessor)
predecessors = set(s[0] for s in eligible.keys())

for pred in predecessors:
    # All sequences that start with this predecessor
    seqs_with_pred = [s for s in eligible.keys() if s[0] == pred]
    
    # Compare every pair of successors given the same predecessor
    for s1, s2 in combinations(seqs_with_pred, 2):
        g1, g2 = eligible[s1], eligible[s2]
        t_stat, p_val = stats.ttest_ind(g1, g2, equal_var=False)

        results.append({
            'predecessor':  pred,
            'seq_A':        f"{s1[0]} → {s1[1]}",
            'seq_B':        f"{s2[0]} → {s2[1]}",
            'mean_A':       np.mean(g1),
            'mean_B':       np.mean(g2),
            'n_A':          len(g1),
            'n_B':          len(g2),
            't_stat':       t_stat,
            'p_value':      p_val,
            'stars':        stars(p_val),
        })

results_df = pd.DataFrame(results).sort_values('p_value')

# Bonferroni correction across all comparisons
n_tests = len(results_df)
results_df['p_bonferroni'] = (results_df['p_value'] * n_tests).clip(upper=1.0)
results_df['sig_bonferroni'] = results_df['p_bonferroni'] < 0.05

print(f"Total comparisons: {n_tests}")
print(results_df[results_df['p_value'] < 0.05].to_string(index=False, float_format='{:.4f}'.format))

Total comparisons: 30
predecessor   seq_A   seq_B  mean_A  mean_B  n_A  n_B  t_stat  p_value stars  p_bonferroni  sig_bonferroni
         NI NI → DH NI → SH 22.9227 19.6983 1998 1553  7.7618   0.0000   ***        0.0000            True
         NI NI → SH NI → DO 19.6983 22.4930 1553 1243 -6.0493   0.0000   ***        0.0000            True
         NI NI → SH NI → SO 19.6983 21.9769 1553 2763 -5.8715   0.0000   ***        0.0000            True
         DO DO → NI DO → SO 24.2563 19.2793  509  252  5.3970   0.0000   ***        0.0000            True
         DO DO → NI DO → DH 24.2563 19.7591  509  386  5.3656   0.0000   ***        0.0000            True
         SH SH → NI SH → SO 24.3480 20.4789  464 1167  5.1661   0.0000   ***        0.0000            True
         SO SO → SH SO → DH 24.2590 21.1490 1360  608  4.7041   0.0000   ***        0.0001            True
         SH SH → NI SH → DH 24.3480 21.0965  464 1161  4.0941   0.0000   ***        0.0014            True
         SO SO → NI SO → DH 23.3756 21.1490 1484  608  3.5235   0.0004   ***        0.0133            True
         DH DH → SO DH → NI 25.5200 22.5730  386  719  3.5017   0.0005   ***        0.0147            True
         DO DO → SH DO → SO 22.2800 19.2793  347  252  2.8691   0.0043    **        0.1281           False
         SO SO → DO SO → DH 23.6245 21.1490  349  608  2.7580   0.0060    **        0.1789           False
         DO DO → DH DO → SH 19.7591 22.2800  386  347 -2.5919   0.0097    **        0.2922           False
         NI NI → DH NI → SO 22.9227 21.9769 1998 2763  2.5320   0.0114     *        0.3413           False
         DH DH → SO DH → DO 25.5200 23.3507  386  551  2.4046   0.0164     *        0.4922           False
         SH SH → NI SH → DO 24.3480 22.1085  464  297  2.3311   0.0200     *        0.6010           False
         DO DO → NI DO → SH 24.2563 22.2800  509  347  2.2074   0.0276     *        0.8286           False
         DH DH → SH DH → NI 23.8763 22.5730 1109  719  2.0732   0.0383     *        1.0000           False
         SH SH → SO SH → DO 20.4789 22.1085 1167  297 -2.0709   0.0389     *        1.0000           False
         DH DH → SO DH → SH 25.5200 23.8763  386 1109  2.0491   0.0408     *        1.0000           False

In [115]:
results_df

,predecessor,seq_A,seq_B,mean_A,mean_B,n_A,n_B,t_stat,p_value,stars,p_bonferroni,sig_bonferroni
24,NI,NI → DH,NI → SH,22.922726,19.698309,1998,1553,7.761769,1.097785e-14,***,3.293355e-13,True
28,NI,NI → SH,NI → DO,19.698309,22.492959,1553,1243,-6.049298,1.661888e-09,***,4.985663e-08,True
27,NI,NI → SH,NI → SO,19.698309,21.976922,1553,2763,-5.871466,4.735637e-09,***,1.420691e-07,True
14,DO,DO → NI,DO → SO,24.256281,19.279281,509,252,5.396956,1.050822e-07,***,3.152466e-06,True
12,DO,DO → NI,DO → DH,24.256281,19.759085,509,386,5.365604,1.058231e-07,***,3.174692e-06,True
7,SH,SH → NI,SH → SO,24.348016,20.478887,464,1167,5.166086,3.064047e-07,***,9.192142e-06,True
20,SO,SO → SH,SO → DH,24.259019,21.148958,1360,608,4.704054,2.837832e-06,***,8.513496e-05,True
6,SH,SH → NI,SH → DH,24.348016,21.096487,464,1161,4.094101,4.615400e-05,***,1.384620e-03,True
22,SO,SO → NI,SO → DH,23.375623,21.148958,1484,608,3.523523,4.435852e-04,***,1.330756e-02,True
1,DH,DH → SO,DH → NI,25.520036,22.572973,386,719,3.501701,4.896120e-04,***,1.468836e-02,True
17,DO,DO → SH,DO → SO,22.279953,19.279281,347,252,2.869064,4.268765e-03,**,1.280629e-01,False
23,SO,SO → DO,SO → DH,23.624482,21.148958,349,608,2.757959,5.963889e-03,**,1.789167e-01,False
15,DO,DO → DH,DO → SH,19.759085,22.279953,386,347,-2.591929,9.739314e-03,**,2.921794e-01,False
25,NI,NI → DH,NI → SO,22.922726,21.976922,1998,2763,2.532039,1.137537e-02,*,3.412610e-01,False
2,DH,DH → SO,DH → DO,25.520036,23.350703,386,551,2.404641,1.640669e-02,*,4.922007e-01,False
8,SH,SH → NI,SH → DO,24.348016,22.108473,464,297,2.331074,2.003249e-02,*,6.009748e-01,False
13,DO,DO → NI,DO → SH,24.256281,22.279953,509,347,2.207373,2.762032e-02,*,8.286097e-01,False
3,DH,DH → SH,DH → NI,23.876259,22.572973,1109,719,2.073170,3.831737e-02,*,1.000000e+00,False
11,SH,SH → SO,SH → DO,20.478887,22.108473,1167,297,-2.070907,3.892056e-02,*,1.000000e+00,False
0,DH,DH → SO,DH → SH,25.520036,23.876259,386,1109,2.049117,4.084010e-02,*,1.000000e+00,False
18,SO,SO → SH,SO → NI,24.259019,23.375623,1360,1484,1.747687,8.063025e-02,ns,1.000000e+00,False
10,SH,SH → DH,SH → DO,21.096487,22.108473,1161,297,-1.219144,2.233024e-01,ns,1.000000e+00,False
29,NI,NI → SO,NI → DO,21.976922,22.492959,2763,1243,-1.215040,2.244668e-01,ns,1.000000e+00,False
9,SH,SH → DH,SH → SO,21.096487,20.478887,1161,1167,1.080117,2.802073e-01,ns,1.000000e+00,False
5,DH,DH → NI,DH → DO,22.572973,23.350703,719,551,-1.034172,3.012734e-01,ns,1.000000e+00,False
26,NI,NI → DH,NI → DO,22.922726,22.492959,1998,1243,0.955405,3.394587e-01,ns,1.000000e+00,False
19,SO,SO → SH,SO → DO,24.259019,23.624482,1360,349,0.779989,4.357254e-01,ns,1.000000e+00,False
4,DH,DH → SH,DH → DO,23.876259,23.350703,1109,551,0.742690,4.578291e-01,ns,1.000000e+00,False
16,DO,DO → DH,DO → SO,19.759085,19.279281,386,252,0.481073,6.306525e-01,ns,1.000000e+00,False
21,SO,SO → NI,SO → DO,23.375623,23.624482,1484,349,-0.315022,7.528753e-01,ns,1.000000e+00,False

In [116]:
#get latex format 
latex_df = results_df[results_df['sig_bonferroni'] == True] 
latex_df = latex_df.drop(columns=['n_A', 'n_B', 'stars', 'predecessor'], )

latex_str = latex_df.to_latex(
    index=False,
    caption='Pairwise T-Test Results for Incentive Sequences',
    label='tab:ttest_results',
    column_format='llllrrrrrr',  # one l/r per column, l=left r=right aligned
    escape=True,                  # escapes special latex characters
    float_format='{:.4f}'.format
)

print(latex_str)

\begin{table}
\caption{Pairwise T-Test Results for Incentive Sequences}
\label{tab:ttest_results}
\begin{tabular}{llllrrrrrr}
\toprule
seq\_A & seq\_B & mean\_A & mean\_B & t\_stat & p\_value & p\_bonferroni & sig\_bonferroni \\
\midrule
NI → DH & NI → SH & 22.9227 & 19.6983 & 7.7618 & 0.0000 & 0.0000 & True \\
NI → SH & NI → DO & 19.6983 & 22.4930 & -6.0493 & 0.0000 & 0.0000 & True \\
NI → SH & NI → SO & 19.6983 & 21.9769 & -5.8715 & 0.0000 & 0.0000 & True \\
DO → NI & DO → SO & 24.2563 & 19.2793 & 5.3970 & 0.0000 & 0.0000 & True \\
DO → NI & DO → DH & 24.2563 & 19.7591 & 5.3656 & 0.0000 & 0.0000 & True \\
SH → NI & SH → SO & 24.3480 & 20.4789 & 5.1661 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DH & 24.2590 & 21.1490 & 4.7041 & 0.0000 & 0.0001 & True \\
SH → NI & SH → DH & 24.3480 & 21.0965 & 4.0941 & 0.0000 & 0.0014 & True \\
SO → NI & SO → DH & 23.3756 & 21.1490 & 3.5235 & 0.0004 & 0.0133 & True \\
DH → SO & DH → NI & 25.5200 & 22.5730 & 3.5017 & 0.0005 & 0.0147 & True \\
\bottomrule
\end{tabular}
\end{table}

In [117]:
# Save full results
results_df.to_csv('ttest_results_driver_acceptance_rate.csv', index=False)
print("\nFull results saved to ttest_results_driver_acceptance_rate.csv")

Full results saved to ttest_results_driver_acceptance_rate.csv

In [118]:
# Now build sequences on the collapsed data
def build_sequences(df, outcome_col='outcome'):
    seq_outcomes = {}

    for (region, driver_id), grp in df.groupby(['region', 'driver_id']):
        grp = grp.sort_values('period_start')
        incentives = grp['Incentive'].values
        outcomes   = grp[outcome_col].values

        for i in range(len(incentives) - 1):
            # Skip if same incentive consecutive (no real transition)
            if incentives[i] == incentives[i + 1]:
                continue
            seq = (incentives[i], incentives[i + 1])
            val = outcomes[i + 1]
            if pd.notna(val):
                seq_outcomes.setdefault(seq, []).append(val)

    return seq_outcomes

In [121]:
#loop through all incentives I want to test to get ttest results 

outcome_columns = ['time_per_order_sec', 'orders_completed', 'acceptance_rate', 'hours_worked']

for outcome in outcome_columns: 
    # Collapse to one row per driver per week
    # df['week'] = df['date'].dt.isocalendar().week
    # df['year'] = df['date'].dt.isocalendar().year

    driver_periods = (
        df.groupby(['driver_id', 'region', 'year', 'week', 'Incentive'])
        .agg(
            period_start=('date', 'min'),
            outcome=(outcome, 'mean')
        )
        .reset_index()
        .sort_values(['driver_id', 'region', 'year', 'week'])
    )

    seq_outcomes = build_sequences(driver_periods)

    # Should now be <= 25 keys (5x5, minus same→same which we skipped)
    print(f"Unique sequences found: {len(seq_outcomes)}")
    print(sorted(seq_outcomes.keys()))

    # Summary table
    rows = []
    for seq, vals in sorted(seq_outcomes.items()):
        rows.append({
            'sequence':   f"{seq[0]} → {seq[1]}",
            'n':          len(vals),
            'mean':       np.mean(vals),
            'std':        np.std(vals, ddof=1),
            'median':     np.median(vals),
        })

    summary = pd.DataFrame(rows).sort_values('mean', ascending=False)

    MIN_SAMPLES = 30

    eligible = {s: v for s, v in seq_outcomes.items() if len(v) >= MIN_SAMPLES}

    results = []

    # Group sequences by their first incentive (predecessor)
    predecessors = set(s[0] for s in eligible.keys())

    for pred in predecessors:
        # All sequences that start with this predecessor
        seqs_with_pred = [s for s in eligible.keys() if s[0] == pred]
        
        # Compare every pair of successors given the same predecessor
        for s1, s2 in combinations(seqs_with_pred, 2):
            g1, g2 = eligible[s1], eligible[s2]
            t_stat, p_val = stats.ttest_ind(g1, g2, equal_var=False)

            results.append({
                'predecessor':  pred,
                'seq_A':        f"{s1[0]} → {s1[1]}",
                'seq_B':        f"{s2[0]} → {s2[1]}",
                'mean_A':       np.mean(g1),
                'mean_B':       np.mean(g2),
                'n_A':          len(g1),
                'n_B':          len(g2),
                't_stat':       t_stat,
                'p_value':      p_val,
                'stars':        stars(p_val),
            })

    results_df = pd.DataFrame(results).sort_values('p_value')

    # Bonferroni correction across all comparisons
    n_tests = len(results_df)
    results_df['p_bonferroni'] = (results_df['p_value'] * n_tests).clip(upper=1.0)
    results_df['sig_bonferroni'] = results_df['p_bonferroni'] < 0.05

    print(f"Total comparisons: {n_tests}")
    print(results_df[results_df['p_value'] < 0.05].to_string(index=False, float_format='{:.4f}'.format))

    #get latex format 
    latex_df = results_df[results_df['sig_bonferroni'] == True] 
    latex_df = latex_df.drop(columns=['n_A', 'n_B', 'stars', 'predecessor'], )

    latex_str = latex_df.to_latex(
        index=False,
        caption=f'Pairwise T-Test Results for Incentive Sequences {outcome}',
        label='tab:ttest_results',
        column_format='llllrrrrrr',  # one l/r per column, l=left r=right aligned
        escape=True,                  # escapes special latex characters
        float_format='{:.4f}'.format
    )

    print(latex_str)

Unique sequences found: 20
[('DH', 'DO'), ('DH', 'NI'), ('DH', 'SH'), ('DH', 'SO'), ('DO', 'DH'), ('DO', 'NI'), ('DO', 'SH'), ('DO', 'SO'), ('NI', 'DH'), ('NI', 'DO'), ('NI', 'SH'), ('NI', 'SO'), ('SH', 'DH'), ('SH', 'DO'), ('SH', 'NI'), ('SH', 'SO'), ('SO', 'DH'), ('SO', 'DO'), ('SO', 'NI'), ('SO', 'SH')]
Total comparisons: 30
predecessor   seq_A   seq_B   mean_A   mean_B  n_A  n_B  t_stat  p_value stars  p_bonferroni  sig_bonferroni
         SH SH → SO SH → DO 812.6403 687.0066 1167  297 15.5230   0.0000   ***        0.0000            True
         SH SH → NI SH → DO 811.3721 687.0066  464  297 13.4171   0.0000   ***        0.0000            True
         DO DO → NI DO → SO 816.7196 694.6408  509  252 11.4245   0.0000   ***        0.0000            True
         NI NI → DH NI → SO 775.8616 815.9247 1998 2763 -9.3793   0.0000   ***        0.0000            True
         SH SH → DH SH → DO 763.0344 687.0066 1161  297  8.7139   0.0000   ***        0.0000            True
         SH SH → DH SH → SO 763.0344 812.6403 1161 1167 -7.2787   0.0000   ***        0.0000            True
         SO SO → NI SO → DO 833.0819 777.2498 1484  349  7.0379   0.0000   ***        0.0000            True
         DO DO → DH DO → SO 770.5350 694.6408  386  252  7.0109   0.0000   ***        0.0000            True
         DO DO → SH DO → SO 779.2622 694.6408  347  252  6.9681   0.0000   ***        0.0000            True
         NI NI → DH NI → DO 775.8616 810.5479 1998 1243 -6.7716   0.0000   ***        0.0000            True
         SH SH → NI SH → DH 811.3721 763.0344  464 1161  5.9115   0.0000   ***        0.0000            True
         DH DH → SH DH → DO 764.4524 816.0414 1109  551 -5.9027   0.0000   ***        0.0000            True
         SO SO → SH SO → DO 822.5979 777.2498 1360  349  5.4639   0.0000   ***        0.0000            True
         DO DO → NI DO → DH 816.7196 770.5350  509  386  5.1717   0.0000   ***        0.0000            True
         NI NI → SH NI → SO 789.8048 815.9247 1553 2763 -5.1198   0.0000   ***        0.0000            True
         DH DH → NI DH → DO 768.5764 816.0414  719  551 -5.0692   0.0000   ***        0.0000            True
         DH DH → SO DH → DO 772.3552 816.0414  386  551 -4.4857   0.0000   ***        0.0002            True
         SO SO → NI SO → DH 833.0819 802.9740 1484  608  4.0193   0.0001   ***        0.0019            True
         DO DO → NI DO → SH 816.7196 779.2622  509  347  3.5707   0.0004   ***        0.0114            True
         NI NI → SH NI → DO 789.8048 810.5479 1553 1243 -3.5563   0.0004   ***        0.0115            True
         NI NI → DH NI → SH 775.8616 789.8048 1998 1553 -2.7041   0.0069    **        0.2066           False
         SO SO → DO SO → DH 777.2498 802.9740  349  608 -2.6124   0.0092    **        0.2745           False
         SO SO → SH SO → DH 822.5979 802.9740 1360  608  2.4910   0.0129     *        0.3866           False
         SO SO → SH SO → NI 822.5979 833.0819 1360 1484 -1.9803   0.0478     *        1.0000           False
\begin{table}
\caption{Pairwise T-Test Results for Incentive Sequences time_per_order_sec}
\label{tab:ttest_results}
\begin{tabular}{llllrrrrrr}
\toprule
seq\_A & seq\_B & mean\_A & mean\_B & t\_stat & p\_value & p\_bonferroni & sig\_bonferroni \\
\midrule
SH → SO & SH → DO & 812.6403 & 687.0066 & 15.5230 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DO & 811.3721 & 687.0066 & 13.4171 & 0.0000 & 0.0000 & True \\
DO → NI & DO → SO & 816.7196 & 694.6408 & 11.4245 & 0.0000 & 0.0000 & True \\
NI → DH & NI → SO & 775.8616 & 815.9247 & -9.3793 & 0.0000 & 0.0000 & True \\
SH → DH & SH → DO & 763.0344 & 687.0066 & 8.7139 & 0.0000 & 0.0000 & True \\
SH → DH & SH → SO & 763.0344 & 812.6403 & -7.2787 & 0.0000 & 0.0000 & True \\
SO → NI & SO → DO & 833.0819 & 777.2498 & 7.0379 & 0.0000 & 0.0000 & True \\
DO → DH & DO → SO & 770.5350 & 694.6408 & 7.0109 & 0.0000 & 0.0000 & True \\
DO → SH & DO → SO & 779.2622 & 694.6408 & 6.9681 & 0.0000 & 0.0000 & True \\
NI → DH & NI → DO & 775.8616 & 810.5479 & -6.7716 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DH & 811.3721 & 763.0344 & 5.9115 & 0.0000 & 0.0000 & True \\
DH → SH & DH → DO & 764.4524 & 816.0414 & -5.9027 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DO & 822.5979 & 777.2498 & 5.4639 & 0.0000 & 0.0000 & True \\
DO → NI & DO → DH & 816.7196 & 770.5350 & 5.1717 & 0.0000 & 0.0000 & True \\
NI → SH & NI → SO & 789.8048 & 815.9247 & -5.1198 & 0.0000 & 0.0000 & True \\
DH → NI & DH → DO & 768.5764 & 816.0414 & -5.0692 & 0.0000 & 0.0000 & True \\
DH → SO & DH → DO & 772.3552 & 816.0414 & -4.4857 & 0.0000 & 0.0002 & True \\
SO → NI & SO → DH & 833.0819 & 802.9740 & 4.0193 & 0.0001 & 0.0019 & True \\
DO → NI & DO → SH & 816.7196 & 779.2622 & 3.5707 & 0.0004 & 0.0114 & True \\
NI → SH & NI → DO & 789.8048 & 810.5479 & -3.5563 & 0.0004 & 0.0115 & True \\
\bottomrule
\end{tabular}
\end{table}

Unique sequences found: 20
[('DH', 'DO'), ('DH', 'NI'), ('DH', 'SH'), ('DH', 'SO'), ('DO', 'DH'), ('DO', 'NI'), ('DO', 'SH'), ('DO', 'SO'), ('NI', 'DH'), ('NI', 'DO'), ('NI', 'SH'), ('NI', 'SO'), ('SH', 'DH'), ('SH', 'DO'), ('SH', 'NI'), ('SH', 'SO'), ('SO', 'DH'), ('SO', 'DO'), ('SO', 'NI'), ('SO', 'SH')]
Total comparisons: 30
predecessor   seq_A   seq_B  mean_A  mean_B  n_A  n_B  t_stat  p_value stars  p_bonferroni  sig_bonferroni
         NI NI → DH NI → SH 22.9227 19.6983 1998 1553  7.7618   0.0000   ***        0.0000            True
         NI NI → SH NI → DO 19.6983 22.4930 1553 1243 -6.0493   0.0000   ***        0.0000            True
         NI NI → SH NI → SO 19.6983 21.9769 1553 2763 -5.8715   0.0000   ***        0.0000            True
         DO DO → NI DO → SO 24.2563 19.2793  509  252  5.3970   0.0000   ***        0.0000            True
         DO DO → NI DO → DH 24.2563 19.7591  509  386  5.3656   0.0000   ***        0.0000            True
         SH SH → NI SH → SO 24.3480 20.4789  464 1167  5.1661   0.0000   ***        0.0000            True
         SO SO → SH SO → DH 24.2590 21.1490 1360  608  4.7041   0.0000   ***        0.0001            True
         SH SH → NI SH → DH 24.3480 21.0965  464 1161  4.0941   0.0000   ***        0.0014            True
         SO SO → NI SO → DH 23.3756 21.1490 1484  608  3.5235   0.0004   ***        0.0133            True
         DH DH → SO DH → NI 25.5200 22.5730  386  719  3.5017   0.0005   ***        0.0147            True
         DO DO → SH DO → SO 22.2800 19.2793  347  252  2.8691   0.0043    **        0.1281           False
         SO SO → DO SO → DH 23.6245 21.1490  349  608  2.7580   0.0060    **        0.1789           False
         DO DO → DH DO → SH 19.7591 22.2800  386  347 -2.5919   0.0097    **        0.2922           False
         NI NI → DH NI → SO 22.9227 21.9769 1998 2763  2.5320   0.0114     *        0.3413           False
         DH DH → SO DH → DO 25.5200 23.3507  386  551  2.4046   0.0164     *        0.4922           False
         SH SH → NI SH → DO 24.3480 22.1085  464  297  2.3311   0.0200     *        0.6010           False
         DO DO → NI DO → SH 24.2563 22.2800  509  347  2.2074   0.0276     *        0.8286           False
         DH DH → SH DH → NI 23.8763 22.5730 1109  719  2.0732   0.0383     *        1.0000           False
         SH SH → SO SH → DO 20.4789 22.1085 1167  297 -2.0709   0.0389     *        1.0000           False
         DH DH → SO DH → SH 25.5200 23.8763  386 1109  2.0491   0.0408     *        1.0000           False
\begin{table}
\caption{Pairwise T-Test Results for Incentive Sequences orders_completed}
\label{tab:ttest_results}
\begin{tabular}{llllrrrrrr}
\toprule
seq\_A & seq\_B & mean\_A & mean\_B & t\_stat & p\_value & p\_bonferroni & sig\_bonferroni \\
\midrule
NI → DH & NI → SH & 22.9227 & 19.6983 & 7.7618 & 0.0000 & 0.0000 & True \\
NI → SH & NI → DO & 19.6983 & 22.4930 & -6.0493 & 0.0000 & 0.0000 & True \\
NI → SH & NI → SO & 19.6983 & 21.9769 & -5.8715 & 0.0000 & 0.0000 & True \\
DO → NI & DO → SO & 24.2563 & 19.2793 & 5.3970 & 0.0000 & 0.0000 & True \\
DO → NI & DO → DH & 24.2563 & 19.7591 & 5.3656 & 0.0000 & 0.0000 & True \\
SH → NI & SH → SO & 24.3480 & 20.4789 & 5.1661 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DH & 24.2590 & 21.1490 & 4.7041 & 0.0000 & 0.0001 & True \\
SH → NI & SH → DH & 24.3480 & 21.0965 & 4.0941 & 0.0000 & 0.0014 & True \\
SO → NI & SO → DH & 23.3756 & 21.1490 & 3.5235 & 0.0004 & 0.0133 & True \\
DH → SO & DH → NI & 25.5200 & 22.5730 & 3.5017 & 0.0005 & 0.0147 & True \\
\bottomrule
\end{tabular}
\end{table}

Unique sequences found: 20
[('DH', 'DO'), ('DH', 'NI'), ('DH', 'SH'), ('DH', 'SO'), ('DO', 'DH'), ('DO', 'NI'), ('DO', 'SH'), ('DO', 'SO'), ('NI', 'DH'), ('NI', 'DO'), ('NI', 'SH'), ('NI', 'SO'), ('SH', 'DH'), ('SH', 'DO'), ('SH', 'NI'), ('SH', 'SO'), ('SO', 'DH'), ('SO', 'DO'), ('SO', 'NI'), ('SO', 'SH')]
Total comparisons: 30
predecessor   seq_A   seq_B  mean_A  mean_B  n_A  n_B   t_stat  p_value stars  p_bonferroni  sig_bonferroni
         SO SO → NI SO → DO  0.7818  0.9339 1484  349 -17.6703   0.0000   ***        0.0000            True
         SO SO → SH SO → DO  0.7940  0.9339 1360  349 -16.5594   0.0000   ***        0.0000            True
         SO SO → NI SO → DH  0.7818  0.9163 1484  608 -15.6951   0.0000   ***        0.0000            True
         SO SO → SH SO → DH  0.7940  0.9163 1360  608 -14.5433   0.0000   ***        0.0000            True
         DH DH → SH DH → DO  0.8515  0.9353 1109  551 -13.2642   0.0000   ***        0.0000            True
         SH SH → NI SH → DO  0.8066  0.9321  464  297 -10.0974   0.0000   ***        0.0000            True
         NI NI → SH NI → SO  0.9034  0.8522 1553 2763   9.6927   0.0000   ***        0.0000            True
         DO DO → DH DO → SH  0.7866  0.9255  386  347  -9.9826   0.0000   ***        0.0000            True
         SH SH → NI SH → SO  0.8066  0.9187  464 1167  -9.9230   0.0000   ***        0.0000            True
         DH DH → NI DH → DO  0.8582  0.9353  719  551  -9.4710   0.0000   ***        0.0000            True
         DO DO → DH DO → SO  0.7866  0.9226  386  252  -8.9876   0.0000   ***        0.0000            True
         DO DO → NI DO → DH  0.9054  0.7866  509  386   8.9299   0.0000   ***        0.0000            True
         NI NI → DH NI → SH  0.8612  0.9034 1998 1553  -8.0360   0.0000   ***        0.0000            True
         SH SH → DH SH → SO  0.8778  0.9187 1161 1167  -7.0983   0.0000   ***        0.0000            True
         SH SH → DH SH → DO  0.8778  0.9321 1161  297  -7.0076   0.0000   ***        0.0000            True
         DH DH → SO DH → DO  0.8805  0.9353  386  551  -6.4253   0.0000   ***        0.0000            True
         NI NI → SO NI → DO  0.8522  0.8878 2763 1243  -6.0814   0.0000   ***        0.0000            True
         SH SH → NI SH → DH  0.8066  0.8778  464 1161  -6.0361   0.0000   ***        0.0000            True
         NI NI → DH NI → DO  0.8612  0.8878 1998 1243  -4.5664   0.0000   ***        0.0002            True
         DH DH → SO DH → SH  0.8805  0.8515  386 1109   3.3370   0.0009   ***        0.0267            True
         NI NI → SH NI → DO  0.9034  0.8878 1553 1243   2.7211   0.0066    **        0.1965           False
         DO DO → NI DO → SH  0.9054  0.9255  509  347  -2.2503   0.0247     *        0.7417           False
         DH DH → SO DH → NI  0.8805  0.8582  386  719   2.2082   0.0275     *        0.8240           False
         SO SO → DO SO → DH  0.9339  0.9163  349  608   2.1695   0.0303     *        0.9093           False
\begin{table}
\caption{Pairwise T-Test Results for Incentive Sequences acceptance_rate}
\label{tab:ttest_results}
\begin{tabular}{llllrrrrrr}
\toprule
seq\_A & seq\_B & mean\_A & mean\_B & t\_stat & p\_value & p\_bonferroni & sig\_bonferroni \\
\midrule
SO → NI & SO → DO & 0.7818 & 0.9339 & -17.6703 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DO & 0.7940 & 0.9339 & -16.5594 & 0.0000 & 0.0000 & True \\
SO → NI & SO → DH & 0.7818 & 0.9163 & -15.6951 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DH & 0.7940 & 0.9163 & -14.5433 & 0.0000 & 0.0000 & True \\
DH → SH & DH → DO & 0.8515 & 0.9353 & -13.2642 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DO & 0.8066 & 0.9321 & -10.0974 & 0.0000 & 0.0000 & True \\
NI → SH & NI → SO & 0.9034 & 0.8522 & 9.6927 & 0.0000 & 0.0000 & True \\
DO → DH & DO → SH & 0.7866 & 0.9255 & -9.9826 & 0.0000 & 0.0000 & True \\
SH → NI & SH → SO & 0.8066 & 0.9187 & -9.9230 & 0.0000 & 0.0000 & True \\
DH → NI & DH → DO & 0.8582 & 0.9353 & -9.4710 & 0.0000 & 0.0000 & True \\
DO → DH & DO → SO & 0.7866 & 0.9226 & -8.9876 & 0.0000 & 0.0000 & True \\
DO → NI & DO → DH & 0.9054 & 0.7866 & 8.9299 & 0.0000 & 0.0000 & True \\
NI → DH & NI → SH & 0.8612 & 0.9034 & -8.0360 & 0.0000 & 0.0000 & True \\
SH → DH & SH → SO & 0.8778 & 0.9187 & -7.0983 & 0.0000 & 0.0000 & True \\
SH → DH & SH → DO & 0.8778 & 0.9321 & -7.0076 & 0.0000 & 0.0000 & True \\
DH → SO & DH → DO & 0.8805 & 0.9353 & -6.4253 & 0.0000 & 0.0000 & True \\
NI → SO & NI → DO & 0.8522 & 0.8878 & -6.0814 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DH & 0.8066 & 0.8778 & -6.0361 & 0.0000 & 0.0000 & True \\
NI → DH & NI → DO & 0.8612 & 0.8878 & -4.5664 & 0.0000 & 0.0002 & True \\
DH → SO & DH → SH & 0.8805 & 0.8515 & 3.3370 & 0.0009 & 0.0267 & True \\
\bottomrule
\end{tabular}
\end{table}

Unique sequences found: 20
[('DH', 'DO'), ('DH', 'NI'), ('DH', 'SH'), ('DH', 'SO'), ('DO', 'DH'), ('DO', 'NI'), ('DO', 'SH'), ('DO', 'SO'), ('NI', 'DH'), ('NI', 'DO'), ('NI', 'SH'), ('NI', 'SO'), ('SH', 'DH'), ('SH', 'DO'), ('SH', 'NI'), ('SH', 'SO'), ('SO', 'DH'), ('SO', 'DO'), ('SO', 'NI'), ('SO', 'SH')]
Total comparisons: 30
predecessor   seq_A   seq_B  mean_A  mean_B  n_A  n_B  t_stat  p_value stars  p_bonferroni  sig_bonferroni
         DO DO → NI DO → SO  5.3430  3.6542  509  252  9.4570   0.0000   ***        0.0000            True
         NI NI → DH NI → SH  4.8591  4.1229 1998 1553  8.7960   0.0000   ***        0.0000            True
         NI NI → SH NI → SO  4.1229  4.7437 1553 2763 -7.9484   0.0000   ***        0.0000            True
         NI NI → SH NI → DO  4.1229  4.8596 1553 1243 -7.8982   0.0000   ***        0.0000            True
         SH SH → NI SH → DO  5.2623  4.1181  464  297  6.2413   0.0000   ***        0.0000            True
         SH SH → NI SH → DH  5.2623  4.3402  464 1161  5.7144   0.0000   ***        0.0000            True
         DO DO → NI DO → DH  5.3430  4.3133  509  386  5.6639   0.0000   ***        0.0000            True
         SH SH → NI SH → SO  5.2623  4.4325  464 1167  5.4337   0.0000   ***        0.0000            True
         DO DO → SH DO → SO  4.6437  3.6542  347  252  5.0286   0.0000   ***        0.0000            True
         SO SO → SH SO → DH  5.2623  4.6570 1360  608  4.2008   0.0000   ***        0.0009            True
         DH DH → SO DH → NI  5.3070  4.6558  386  719  3.9501   0.0001   ***        0.0026            True
         DO DO → NI DO → SH  5.3430  4.6437  509  347  3.8819   0.0001   ***        0.0034            True
         SO SO → NI SO → DH  5.1462  4.6570 1484  608  3.5460   0.0004   ***        0.0123            True
         DO DO → DH DO → SO  4.3133  3.6542  386  252  3.3234   0.0009   ***        0.0283            True
         DH DH → SO DH → SH  5.3070  4.7909  386 1109  3.3224   0.0009   ***        0.0283            True
         DH DH → NI DH → DO  4.6558  5.1244  719  551 -2.9972   0.0028    **        0.0836           False
         DH DH → SH DH → DO  4.7909  5.1244 1109  551 -2.2800   0.0228     *        0.6848           False
         SH SH → SO SH → DO  4.4325  4.1181 1167  297  2.1794   0.0298     *        0.8925           False
         SO SO → SH SO → DO  5.2623  4.9310 1360  349  2.0114   0.0447     *        1.0000           False
\begin{table}
\caption{Pairwise T-Test Results for Incentive Sequences hours_worked}
\label{tab:ttest_results}
\begin{tabular}{llllrrrrrr}
\toprule
seq\_A & seq\_B & mean\_A & mean\_B & t\_stat & p\_value & p\_bonferroni & sig\_bonferroni \\
\midrule
DO → NI & DO → SO & 5.3430 & 3.6542 & 9.4570 & 0.0000 & 0.0000 & True \\
NI → DH & NI → SH & 4.8591 & 4.1229 & 8.7960 & 0.0000 & 0.0000 & True \\
NI → SH & NI → SO & 4.1229 & 4.7437 & -7.9484 & 0.0000 & 0.0000 & True \\
NI → SH & NI → DO & 4.1229 & 4.8596 & -7.8982 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DO & 5.2623 & 4.1181 & 6.2413 & 0.0000 & 0.0000 & True \\
SH → NI & SH → DH & 5.2623 & 4.3402 & 5.7144 & 0.0000 & 0.0000 & True \\
DO → NI & DO → DH & 5.3430 & 4.3133 & 5.6639 & 0.0000 & 0.0000 & True \\
SH → NI & SH → SO & 5.2623 & 4.4325 & 5.4337 & 0.0000 & 0.0000 & True \\
DO → SH & DO → SO & 4.6437 & 3.6542 & 5.0286 & 0.0000 & 0.0000 & True \\
SO → SH & SO → DH & 5.2623 & 4.6570 & 4.2008 & 0.0000 & 0.0009 & True \\
DH → SO & DH → NI & 5.3070 & 4.6558 & 3.9501 & 0.0001 & 0.0026 & True \\
DO → NI & DO → SH & 5.3430 & 4.6437 & 3.8819 & 0.0001 & 0.0034 & True \\
SO → NI & SO → DH & 5.1462 & 4.6570 & 3.5460 & 0.0004 & 0.0123 & True \\
DO → DH & DO → SO & 4.3133 & 3.6542 & 3.3234 & 0.0009 & 0.0283 & True \\
DH → SO & DH → SH & 5.3070 & 4.7909 & 3.3224 & 0.0009 & 0.0283 & True \\
\bottomrule
\end{tabular}
\end{table}