In [3]:
import pandas as pd

In [4]:
pd.set_option('display.max_columns', None)

In [8]:
week0_drivers_summary = pd.read_csv('../baseline/week0_stats/driver_summary_week_0.csv')

In [12]:
week0_drivers_summary

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size
0,0,LMD00BZBZ,Mid,SURIN,2025-07-10,No Incentive,Swing,41,0.953488,8.924722,649.42,783.581395,3057.046512,298.0,6895.0,0.00000,159.917442
1,1,LMD00BZBZ,Mid,SURIN,2025-07-11,No Incentive,Swing,34,0.871795,8.221389,589.93,848.410256,2863.666667,442.0,6330.0,0.00000,130.217436
2,2,LMD00BZBZ,Mid,SURIN,2025-07-12,No Incentive,Swing,30,0.810811,7.131111,572.37,915.270270,3307.972973,244.0,7419.0,0.33000,112.129730
3,3,LMD00BZBZ,Mid,SURIN,2025-07-13,No Incentive,Swing,27,1.000000,6.377778,415.60,850.370370,2944.074074,290.0,7090.0,0.00000,106.174074
4,4,LMD01NAMM,Bottom,UTTARADIT,2025-07-10,No Incentive,Lose,19,1.000000,4.865833,308.40,921.947368,2798.842105,271.0,9315.0,0.01350,107.285263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15428,15428,LMDZZPA6L,Bottom,KRABI,2025-07-13,No Incentive,Win,29,1.000000,6.372222,517.40,791.034483,3262.655172,367.0,8510.0,0.26864,140.652414
15429,15429,LMDZZTVOL,Top,KHONKAEN,2025-07-10,No Incentive,Lose,37,1.000000,7.212778,821.03,701.783784,3357.162162,167.0,9681.0,0.00000,133.283243
15430,15430,LMDZZTVOL,Top,KHONKAEN,2025-07-11,No Incentive,Lose,39,1.000000,8.561111,781.96,790.256410,2885.512821,188.0,6422.0,0.18000,123.519487
15431,15431,LMDZZTVOL,Top,KHONKAEN,2025-07-12,No Incentive,Lose,44,0.956522,9.945278,1094.81,800.000000,3792.195652,336.0,8172.0,0.00000,154.438478
15432,15432,LMDZZTVOL,Top,KHONKAEN,2025-07-13,No Incentive,Lose,41,1.000000,9.366667,913.98,822.439024,3576.190244,464.0,7153.8,0.12000,137.952927

In [13]:
week0_drivers_summary.columns

Index(['Unnamed: 0', 'driver_id', 'Rider Group', 'region', 'date', 'Incentive',
       'Status', 'orders_completed', 'acceptance_rate', 'hours_worked',
       'total_wage', 'avg_time_per_order_sec', 'avg_drop_distance',
       'closest_drop_distance', 'furthest_drop_distance', 'avg_rain',
       'avg_basket_size'],
      dtype='object')

In [9]:
week0_baseline = week0_drivers_summary.groupby(['driver_id', 'Rider Group', 'region']).agg(
    ref_wage = ('total_wage', 'mean'),
    ref_orders = ('orders_completed', 'mean'),
    ref_hours = ('hours_worked', 'mean')
).reset_index()

week0_baseline

,driver_id,Rider Group,region,ref_wage,ref_orders,ref_hours
0,LMD00BZBZ,Mid,SURIN,556.830000,33.000000,7.663750
1,LMD01NAMM,Bottom,UTTARADIT,338.800000,20.666667,5.202037
2,LMD01WR5O,Top,TRAT,655.455000,12.750000,2.220486
3,LMD025NCG,Mid,HAT YAI,276.586667,11.333333,4.070556
4,LMD02DNNT,Top,RATCHABURI_Banpong,844.490000,37.000000,8.556389
...,...,...,...,...,...,...
5159,LMDZZ8ZTR,Mid,HAT YAI,670.215000,28.000000,6.695903
5160,LMDZZEUQA,Bottom,CHANTHABURI,576.877500,11.250000,2.761111
5161,LMDZZICT6,Bottom,RATCHABURI_Banpong,380.025000,20.000000,5.341667
5162,LMDZZPA6L,Bottom,KRABI,245.430000,14.000000,3.015000
5163,LMDZZTVOL,Top,KHONKAEN,902.945000,40.250000,8.771458

In [15]:
week1 = pd.read_csv('../week1_stats/driver_summary_week_1.csv')

In [16]:
week1

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size
0,0,LMD00BZBZ,Mid,SURIN,2025-07-14,Streak Orders,Swing,12,1.000000,2.602778,202.76,780.833333,3685.000000,329.0,5455.0,0.76,129.683333
1,1,LMD00BZBZ,Mid,SURIN,2025-07-15,Streak Orders,Swing,34,0.944444,7.714444,551.11,821.194444,3211.527778,89.0,9453.0,0.67,113.361389
2,2,LMD00BZBZ,Mid,SURIN,2025-07-18,Streak Orders,Swing,30,0.967742,5.717500,562.01,720.677419,3781.161290,693.0,7604.0,0.00,118.684839
3,3,LMD00BZBZ,Mid,SURIN,2025-07-19,Streak Orders,Swing,34,0.918919,7.772222,556.73,896.189189,2695.297297,473.0,9112.0,0.16,121.768649
4,4,LMD00BZBZ,Mid,SURIN,2025-07-20,Streak Orders,Swing,47,1.000000,10.237500,752.75,784.148936,3133.297872,265.0,8985.0,0.00,138.787234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28971,28971,LMDZZTVOL,Top,KHONKAEN,2025-07-16,Streak Orders,Lose,37,1.000000,7.463056,897.40,726.135135,3485.459459,200.0,8433.0,0.58,104.053514
28972,28972,LMDZZTVOL,Top,KHONKAEN,2025-07-17,Streak Orders,Lose,38,1.000000,7.770833,749.80,736.184211,2622.684211,185.0,7954.0,1.00,97.170526
28973,28973,LMDZZTVOL,Top,KHONKAEN,2025-07-18,Streak Orders,Lose,36,1.000000,8.472222,811.16,847.222222,3438.638889,650.0,9321.0,0.22,115.247778
28974,28974,LMDZZTVOL,Top,KHONKAEN,2025-07-19,Streak Orders,Lose,10,1.000000,2.074167,237.40,746.700000,3364.400000,619.0,8280.0,0.00,144.380000
28975,28975,LMDZZTVOL,Top,KHONKAEN,2025-07-20,Streak Orders,Lose,20,1.000000,4.509444,464.83,811.700000,3991.950000,507.0,7703.0,0.27,156.731500

In [17]:
week1 = week1.merge(week0_baseline, on = ['driver_id', 'region', 'Rider Group'], how = 'left') #merge with baseline data (so have baseline for all rows

In [18]:
week1

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size,ref_wage,ref_orders,ref_hours
0,0,LMD00BZBZ,Mid,SURIN,2025-07-14,Streak Orders,Swing,12,1.000000,2.602778,202.76,780.833333,3685.000000,329.0,5455.0,0.76,129.683333,556.830,33.00,7.663750
1,1,LMD00BZBZ,Mid,SURIN,2025-07-15,Streak Orders,Swing,34,0.944444,7.714444,551.11,821.194444,3211.527778,89.0,9453.0,0.67,113.361389,556.830,33.00,7.663750
2,2,LMD00BZBZ,Mid,SURIN,2025-07-18,Streak Orders,Swing,30,0.967742,5.717500,562.01,720.677419,3781.161290,693.0,7604.0,0.00,118.684839,556.830,33.00,7.663750
3,3,LMD00BZBZ,Mid,SURIN,2025-07-19,Streak Orders,Swing,34,0.918919,7.772222,556.73,896.189189,2695.297297,473.0,9112.0,0.16,121.768649,556.830,33.00,7.663750
4,4,LMD00BZBZ,Mid,SURIN,2025-07-20,Streak Orders,Swing,47,1.000000,10.237500,752.75,784.148936,3133.297872,265.0,8985.0,0.00,138.787234,556.830,33.00,7.663750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28971,28971,LMDZZTVOL,Top,KHONKAEN,2025-07-16,Streak Orders,Lose,37,1.000000,7.463056,897.40,726.135135,3485.459459,200.0,8433.0,0.58,104.053514,902.945,40.25,8.771458
28972,28972,LMDZZTVOL,Top,KHONKAEN,2025-07-17,Streak Orders,Lose,38,1.000000,7.770833,749.80,736.184211,2622.684211,185.0,7954.0,1.00,97.170526,902.945,40.25,8.771458
28973,28973,LMDZZTVOL,Top,KHONKAEN,2025-07-18,Streak Orders,Lose,36,1.000000,8.472222,811.16,847.222222,3438.638889,650.0,9321.0,0.22,115.247778,902.945,40.25,8.771458
28974,28974,LMDZZTVOL,Top,KHONKAEN,2025-07-19,Streak Orders,Lose,10,1.000000,2.074167,237.40,746.700000,3364.400000,619.0,8280.0,0.00,144.380000,902.945,40.25,8.771458
28975,28975,LMDZZTVOL,Top,KHONKAEN,2025-07-20,Streak Orders,Lose,20,1.000000,4.509444,464.83,811.700000,3991.950000,507.0,7703.0,0.27,156.731500,902.945,40.25,8.771458

In [19]:
# Classify incentive direction (based on change in actual earnings versus reference)
week1['earnings_gap'] = week1['total_wage'] - week1['ref_wage']  # positive = payup, negative = paydown
week1['incentive_direction'] = week1['earnings_gap'].apply(lambda x: 'payup' if x > 0 else 'paydown')
week1

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size,ref_wage,ref_orders,ref_hours,earnings_gap,incentive_direction
0,0,LMD00BZBZ,Mid,SURIN,2025-07-14,Streak Orders,Swing,12,1.000000,2.602778,202.76,780.833333,3685.000000,329.0,5455.0,0.76,129.683333,556.830,33.00,7.663750,-354.070,paydown
1,1,LMD00BZBZ,Mid,SURIN,2025-07-15,Streak Orders,Swing,34,0.944444,7.714444,551.11,821.194444,3211.527778,89.0,9453.0,0.67,113.361389,556.830,33.00,7.663750,-5.720,paydown
2,2,LMD00BZBZ,Mid,SURIN,2025-07-18,Streak Orders,Swing,30,0.967742,5.717500,562.01,720.677419,3781.161290,693.0,7604.0,0.00,118.684839,556.830,33.00,7.663750,5.180,payup
3,3,LMD00BZBZ,Mid,SURIN,2025-07-19,Streak Orders,Swing,34,0.918919,7.772222,556.73,896.189189,2695.297297,473.0,9112.0,0.16,121.768649,556.830,33.00,7.663750,-0.100,paydown
4,4,LMD00BZBZ,Mid,SURIN,2025-07-20,Streak Orders,Swing,47,1.000000,10.237500,752.75,784.148936,3133.297872,265.0,8985.0,0.00,138.787234,556.830,33.00,7.663750,195.920,payup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28971,28971,LMDZZTVOL,Top,KHONKAEN,2025-07-16,Streak Orders,Lose,37,1.000000,7.463056,897.40,726.135135,3485.459459,200.0,8433.0,0.58,104.053514,902.945,40.25,8.771458,-5.545,paydown
28972,28972,LMDZZTVOL,Top,KHONKAEN,2025-07-17,Streak Orders,Lose,38,1.000000,7.770833,749.80,736.184211,2622.684211,185.0,7954.0,1.00,97.170526,902.945,40.25,8.771458,-153.145,paydown
28973,28973,LMDZZTVOL,Top,KHONKAEN,2025-07-18,Streak Orders,Lose,36,1.000000,8.472222,811.16,847.222222,3438.638889,650.0,9321.0,0.22,115.247778,902.945,40.25,8.771458,-91.785,paydown
28974,28974,LMDZZTVOL,Top,KHONKAEN,2025-07-19,Streak Orders,Lose,10,1.000000,2.074167,237.40,746.700000,3364.400000,619.0,8280.0,0.00,144.380000,902.945,40.25,8.771458,-665.545,paydown
28975,28975,LMDZZTVOL,Top,KHONKAEN,2025-07-20,Streak Orders,Lose,20,1.000000,4.509444,464.83,811.700000,3991.950000,507.0,7703.0,0.27,156.731500,902.945,40.25,8.771458,-438.115,paydown

In [14]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from statsmodels) (2.2.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [15]:
#test asymmetric response
import statsmodels.formula.api as smf
from scipy import stats

In [42]:
week0_week1 = pd.read_csv('./week0_vs_week1_results/driver_summary_wk0_wk1.csv')

In [6]:
#outcome variables to test
outcomes = ['orders_completed', 'acceptance_rate', 'hours_worked', 'total_wage']

In [ ]:
# Stack week0 and week1 at driver level
df = week0_week1.copy()
df['post'] = df['date'].isin(['2025-07-14', '2025-07-15', '2025-07-18', '2025-07-19',
       '2025-07-20', '2025-07-17', '2025-07-16']).astype(int)

# Merge baseline
df = df.merge(week0_baseline, on=['driver_id', 'region', 'Rider Group'], how='left')
df['earnings_gap_to_ref'] = df['total_wage'] - df['ref_wage']

# For week1 rows, classify direction based on incentive vs baseline
df['is_paydown'] = (df['post'] == 1) & (df['earnings_gap_to_ref'] < 0)
df['is_payup']   = (df['post'] == 1) & (df['earnings_gap_to_ref'] > 0)

df['incentive_direction'] = df['earnings_gap_to_ref'].apply(lambda x: 'payup' if x > 0 else 'paydown')

In [11]:
df

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size,post,ref_wage,ref_orders,ref_hours,earnings_gap_to_ref,is_paydown,is_payup,incentive_direction
0,0,LMD00BZBZ,Mid,SURIN,2025-07-10,No Incentive,Swing,41,0.953488,8.924722,649.42,783.581395,3057.046512,298.0,6895.0,0.00,159.917442,0,556.830,33.00,7.663750,92.590,False,False,payup
1,1,LMD00BZBZ,Mid,SURIN,2025-07-11,No Incentive,Swing,34,0.871795,8.221389,589.93,848.410256,2863.666667,442.0,6330.0,0.00,130.217436,0,556.830,33.00,7.663750,33.100,False,False,payup
2,2,LMD00BZBZ,Mid,SURIN,2025-07-12,No Incentive,Swing,30,0.810811,7.131111,572.37,915.270270,3307.972973,244.0,7419.0,0.33,112.129730,0,556.830,33.00,7.663750,15.540,False,False,payup
3,3,LMD00BZBZ,Mid,SURIN,2025-07-13,No Incentive,Swing,27,1.000000,6.377778,415.60,850.370370,2944.074074,290.0,7090.0,0.00,106.174074,0,556.830,33.00,7.663750,-141.230,False,False,paydown
4,4,LMD00BZBZ,Mid,SURIN,2025-07-14,Streak Orders,Swing,12,1.000000,2.602778,202.76,780.833333,3685.000000,329.0,5455.0,0.76,129.683333,1,556.830,33.00,7.663750,-354.070,True,False,paydown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44404,44404,LMDZZTVOL,Top,KHONKAEN,2025-07-16,Streak Orders,Lose,37,1.000000,7.463056,897.40,726.135135,3485.459459,200.0,8433.0,0.58,104.053514,1,902.945,40.25,8.771458,-5.545,True,False,paydown
44405,44405,LMDZZTVOL,Top,KHONKAEN,2025-07-17,Streak Orders,Lose,38,1.000000,7.770833,749.80,736.184211,2622.684211,185.0,7954.0,1.00,97.170526,1,902.945,40.25,8.771458,-153.145,True,False,paydown
44406,44406,LMDZZTVOL,Top,KHONKAEN,2025-07-18,Streak Orders,Lose,36,1.000000,8.472222,811.16,847.222222,3438.638889,650.0,9321.0,0.22,115.247778,1,902.945,40.25,8.771458,-91.785,True,False,paydown
44407,44407,LMDZZTVOL,Top,KHONKAEN,2025-07-19,Streak Orders,Lose,10,1.000000,2.074167,237.40,746.700000,3364.400000,619.0,8280.0,0.00,144.380000,1,902.945,40.25,8.771458,-665.545,True,False,paydown
44408,44408,LMDZZTVOL,Top,KHONKAEN,2025-07-20,Streak Orders,Lose,20,1.000000,4.509444,464.83,811.700000,3991.950000,507.0,7703.0,0.27,156.731500,1,902.945,40.25,8.771458,-438.115,True,False,paydown

In [52]:
df[df['is_payup'] == True]

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size,post,ref_wage,ref_orders,ref_hours,earnings_gap_to_ref,is_paydown,is_payup,incentive_direction
6,6,LMD00BZBZ,Mid,SURIN,2025-07-18,Streak Orders,Swing,30,0.967742,5.717500,562.01,720.677419,3781.161290,693.0,7604.0,0.00,118.684839,1,556.830000,33.000000,7.663750,5.180000,False,True,payup
8,8,LMD00BZBZ,Mid,SURIN,2025-07-20,Streak Orders,Swing,47,1.000000,10.237500,752.75,784.148936,3133.297872,265.0,8985.0,0.00,138.787234,1,556.830000,33.000000,7.663750,195.920000,False,True,payup
27,27,LMD025NCG,Mid,HAT YAI,2025-07-14,Streak Hours,Lose,14,1.000000,3.101944,309.48,797.642857,3077.000000,363.0,7978.0,NaN,140.875714,1,276.586667,11.333333,4.070556,32.893333,False,True,payup
38,38,LMD02DNNT,Top,RATCHABURI_Banpong,2025-07-14,No Incentive,Swing,38,0.716981,8.325556,911.63,857.886792,3872.735849,306.0,12597.0,4.21,117.373585,1,844.490000,37.000000,8.556389,67.140000,False,True,payup
41,41,LMD02DNNT,Top,RATCHABURI_Banpong,2025-07-17,No Incentive,Swing,40,0.606061,9.039444,1233.87,883.439394,4121.075758,50.0,12942.0,0.28,171.028939,1,844.490000,37.000000,8.556389,389.380000,False,True,payup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44366,44366,LMDZXTHFN,Mid,NAKHONPATHOM,2025-07-19,No Incentive,Lose,39,0.866667,8.118611,1381.73,754.244444,4293.644444,671.0,16153.0,0.00,128.972444,1,514.640000,12.750000,2.699306,867.090000,False,True,payup
44367,44367,LMDZXTHFN,Mid,NAKHONPATHOM,2025-07-20,No Incentive,Lose,35,0.813953,6.618611,1302.97,702.790698,3681.348837,22.0,12934.0,0.00,150.050698,1,514.640000,12.750000,2.699306,788.330000,False,True,payup
44375,44375,LMDZZ8ZTR,Mid,HAT YAI,2025-07-14,Streak Hours,Lose,35,0.921053,6.933333,838.64,728.289474,3316.052632,724.0,9556.0,NaN,138.636316,1,670.215000,28.000000,6.695903,168.425000,False,True,payup
44377,44377,LMDZZ8ZTR,Mid,HAT YAI,2025-07-16,Streak Hours,Lose,32,0.842105,5.784444,998.56,703.921053,4457.105263,468.0,17417.0,NaN,119.789211,1,670.215000,28.000000,6.695903,328.345000,False,True,payup
44403,44403,LMDZZTVOL,Top,KHONKAEN,2025-07-15,Streak Orders,Lose,40,1.000000,8.463333,924.84,761.700000,3626.875000,148.0,8453.0,0.00,110.908250,1,902.945000,40.250000,8.771458,21.895000,False,True,payup

In [51]:
df.columns

Index(['Unnamed: 0', 'driver_id', 'Rider Group', 'region', 'date', 'Incentive',
       'Status', 'orders_completed', 'acceptance_rate', 'hours_worked',
       'total_wage', 'avg_time_per_order_sec', 'avg_drop_distance',
       'closest_drop_distance', 'furthest_drop_distance', 'avg_rain',
       'avg_basket_size', 'post', 'ref_wage', 'ref_orders', 'ref_hours',
       'earnings_gap_to_ref', 'is_paydown', 'is_payup', 'incentive_direction'],
      dtype='object')

In [57]:
outcomes = ['orders_completed', 'acceptance_rate', 'hours_worked', 'total_wage']

In [58]:
df['post']

0        0
1        0
2        0
3        0
4        1
        ..
44404    1
44405    1
44406    1
44407    1
44408    1
Name: post, Length: 44409, dtype: int64

In [53]:
for direction, subset in [('paydown', df[df['incentive_direction']=='paydown'].copy()),
                           ('payup',   df[df['incentive_direction']=='payup'].copy())]:
    for outcome in outcomes:
        # Create a temporary subset with no NaNs for the variables in the model
        vars_in_model = [outcome, 'post', 'region', 'avg_rain', 'driver_id', 'Rider Group'] #verify columns exist 
        reg_data = subset[vars_in_model].dropna()

        model = smf.ols(
            f"{outcome} ~ post + C(region) + C(Q('Rider Group')) + avg_rain",
            data=reg_data
        ).fit(cov_type='cluster', cov_kwds={'groups': reg_data['driver_id']})
        
        coef = model.params['post']
        pval = model.pvalues['post']
        print(f"{direction} | {outcome}: coef={coef:.4f}, p={pval:.4f}")

paydown | orders_completed: coef=-1.2152, p=0.0000
paydown | acceptance_rate: coef=0.0316, p=0.0000
paydown | hours_worked: coef=-0.2553, p=0.0000
paydown | total_wage: coef=-56.6296, p=0.0000
payup | orders_completed: coef=-0.5651, p=0.0058
payup | acceptance_rate: coef=0.0473, p=0.0000
payup | hours_worked: coef=-0.1322, p=0.0020
payup | total_wage: coef=-97.2181, p=0.0000

In [ ]:
df['region_tier'] = df['region'].astype(str) + "_" + df['Rider Group'].astype(str)

for outcome in outcomes:
    formula = f"{outcome} ~ post : C(region_tier) + avg_rain + C(region_tier)"   
    model_df = df.dropna(subset=[outcome, 'post', 'region_tier', 'avg_rain'])
    
    model = smf.ols(formula, data=model_df).fit(
        cov_type='cluster', 
        cov_kwds={'groups': model_df['driver_id']}
    )
    
    print(f"\n--- Results for {outcome} ---")
    cohort_effects = model.params[model.params.index.str.contains('post:')]
    cohort_pvalues = model.pvalues[model.params.index.str.contains('post:')]
    # print(model.summary().tables[1])

    print("Top 5 Group Responses (Post-Incentive Change):")
    print(cohort_effects.sort_values(ascending=False).head(5))

--- Results for orders_completed ---
Top 5 Group Responses (Post-Incentive Change):
post:C(region_tier)[TRAT_Top]             1.449518
post:C(region_tier)[KRABI_Bottom]         1.207307
post:C(region_tier)[TAK_Maesot_Bottom]    1.127851
post:C(region_tier)[TRAT_Bottom]          0.486085
post:C(region_tier)[TRAT_Mid]             0.403490
dtype: float64

--- Results for acceptance_rate ---
Top 5 Group Responses (Post-Incentive Change):
post:C(region_tier)[UDONTHANI_Bottom]     0.145198
post:C(region_tier)[TAK_Maesot_Top]       0.141109
post:C(region_tier)[TAK_Maesot_Bottom]    0.132555
post:C(region_tier)[KHONKAEN_Bottom]      0.128188
post:C(region_tier)[UDONTHANI_Top]        0.117777
dtype: float64

--- Results for hours_worked ---
Top 5 Group Responses (Post-Incentive Change):
post:C(region_tier)[KRABI_Bottom]     0.283022
post:C(region_tier)[TRAT_Mid]         0.196105
post:C(region_tier)[CHIANGRAI_Mid]    0.129170
post:C(region_tier)[TRAT_Top]         0.127487
post:C(region_tier)[KHONKAEN_Top]     0.109974
dtype: float64

--- Results for total_wage ---
Top 5 Group Responses (Post-Incentive Change):
post:C(region_tier)[KRABI_Bottom]          22.223276
post:C(region_tier)[TRAT_Top]              20.332848
post:C(region_tier)[NONGKHAI_Bottom]       -2.397272
post:C(region_tier)[TRAT_Mid]              -5.086741
post:C(region_tier)[NAKHONSAWAN_Bottom]    -6.117600
dtype: float64

In [65]:
# for outcome in outcomes:
#     # expands to: post + is_paydown + (post : is_paydown)
#     formula = f"{outcome} ~ post * is_paydown + avg_rain + C(region)"
    
#     # Drop NaNs for these specific variables to avoid the length mismatch error
#     model_df = df.dropna(subset=[outcome, 'post', 'is_paydown', 'avg_rain', 'region', 'driver_id'])
    
#     model = smf.ols(formula, data=model_df).fit(
#         cov_type='cluster', 
#         cov_kwds={'groups': model_df['driver_id']}
#     )
    
#     print(f"\n--- Results for {outcome} ---")
#     # 'post:is_paydown' coefficient is test for asymmetry
#     asym_coef = model.params.get('post:is_paydown')
#     asym_p = model.pvalues.get('post:is_paydown')
    
#     print(f"Asymmetry (Interaction) Coef: {asym_coef:.4f}")
#     print(f"Asymmetry P-value: {asym_p:.4f}")
    
#     if asym_p < 0.05:
#         print("Result: Statistically significant evidence of asymmetry.")
#     else:
#         print("Result: No significant evidence of asymmetry.")

In [60]:
df_week1 = df[df['date'].isin(['2025-07-14', '2025-07-15', '2025-07-18', '2025-07-19',
       '2025-07-20', '2025-07-17', '2025-07-16'])]
df_week1

,Unnamed: 0,driver_id,Rider Group,region,date,Incentive,Status,orders_completed,acceptance_rate,hours_worked,total_wage,avg_time_per_order_sec,avg_drop_distance,closest_drop_distance,furthest_drop_distance,avg_rain,avg_basket_size,post,ref_wage,ref_orders,ref_hours,earnings_gap_to_ref,is_paydown,is_payup,incentive_direction
4,4,LMD00BZBZ,Mid,SURIN,2025-07-14,Streak Orders,Swing,12,1.000000,2.602778,202.76,780.833333,3685.000000,329.0,5455.0,0.76,129.683333,1,556.830,33.00,7.663750,-354.070,True,False,paydown
5,5,LMD00BZBZ,Mid,SURIN,2025-07-15,Streak Orders,Swing,34,0.944444,7.714444,551.11,821.194444,3211.527778,89.0,9453.0,0.67,113.361389,1,556.830,33.00,7.663750,-5.720,True,False,paydown
6,6,LMD00BZBZ,Mid,SURIN,2025-07-18,Streak Orders,Swing,30,0.967742,5.717500,562.01,720.677419,3781.161290,693.0,7604.0,0.00,118.684839,1,556.830,33.00,7.663750,5.180,False,True,payup
7,7,LMD00BZBZ,Mid,SURIN,2025-07-19,Streak Orders,Swing,34,0.918919,7.772222,556.73,896.189189,2695.297297,473.0,9112.0,0.16,121.768649,1,556.830,33.00,7.663750,-0.100,True,False,paydown
8,8,LMD00BZBZ,Mid,SURIN,2025-07-20,Streak Orders,Swing,47,1.000000,10.237500,752.75,784.148936,3133.297872,265.0,8985.0,0.00,138.787234,1,556.830,33.00,7.663750,195.920,False,True,payup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44404,44404,LMDZZTVOL,Top,KHONKAEN,2025-07-16,Streak Orders,Lose,37,1.000000,7.463056,897.40,726.135135,3485.459459,200.0,8433.0,0.58,104.053514,1,902.945,40.25,8.771458,-5.545,True,False,paydown
44405,44405,LMDZZTVOL,Top,KHONKAEN,2025-07-17,Streak Orders,Lose,38,1.000000,7.770833,749.80,736.184211,2622.684211,185.0,7954.0,1.00,97.170526,1,902.945,40.25,8.771458,-153.145,True,False,paydown
44406,44406,LMDZZTVOL,Top,KHONKAEN,2025-07-18,Streak Orders,Lose,36,1.000000,8.472222,811.16,847.222222,3438.638889,650.0,9321.0,0.22,115.247778,1,902.945,40.25,8.771458,-91.785,True,False,paydown
44407,44407,LMDZZTVOL,Top,KHONKAEN,2025-07-19,Streak Orders,Lose,10,1.000000,2.074167,237.40,746.700000,3364.400000,619.0,8280.0,0.00,144.380000,1,902.945,40.25,8.771458,-665.545,True,False,paydown
44408,44408,LMDZZTVOL,Top,KHONKAEN,2025-07-20,Streak Orders,Lose,20,1.000000,4.509444,464.83,811.700000,3991.950000,507.0,7703.0,0.27,156.731500,1,902.945,40.25,8.771458,-438.115,True,False,paydown

In [62]:
df_week1['gap'] = df_week1['total_wage'] - df_week1['ref_wage']
df_week1['gap_neg'] = df_week1['gap'].clip(upper=0)   # loss region
df_week1['gap_pos'] = df_week1['gap'].clip(lower=0)   # gain region

/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_74397/3805513024.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_week1['gap'] = df_week1['total_wage'] - df_week1['ref_wage']
/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_74397/3805513024.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_week1['gap_neg'] = df_week1['gap'].clip(upper=0)   # loss region
/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_74397/3805513024.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_week1['gap_pos'] = df_week1['gap'].clip(lower=0)   # gain region

In [63]:
import numpy as np

In [64]:
for outcome in outcomes:
    model_vars = [outcome, 'gap_neg', 'gap_pos', 'region', 'avg_rain', 'driver_id']
    
    subset = df_week1[model_vars].dropna()
    
    # fit the model
    model = smf.ols(
        f"{outcome} ~ gap_neg + gap_pos + C(region) + avg_rain",
        data=subset
    ).fit(cov_type='cluster', cov_kwds={'groups': subset['driver_id']})
    
    # results
    coef_neg = model.params.get('gap_neg', np.nan)
    coef_pos = model.params.get('gap_pos', np.nan)
    
    print(f"\n--- {outcome} ---")
    print(f"  Loss slope: {coef_neg:.4f} | Gain slope: {coef_pos:.4f}")
    
    # tests if the two slopes are statistically different
    wald_test = model.f_test("gap_neg = gap_pos")
    print(f"  Kink test p-value: {wald_test.pvalue:.4f}")

--- orders_completed ---
  Loss slope: 0.0097 | Gain slope: 0.0227
  Kink test p-value: 0.0000

--- acceptance_rate ---
  Loss slope: 0.0001 | Gain slope: -0.0003
  Kink test p-value: 0.0000

--- hours_worked ---
  Loss slope: 0.0024 | Gain slope: 0.0044
  Kink test p-value: 0.0001

--- total_wage ---
  Loss slope: 0.0805 | Gain slope: 1.2318
  Kink test p-value: 0.0000