In [1]:
import pandas as pd 
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
#getting an overview of all 30 cities 
baseline_data = pd.read_csv('../progress_metrics/daily_guarantee/daily_guarantee_results_updated_2/daily_guarantee_daily_productivity_tiers_merged_0710-0713.csv')

In [4]:
baseline_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446844 entries, 0 to 446843
Data columns (total 37 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Unnamed: 0.1                                446844 non-null  int64
 1   region                                      446844 non-null  object
 2   driver_id                                   446844 non-null  object
 3   assign_created_at                           446844 non-null  object
 4   restaurant_name                             446844 non-null  object
 5   restaurant_category                         446844 non-null  object
 6   order_id                                    446844 non-null  object
 7   is_driver_accept                            446844 non-null  bool
 8   wage                                        446844 non-null  float64
 9   on_top_fare                                 446844 non-null  float64
 10  basket_size                                 446844 non-null  float64
 11  drop_off_distance                           446844 non-null  float64
 12  distance_rider_to_restaurant                446844 non-null  float64
 13  placed_to_match_second                      446844 non-null  int64
 14  rider_matched_to_arrived_restaurant_second  446844 non-null  int64
 15  rider_waiting_time_in_restaurant_second     446844 non-null  int64
 16  delivery_time_to_user_second                446844 non-null  int64
 17  total_user_waiting_time_second              446844 non-null  int64
 18  order_status                                446844 non-null  object
 19  date                                        446844 non-null  object
 20  region::multi-filter                        396920 non-null  object
 21  avg_rain                                    396920 non-null  float64
 22  Rain_Level                                  396920 non-null  object
 23  Rider Group                                 445026 non-null  object
 24  Start Date                                  445026 non-null  object
 25  End Date                                    445026 non-null  object
 26  Incentive                                   446844 non-null  object
 27  daily_order_count                           446844 non-null  int64
 28  time_per_order_sec                          446844 non-null  int64
 29  time_worked_sec                             446844 non-null  int64
 30  hour                                        446844 non-null  int64
 31  daily_cumulative_time_sec                   446844 non-null  int64
 32  time_worked_in_window_sec                   446844 non-null  int64
 33  window_cumulative_sec                       446844 non-null  int64
 34  daily_cumulative_time_hr                    446844 non-null  float64
 35  window_cumulative_hr                        446844 non-null  float64
 36  Status                                      445054 non-null  object
dtypes: bool(1), float64(8), int64(13), object(15)
memory usage: 123.2+ MB

In [5]:
baseline_data.head(5)

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.00,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose
1,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.00,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.0,Lose
2,2,SISAKET,LMD6ZOP8E,2025-07-10 00:00:26.512,ครัวคุณโต้ง อาหาร/เครื่องดื่ม (Krue.kun.tong) ...,Fastfood,LMF-250710-357336867,True,17.00,2.0,130.00,2822.0,2241.9,17,601,583,29,1230,COMPLETED,2025-07-10,SISAKET,0.000000,no-rain,Mid,2025-07-10,2025-07-13,No Incentive,1,612,612,0,612,0,0,0.170000,0.0,Win
3,3,KHONKAEN,LMDK8T3XZ,2025-07-10 00:00:27.543,เจียวกะพี่หมี ( หอพักสุทธิลักษณ์ ตึกA ),Rice Dish,LMF-250710-728920242,True,19.00,0.0,107.66,785.0,1237.8,11,1011,194,145,1361,COMPLETED,2025-07-10,KHONKAEN,0.000000,no-rain,Mid,2025-07-10,2025-07-13,No Incentive,1,339,339,0,339,0,0,0.094167,0.0,Lose
4,4,CHIANGRAI,LMDMG4ZNH,2025-07-10 00:01:01.135,สถานีแจ่วฮ้อน MFU,Thai,LMF-250710-664531507,False,48.40,0.0,198.00,9902.0,829.2,0,0,0,0,0,EXPIRED,2025-07-10,CHIANGRAI,0.000000,no-rain,Bottom,2025-07-10,2025-07-13,No Incentive,0,0,0,0,0,0,0,0.000000,0.0,Lose

In [6]:
baseline_data[baseline_data['driver_id'] == 'LMDCSO52Z']

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose
23335,23335,UDONTHANI,LMDCSO52Z,2025-07-10 10:59:50.639,Five Star (ห้าดาว) ดูโฮม อุดรธานี,Barbeque/Grill,LMF-250710-419574625,False,24.00,5.0,165.0,3399.0,2002.2,0,0,0,0,0,EXPIRED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,0,0,10,472,0,0,0.131111,0.000000,Lose
26735,26735,UDONTHANI,LMDCSO52Z,2025-07-10 11:16:01.800,ครัวพุงกาง (Pung Kang Kitchen),À La Carte,LMF-250710-984283443,True,19.00,5.0,162.0,4205.0,2591.6,464,293,527,454,1738,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,2,981,981,11,1453,981,981,0.403611,0.272500,Lose
28080,28080,UDONTHANI,LMDCSO52Z,2025-07-10 11:22:21.890,ตำแซ่บอุดรธานี 1 (หน้าราชภัฏอุดร) (Tam Zaab Ud...,North East,LMF-250710-802551523,False,43.92,5.0,80.0,8498.0,3546.2,1046,452,949,406,2853,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,2,1355,0,11,1453,0,981,0.403611,0.272500,Lose
28248,28248,UDONTHANI,LMDCSO52Z,2025-07-10 11:23:11.190,อาหารตามสั่งครัวออโต้ (กะเพราแท้) (Auto Kitche...,À La Carte,LMF-250710-730251463,True,19.00,5.0,130.0,527.0,1659.9,35,554,55,174,818,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,3,229,229,11,1682,229,1210,0.467222,0.336111,Lose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443633,443633,UDONTHANI,LMDCSO52Z,2025-07-13 22:00:52.190,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250713-697795162,True,24.00,5.0,94.0,2189.0,1882.3,10,296,887,252,1445,COMPLETED,2025-07-13,UDONTHANI,1.315250,Light,Top,2025-07-10,2025-07-13,No Incentive,36,1139,1139,22,27922,0,13835,7.756111,3.843056,Lose
444735,444735,UDONTHANI,LMDCSO52Z,2025-07-13 22:29:53.257,is it ลาบยโส,North East,LMF-250713-685190429,True,24.00,0.0,60.0,4766.0,1614.6,3,221,145,624,993,COMPLETED,2025-07-13,UDONTHANI,1.315250,Light,Top,2025-07-10,2025-07-13,No Incentive,37,769,769,22,28691,0,13835,7.969722,3.843056,Lose
445260,445260,UDONTHANI,LMDCSO52Z,2025-07-13 22:45:50.102,ต.กระเพราระเบิด (Spicy Lab Udon Made-to-Order ...,À La Carte,LMF-250713-810260717,True,24.00,0.0,60.0,2086.0,2564.9,1,370,79,249,699,COMPLETED,2025-07-13,UDONTHANI,1.315250,Light,Top,2025-07-10,2025-07-13,No Incentive,38,328,328,22,29019,0,13835,8.060833,3.843056,Lose
446217,446217,UDONTHANI,LMDCSO52Z,2025-07-13 23:22:47.923,ณำนารา - Namnara,Café/Coffee Shop,LMF-250713-797684090,True,24.00,2.0,181.0,3358.0,3721.2,4,584,191,510,1289,COMPLETED,2025-07-13,UDONTHANI,1.315250,Light,Top,2025-07-10,2025-07-13,No Incentive,39,701,701,23,29720,0,13835,8.255556,3.843056,Lose
446651,446651,UDONTHANI,LMDCSO52Z,2025-07-13 23:45:43.330,ชายสี่บะหมี่เกี๊ยว By เฮียยศ (หน้าวัดโพธิวรารา...,Noodles,LMF-250713-049284805,True,28.76,0.0,160.0,5738.0,499.2,22,121,319,805,1267,COMPLETED,2025-07-13,UDONTHANI,1.315250,Light,Top,2025-07-10,2025-07-13,No Incentive,40,1124,1124,23,30844,0,13835,8.567778,3.843056,Lose

In [7]:
baseline_data.columns

Index(['Unnamed: 0.1', 'region', 'driver_id', 'assign_created_at',
       'restaurant_name', 'restaurant_category', 'order_id',
       'is_driver_accept', 'wage', 'on_top_fare', 'basket_size',
       'drop_off_distance', 'distance_rider_to_restaurant',
       'placed_to_match_second', 'rider_matched_to_arrived_restaurant_second',
       'rider_waiting_time_in_restaurant_second',
       'delivery_time_to_user_second', 'total_user_waiting_time_second',
       'order_status', 'date', 'region::multi-filter', 'avg_rain',
       'Rain_Level', 'Rider Group', 'Start Date', 'End Date', 'Incentive',
       'daily_order_count', 'time_per_order_sec', 'time_worked_sec', 'hour',
       'daily_cumulative_time_sec', 'time_worked_in_window_sec',
       'window_cumulative_sec', 'daily_cumulative_time_hr',
       'window_cumulative_hr', 'Status'],
      dtype='object')

In [8]:
statuses = pd.read_csv('../region_status.csv')
statuses

   status       region
0    Lose  CHANTHABURI
1    Lose  CHANTHABURI
2    Lose  CHANTHABURI
3    Lose    CHIANGRAI
4    Lose    CHIANGRAI
..    ...          ...
85   Lose    UTTARADIT
86   Lose    UTTARADIT
87    Win     YASOTHON
88    Win     YASOTHON
89    Win     YASOTHON

[90 rows x 2 columns]

In [9]:
total_count = baseline_data.groupby(['driver_id','date']).agg(
    total_orders= ('daily_order_count', 'max'),
    total_sec_worked=('daily_cumulative_time_sec','max'),
    total_hours_worked = ('daily_cumulative_time_hr', 'max'))

baseline_data = baseline_data.merge(total_count, on=['driver_id', 'date'], how='left')

In [10]:
baseline_data = baseline_data.merge(statuses, on = 'region', how = 'left')

In [11]:
baseline_data.head(4)

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status,total_orders,total_sec_worked,total_hours_worked,status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
1,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
2,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
3,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.0,Lose,30,29410,8.169444,Lose

In [12]:
baseline_data[baseline_data['driver_id'] == 'LMDCSO52Z']['total_hours_worked'].unique()

array([7.93444444, 6.405     , 5.63611111, 8.56777778])

In [13]:
baseline_data['date'] = pd.to_datetime(baseline_data['date'])

In [14]:
regions = [
    "CHANTHABURI", "CHIANGRAI", "CHUMPHON", "HAT YAI", "KANCHANABURI",
    "KHONKAEN", "KRABI", "LAMPANG", "NAKHONNAYOK", "NAKHONPATHOM",
    "NAKHONSAWAN", "NAKHONSRITHAMMARAT", "NONGKHAI", "PHAYAO",
    "PHETCHABURI_Chaam", "PRACHINBURI", "RATCHABURI_Banpong",
    "SAKAEO_Aranyaprathet", "SAKONNAKHON", "SARABURI_Nongkhae",
    "SARABURI_Phraphutthabat", "SISAKET", "SONGKHLA_City",
    "SURATTHANI_City", "SURIN", "TAK_Maesot", "TRAT", "UDONTHANI",
    "UTTARADIT", "YASOTHON"
]

baseline_data = baseline_data[baseline_data["region"].isin(regions)]

In [15]:
baseline_data

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status,total_orders,total_sec_worked,total_hours_worked,status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
1,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
2,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
3,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.000000,Lose,30,29410,8.169444,Lose
4,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.000000,Lose,30,29410,8.169444,Lose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1336947,446842,HAT YAI,LMDPBNV24,2025-07-13 23:59:57.488,Tanji Ramen สาขาจุติ,Japanese,LMF-250713-567050464,True,18.71,0.0,169.0,2173.0,1497.7,7,977,492,283,1759,COMPLETED,2025-07-13,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,20,775,775,23,17108,0,5705,4.752222,1.584722,Lose,20,17108,4.752222,Lose
1336948,446842,HAT YAI,LMDPBNV24,2025-07-13 23:59:57.488,Tanji Ramen สาขาจุติ,Japanese,LMF-250713-567050464,True,18.71,0.0,169.0,2173.0,1497.7,7,977,492,283,1759,COMPLETED,2025-07-13,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,20,775,775,23,17108,0,5705,4.752222,1.584722,Lose,20,17108,4.752222,Lose
1336949,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose
1336950,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose
1336951,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose

In [16]:
baseline_data_accepted = baseline_data[baseline_data['is_driver_accept'] == True]

In [17]:
baseline_data_accepted.head(5)

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status,total_orders,total_sec_worked,total_hours_worked,status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
1,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
2,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.0,Lose,37,28564,7.934444,Lose
3,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.0,Lose,30,29410,8.169444,Lose
4,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.0,Lose,30,29410,8.169444,Lose

In [18]:
baseline_data_accepted[baseline_data_accepted['region'] == 'CHIANG_MAI']['driver_id'].unique()

array([], dtype=object)

In [19]:
driver_counts_region = baseline_data_accepted.groupby(['region'])['driver_id'].nunique()
driver_counts_city_group = baseline_data_accepted.groupby(['status'])['driver_id'].nunique()
driver_counts_driver_group = baseline_data_accepted.groupby(['Rider Group'])['driver_id'].nunique()

In [20]:
#overall cities information
cities_stats = baseline_data_accepted.groupby(['region', 'status']).agg(
    total_orders = ('order_id', 'nunique'),
    total_drivers = ('driver_id', 'nunique'),
    avg_wage=('wage', 'mean'), 
    avg_basked=('basket_size', 'mean'), 
    avg_drop_distance=('drop_off_distance', 'mean'), 
    avg_orders_daily = ('total_orders','mean'),
    avg_hours_daily = ('total_hours_worked','mean'), 
).reset_index() 

#acceptance rate per city
acc_rate = baseline_data.groupby('region')['is_driver_accept'].mean().reset_index()
acc_rate = acc_rate.rename(columns={'is_driver_accept':"acceptance_rate"}) 

#all cities data 
cities_info = cities_stats.merge(acc_rate, on='region')

#split into 3 quartiles based on acceptance rate 
p33, p67 = cities_info["acceptance_rate"].quantile([0.33, 0.67])
cities_info["city_type"] = pd.cut(
    cities_info["acceptance_rate"],
    bins=[-np.inf, p33, p67, np.inf],
    labels=["Q1", "Q2", "Q3"],
)

cities_info.head()

,region,status,total_orders,total_drivers,avg_wage,avg_basked,avg_drop_distance,avg_orders_daily,avg_hours_daily,acceptance_rate,city_type
0,CHANTHABURI,Lose,10887,133,18.305905,144.998494,3489.828762,38.370267,7.950334,0.872078,Q2
1,CHIANGRAI,Lose,18825,387,20.948456,124.355264,3227.486562,27.032256,5.634661,0.655492,Q1
2,CHUMPHON,Win,12541,117,13.688194,135.340862,2702.760306,43.220863,8.395518,0.797772,Q1
3,HAT YAI,Lose,28855,516,21.299361,140.510600,3463.515753,27.785089,6.044613,0.893881,Q2
4,KANCHANABURI,Swing,10211,156,18.840760,148.539783,3347.584714,29.554689,5.985101,0.904107,Q3

In [21]:
cities_info.to_csv('./results/cities_stats.csv')

In [22]:
#get volume by driver_type and region 
city_volume = baseline_data_accepted.groupby(['Rider Group', 'region'])['order_id'].nunique().reset_index().rename(columns={'order_id':'order_volume'}).sort_values("order_volume",ascending=False)
city_volume.head()

   Rider Group        region  order_volume
65         Top      KHONKAEN         19080
35         Mid      KHONKAEN         12948
63         Top       HAT YAI         11868
33         Mid       HAT YAI         11689
39         Mid  NAKHONPATHOM          9811

In [23]:
#helper function to get all the statistical metrics we want 
def describe_full(series, label): 
    s = series.dropna() 
    return pd.DataFrame([{
        'metric': label, 
        'n' : len(s), 
        'mean': s.mean(), 
        'std' : s.std(),
        "min": s.quantile(0.25), 
        'median': s.median(), 
        'Q3': s.quantile(0.75), 
        'max': s.max()
    }])

In [24]:
baseline_data_accepted.groupby('driver_id')

In [25]:
baseline_data_accepted

,Unnamed: 0.1,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status,total_orders,total_sec_worked,total_hours_worked,status
0,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
1,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
2,0,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,138.0,1675.0,594.7,5,441,197,275,918,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,No Incentive,1,472,472,0,472,0,0,0.131111,0.000000,Lose,37,28564,7.934444,Lose
3,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.000000,Lose,30,29410,8.169444,Lose
4,1,HAT YAI,LMD2P96XU,2025-07-10 00:00:11.812,Akita ชานมไข่มุก (Akita Bubble Tea) ตลาดศรีตรั...,Cafe,LMF-250710-967446340,True,22.00,0.0,123.0,3849.0,831.5,8,149,339,453,949,COMPLETED,2025-07-10,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,1,792,792,0,792,0,0,0.220000,0.000000,Lose,30,29410,8.169444,Lose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1336947,446842,HAT YAI,LMDPBNV24,2025-07-13 23:59:57.488,Tanji Ramen สาขาจุติ,Japanese,LMF-250713-567050464,True,18.71,0.0,169.0,2173.0,1497.7,7,977,492,283,1759,COMPLETED,2025-07-13,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,20,775,775,23,17108,0,5705,4.752222,1.584722,Lose,20,17108,4.752222,Lose
1336948,446842,HAT YAI,LMDPBNV24,2025-07-13 23:59:57.488,Tanji Ramen สาขาจุติ,Japanese,LMF-250713-567050464,True,18.71,0.0,169.0,2173.0,1497.7,7,977,492,283,1759,COMPLETED,2025-07-13,NaN,NaN,NaN,Top,2025-07-10,2025-07-13,No Incentive,20,775,775,23,17108,0,5705,4.752222,1.584722,Lose,20,17108,4.752222,Lose
1336949,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose
1336950,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose
1336951,446843,KHONKAEN,LMD60148N,2025-07-13 23:59:57.768,One World at KKU วันเวิลด์ ปังปิ้ง บิงซู Toast...,Dessert,LMF-250713-586444915,True,21.66,0.0,69.0,1347.0,3975.5,6,1010,6,223,1245,COMPLETED,2025-07-13,KHONKAEN,0.120000,Light,Mid,2025-07-10,2025-07-13,No Incentive,33,229,229,23,29071,0,6677,8.075278,1.854722,Lose,33,29071,8.075278,Lose

In [26]:
daily = baseline_data_accepted.groupby(['driver_id', 'date', 'Rider Group', 'region', 'status']).agg(
    num_daily_orders=('daily_order_count','max'),
    total_hours_worked=('total_hours_worked', 'max'),
    total_wage=('wage', 'sum')
).reset_index()

days_worked = baseline_data_accepted.groupby('driver_id').agg(
    num_days_worked = ('date', 'nunique')).reset_index()

daily = daily.merge(days_worked, on=['driver_id'], how='left')

daily

,driver_id,date,Rider Group,region,status,num_daily_orders,total_hours_worked,total_wage,num_days_worked
0,LMD00BZBZ,2025-07-10,Mid,SURIN,Swing,41,8.924722,1812.30,4
1,LMD00BZBZ,2025-07-11,Mid,SURIN,Swing,34,8.221389,1527.60,4
2,LMD00BZBZ,2025-07-12,Mid,SURIN,Swing,30,7.131111,1304.40,4
3,LMD00BZBZ,2025-07-13,Mid,SURIN,Swing,27,6.377778,1246.80,4
4,LMD01NAMM,2025-07-10,Bottom,UTTARADIT,Lose,19,4.865833,925.20,3
...,...,...,...,...,...,...,...,...,...
15301,LMDZZPA6L,2025-07-13,Bottom,KRABI,Win,29,6.372222,1552.20,4
15302,LMDZZTVOL,2025-07-10,Top,KHONKAEN,Lose,37,7.212778,2463.09,4
15303,LMDZZTVOL,2025-07-11,Top,KHONKAEN,Lose,39,8.561111,2345.88,4
15304,LMDZZTVOL,2025-07-12,Top,KHONKAEN,Lose,44,9.945278,3160.44,4
15305,LMDZZTVOL,2025-07-13,Top,KHONKAEN,Lose,41,9.366667,2741.94,4

In [27]:
daily.to_csv('./results/daily_driver_stats.csv')

In [28]:
stats = []

for (region, rider_group, status), group in daily.groupby(['region', 'Rider Group', 'status']):
    for metric, label in [
        ('num_days_worked',    'Days worked'),
        ('num_daily_orders',   'Daily orders'),
        ('total_hours_worked', 'Daily hours worked'),
        ('total_wage', 'Daily Wage')
    ]:
        row = describe_full(group[metric], label)
        row['region']     = region
        row['rider_group'] = rider_group
        row['status'] = status
        stats.append(row)

regional_drivers = baseline_data_accepted.groupby('region')['driver_id'].nunique().reset_index()
regional_drivers.columns = ['region', 'total_regional_drivers']

#get group counts of number of drivers per tier per region
group_counts = baseline_data_accepted.groupby(['region', 'Rider Group'])['driver_id'].nunique().unstack(fill_value=0)

group_counts.columns = [f'num_{col.lower()}_drivers' for col in group_counts.columns]

#Reset index so 'region' becomes a column for merging
group_counts = group_counts.reset_index()

stats = pd.concat(stats, ignore_index=True)
stats = stats.merge(regional_drivers, on = 'region', how = 'left')
stats = stats.merge(group_counts, on='region', how='left')

stats

,metric,n,mean,std,min,median,Q3,max,region,rider_group,status,total_regional_drivers,num_bottom_drivers,num_mid_drivers,num_top_drivers
0,Days worked,99,2.717172,0.979800,2.000000,3.000000,3.000000,4.000000,CHANTHABURI,Bottom,Lose,133,44,51,38
1,Daily orders,99,17.989899,13.012941,7.000000,14.000000,25.000000,51.000000,CHANTHABURI,Bottom,Lose,133,44,51,38
2,Daily hours worked,99,3.945772,2.901373,1.595278,3.146389,5.590139,12.011111,CHANTHABURI,Bottom,Lose,133,44,51,38
3,Daily Wage,99,999.733030,735.729504,444.900000,790.800000,1327.200000,3001.170000,CHANTHABURI,Bottom,Lose,133,44,51,38
4,Days worked,152,3.355263,0.871992,3.000000,4.000000,4.000000,4.000000,CHANTHABURI,Mid,Lose,133,44,51,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,Daily Wage,89,1002.028315,577.382475,590.430000,884.400000,1456.200000,2337.180000,YASOTHON,Mid,Win,81,27,30,24
356,Days worked,82,3.658537,0.652053,3.000000,4.000000,4.000000,4.000000,YASOTHON,Top,Win,81,27,30,24
357,Daily orders,82,33.158537,15.241650,22.250000,33.500000,44.000000,66.000000,YASOTHON,Top,Win,81,27,30,24
358,Daily hours worked,82,6.610779,2.595939,4.546667,6.983472,8.494444,12.205278,YASOTHON,Top,Win,81,27,30,24
359,Daily Wage,82,1781.533537,787.352996,1223.100000,1821.735000,2403.750000,3372.150000,YASOTHON,Top,Win,81,27,30,24

In [43]:
stats.columns

Index(['metric', 'n', 'mean', 'std', 'min', 'median', 'Q3', 'max', 'region',
       'rider_group', 'status', 'total_regional_drivers', 'num_bottom_drivers',
       'num_mid_drivers', 'num_top_drivers'],
      dtype='object')

In [29]:
stats.to_csv('./results/overall_region_stats.csv')

In [30]:
pd.set_option('display.max_rows', None)

In [31]:
region_stats = []

for (region, status), group in daily.groupby(['region', 'status']):
    for metric, label in [
        ('num_days_worked',    'Days worked'),
        ('num_daily_orders',   'Daily orders'),
        ('total_hours_worked', 'Daily hours worked'),
        ('total_wage', 'Daily Wage'),
    ]:
        row = describe_full(group[metric], label)
        row['region'] = region
        row['status'] = status
        region_stats.append(row)

regional_drivers = baseline_data_accepted.groupby('region')['driver_id'].nunique().reset_index()
regional_drivers.columns = ['region', 'total_regional_drivers']

region_stats = pd.concat(region_stats, ignore_index=True)
region_stats = region_stats.merge(regional_drivers, on = 'region', how = 'left')

region_stats

,metric,n,mean,std,min,median,Q3,max,region,status,total_regional_drivers
0,Days worked,376,3.239362,0.904002,3.000000,3.500000,4.000000,4.000000,CHANTHABURI,Lose,133
1,Daily orders,376,29.571809,16.151785,15.750000,30.000000,43.250000,66.000000,CHANTHABURI,Lose,133
2,Daily hours worked,376,6.188207,3.430823,3.425000,6.116944,8.853889,15.229167,CHANTHABURI,Lose,133
3,Daily Wage,376,1624.016170,883.406908,839.107500,1637.895000,2373.000000,3715.080000,CHANTHABURI,Lose,133
4,Days worked,1110,3.288288,0.899728,3.000000,4.000000,4.000000,4.000000,CHIANGRAI,Lose,387
5,Daily orders,1110,17.316216,12.976778,7.000000,14.000000,25.000000,61.000000,CHIANGRAI,Lose,387
6,Daily hours worked,1110,3.679345,2.741983,1.391319,3.000417,5.483889,13.996944,CHIANGRAI,Lose,387
7,Daily Wage,1110,1088.243973,806.109263,431.400000,890.400000,1617.525000,3562.740000,CHIANGRAI,Lose,387
8,Days worked,359,3.406685,0.823238,3.000000,4.000000,4.000000,4.000000,CHUMPHON,Win,117
9,Daily orders,359,35.515320,16.565906,22.000000,37.000000,50.000000,64.000000,CHUMPHON,Win,117
10,Daily hours worked,359,7.073402,3.131962,4.570417,7.323333,9.558611,14.462778,CHUMPHON,Win,117
11,Daily Wage,359,1458.421755,669.597369,910.575000,1531.260000,2031.030000,2788.110000,CHUMPHON,Win,117
12,Days worked,1557,3.398202,0.848829,3.000000,4.000000,4.000000,4.000000,HAT YAI,Lose,516
13,Daily orders,1557,18.848426,12.982691,8.000000,16.000000,27.000000,61.000000,HAT YAI,Lose,516
14,Daily hours worked,1557,4.278992,2.752111,1.962778,3.917222,6.430278,15.183611,HAT YAI,Lose,516
15,Daily Wage,1557,1204.378324,805.014082,538.080000,1075.320000,1758.600000,4147.920000,HAT YAI,Lose,516
16,Days worked,470,3.365957,0.837622,3.000000,4.000000,4.000000,4.000000,KANCHANABURI,Swing,156
17,Daily orders,470,21.825532,13.002025,11.000000,20.000000,32.000000,56.000000,KANCHANABURI,Swing,156
18,Daily hours worked,470,4.514854,2.602432,2.356597,4.272083,6.492083,11.424167,KANCHANABURI,Swing,156
19,Daily Wage,470,1233.628851,728.867276,626.992500,1128.900000,1833.285000,3078.150000,KANCHANABURI,Swing,156
20,Days worked,1746,3.331042,0.881734,3.000000,4.000000,4.000000,4.000000,KHONKAEN,Lose,596
21,Daily orders,1746,22.735968,14.484599,11.000000,21.000000,32.000000,77.000000,KHONKAEN,Lose,596
22,Daily hours worked,1746,5.087029,3.224292,2.374167,4.705139,7.368958,20.716944,KHONKAEN,Lose,596
23,Daily Wage,1746,1472.289364,925.874566,689.250000,1369.080000,2125.897500,4639.410000,KHONKAEN,Lose,596
24,Days worked,835,3.409581,0.814970,3.000000,4.000000,4.000000,4.000000,KRABI,Win,271
25,Daily orders,835,27.220359,14.883055,15.000000,25.000000,38.000000,67.000000,KRABI,Win,271
26,Daily hours worked,835,5.104982,2.683967,2.990833,4.987222,7.049583,15.528611,KRABI,Win,271
27,Daily Wage,835,1330.156240,724.739172,765.900000,1252.200000,1902.900000,3847.020000,KRABI,Win,271
28,Days worked,588,3.302721,0.881492,3.000000,4.000000,4.000000,4.000000,LAMPANG,Swing,202
29,Daily orders,588,23.959184,13.974851,12.000000,22.000000,35.000000,70.000000,LAMPANG,Swing,202
30,Daily hours worked,588,5.265086,3.058929,2.713542,5.172778,7.345208,15.572222,LAMPANG,Swing,202
31,Daily Wage,588,1282.792194,724.695433,665.700000,1242.300000,1857.750000,3286.320000,LAMPANG,Swing,202
32,Days worked,201,3.477612,0.781503,3.000000,4.000000,4.000000,4.000000,NAKHONNAYOK,Win,63
33,Daily orders,201,27.477612,14.209530,16.000000,27.000000,38.000000,60.000000,NAKHONNAYOK,Win,63
34,Daily hours worked,201,5.518213,2.876068,3.236389,5.474167,7.736389,12.872778,NAKHONNAYOK,Win,63
35,Daily Wage,201,1463.797313,762.003692,803.550000,1487.970000,2018.940000,3223.140000,NAKHONNAYOK,Win,63
36,Days worked,1258,3.550079,0.718737,3.000000,4.000000,4.000000,4.000000,NAKHONPATHOM,Lose,382
37,Daily orders,1258,20.178060,13.673547,9.000000,18.000000,29.000000,65.000000,NAKHONPATHOM,Lose,382
38,Daily hours worked,1258,4.490723,2.983413,2.100417,3.975556,6.406806,15.599444,NAKHONPATHOM,Lose,382
39,Daily Wage,1258,1661.845970,1108.748803,753.082500,1448.280000,2433.195000,5196.450000,NAKHONPATHOM,Lose,382
40,Days worked,274,3.372263,0.905881,3.000000,4.000000,4.000000,4.000000,NAKHONSAWAN,Lose,93
41,Daily orders,274,17.397810,10.567356,9.000000,17.000000,25.000000,45.000000,NAKHONSAWAN,Lose,93
42,Daily hours worked,274,4.045564,2.432924,2.123889,3.881250,5.719444,11.211667,NAKHONSAWAN,Lose,93
43,Daily Wage,274,1153.368175,699.002083,568.800000,1111.500000,1688.775000,2930.100000,NAKHONSAWAN,Lose,93
44,Days worked,645,3.316279,0.864661,3.000000,4.000000,4.000000,4.000000,NAKHONSRITHAMMARAT,Swing,219
45,Daily orders,645,26.917829,15.735619,15.000000,25.000000,38.000000,71.000000,NAKHONSRITHAMMARAT,Swing,219
46,Daily hours worked,645,5.606519,3.112330,3.200000,5.292500,7.755556,14.954444,NAKHONSRITHAMMARAT,Swing,219
47,Daily Wage,645,1394.229628,786.819101,750.360000,1300.800000,1963.680000,4037.280000,NAKHONSRITHAMMARAT,Swing,219
48,Days worked,266,3.270677,0.865505,3.000000,4.000000,4.000000,4.000000,NONGKHAI,Swing,91
49,Daily orders,266,24.398496,13.886027,14.000000,22.000000,35.000000,60.000000,NONGKHAI,Swing,91
50,Daily hours worked,266,4.772297,2.590237,2.747014,4.450556,6.745000,11.099167,NONGKHAI,Swing,91
51,Daily Wage,266,1401.983346,797.625298,783.900000,1245.120000,1998.150000,3729.000000,NONGKHAI,Swing,91
52,Days worked,160,3.087500,0.856991,3.000000,3.000000,4.000000,4.000000,PHAYAO,Swing,59
53,Daily orders,160,29.306250,16.049843,15.000000,30.000000,43.000000,57.000000,PHAYAO,Swing,59
54,Daily hours worked,160,5.590049,3.021677,2.900903,5.882083,7.958611,13.008889,PHAYAO,Swing,59
55,Daily Wage,160,1431.875250,802.844515,686.850000,1432.800000,2173.185000,2831.280000,PHAYAO,Swing,59
56,Days worked,207,3.589372,0.724390,3.000000,4.000000,4.000000,4.000000,PHETCHABURI_Chaam,Swing,63
57,Daily orders,207,27.541063,11.679665,20.000000,28.000000,35.000000,55.000000,PHETCHABURI_Chaam,Swing,63
58,Daily hours worked,207,5.368857,2.285102,3.768889,5.463056,6.631667,10.725000,PHETCHABURI_Chaam,Swing,63
59,Daily Wage,207,1804.376087,766.514028,1308.525000,1815.510000,2263.800000,3797.850000,PHETCHABURI_Chaam,Swing,63
60,Days worked,444,3.270270,0.935345,3.000000,4.000000,4.000000,4.000000,PRACHINBURI,Swing,157
61,Daily orders,444,24.072072,14.759142,12.000000,22.000000,35.000000,69.000000,PRACHINBURI,Swing,157
62,Daily hours worked,444,4.443097,2.618116,2.308889,4.186944,6.380694,11.991389,PRACHINBURI,Swing,157
63,Daily Wage,444,1215.285135,726.456670,660.412500,1118.085000,1767.435000,3294.660000,PRACHINBURI,Swing,157
64,Days worked,366,3.382514,0.831648,3.000000,4.000000,4.000000,4.000000,RATCHABURI_Banpong,Swing,121
65,Daily orders,366,25.819672,15.498838,13.000000,23.000000,39.000000,65.000000,RATCHABURI_Banpong,Swing,121
66,Daily hours worked,366,5.539396,3.330853,2.867500,5.070556,7.923333,15.253611,RATCHABURI_Banpong,Swing,121
67,Daily Wage,366,1348.068934,799.668048,693.847500,1249.050000,1987.245000,3418.440000,RATCHABURI_Banpong,Swing,121
68,Days worked,231,3.303030,0.934340,3.000000,4.000000,4.000000,4.000000,SAKAEO_Aranyaprathet,Win,81
69,Daily orders,231,25.783550,14.857172,15.000000,24.000000,38.000000,59.000000,SAKAEO_Aranyaprathet,Win,81
70,Daily hours worked,231,5.126287,2.940502,2.934444,4.838889,7.173472,14.468333,SAKAEO_Aranyaprathet,Win,81
71,Daily Wage,231,1621.197013,927.508455,938.640000,1477.800000,2422.800000,3700.170000,SAKAEO_Aranyaprathet,Win,81
72,Days worked,581,3.285714,0.841357,3.000000,4.000000,4.000000,4.000000,SAKONNAKHON,Win,197
73,Daily orders,581,28.769363,14.951479,17.000000,28.000000,41.000000,73.000000,SAKONNAKHON,Win,197
74,Daily hours worked,581,6.073027,3.113366,3.550278,6.034167,8.503889,15.621667,SAKONNAKHON,Win,197
75,Daily Wage,581,1383.044251,722.880928,815.700000,1356.750000,1955.250000,3085.080000,SAKONNAKHON,Win,197
76,Days worked,211,3.218009,0.925747,3.000000,3.000000,4.000000,4.000000,SARABURI_Nongkhae,Win,76
77,Daily orders,211,26.279621,16.629077,13.000000,23.000000,38.000000,69.000000,SARABURI_Nongkhae,Win,76
78,Daily hours worked,211,5.053137,2.851013,2.703333,4.861389,7.150278,11.905000,SARABURI_Nongkhae,Win,76
79,Daily Wage,211,1637.387488,984.532531,803.580000,1502.130000,2357.400000,4431.060000,SARABURI_Nongkhae,Win,76
80,Days worked,108,3.518519,0.825770,3.000000,4.000000,4.000000,4.000000,SARABURI_Phraphutthabat,Win,34
81,Daily orders,108,28.712963,14.584623,19.750000,27.000000,36.250000,81.000000,SARABURI_Phraphutthabat,Win,34
82,Daily hours worked,108,6.226644,3.063504,3.825139,6.171944,8.434514,14.447778,SARABURI_Phraphutthabat,Win,34
83,Daily Wage,108,1681.635000,850.256588,1073.445000,1584.720000,2173.230000,4675.470000,SARABURI_Phraphutthabat,Win,34
84,Days worked,454,3.286344,0.857090,3.000000,4.000000,4.000000,4.000000,SISAKET,Win,156
85,Daily orders,454,25.621145,13.729397,15.000000,25.000000,36.000000,68.000000,SISAKET,Win,156
86,Daily hours worked,454,5.525737,2.928855,3.282431,5.375972,7.782153,14.263889,SISAKET,Win,156
87,Daily Wage,454,1192.328260,641.808001,703.845000,1154.775000,1680.997500,2911.770000,SISAKET,Win,156
88,Days worked,459,3.366013,0.877310,3.000000,4.000000,4.000000,4.000000,SONGKHLA_City,Lose,154
89,Daily orders,459,22.564270,13.049691,12.000000,21.000000,32.000000,60.000000,SONGKHLA_City,Lose,154
90,Daily hours worked,459,4.861547,2.754184,2.604167,4.703611,6.733194,14.663056,SONGKHLA_City,Lose,154
91,Daily Wage,459,1425.656144,814.291085,736.650000,1338.840000,2007.960000,3936.660000,SONGKHLA_City,Lose,154
92,Days worked,231,3.346320,0.875498,3.000000,4.000000,4.000000,4.000000,SURATTHANI_City,Lose,78
93,Daily orders,231,24.632035,13.766014,13.000000,24.000000,36.500000,53.000000,SURATTHANI_City,Lose,78
94,Daily hours worked,231,4.863074,2.750640,2.538472,4.596389,7.050556,11.616667,SURATTHANI_City,Lose,78
95,Daily Wage,231,1352.685195,741.411736,713.700000,1319.520000,2016.240000,3058.320000,SURATTHANI_City,Lose,78
96,Days worked,533,3.356473,0.876028,3.000000,4.000000,4.000000,4.000000,SURIN,Swing,180
97,Daily orders,533,26.292683,15.177171,14.000000,25.000000,36.000000,71.000000,SURIN,Swing,180
98,Daily hours worked,533,5.511652,3.073760,3.135833,5.305000,7.607222,16.999444,SURIN,Swing,180
99,Daily Wage,533,1179.425516,678.151511,658.200000,1095.000000,1635.000000,3476.700000,SURIN,Swing,180
100,Days worked,333,3.300300,0.806543,3.000000,3.000000,4.000000,4.000000,TAK_Maesot,Swing,111
101,Daily orders,333,23.483483,14.139490,11.000000,22.000000,35.000000,59.000000,TAK_Maesot,Swing,111
102,Daily hours worked,333,4.882836,2.823752,2.498333,4.660556,7.187222,13.360000,TAK_Maesot,Swing,111
103,Daily Wage,333,1265.849009,742.152516,611.820000,1225.890000,1878.420000,3152.970000,TAK_Maesot,Swing,111
104,Days worked,228,3.491228,0.842125,3.000000,4.000000,4.000000,4.000000,TRAT,Win,74
105,Daily orders,228,25.337719,16.062241,12.000000,21.500000,38.500000,60.000000,TRAT,Win,74
106,Daily hours worked,228,4.935179,3.124895,2.435069,4.225278,7.397292,14.320556,TRAT,Win,74
107,Daily Wage,228,1369.280395,871.683585,660.952500,1156.920000,2101.980000,3276.810000,TRAT,Win,74
108,Days worked,680,3.388235,0.867941,3.000000,4.000000,4.000000,4.000000,UDONTHANI,Lose,227
109,Daily orders,680,20.416176,13.438959,10.000000,18.000000,30.000000,65.000000,UDONTHANI,Lose,227
110,Daily hours worked,680,4.559500,2.886757,2.155556,4.200972,6.600903,13.013889,UDONTHANI,Lose,227
111,Daily Wage,680,1399.014353,898.695169,655.710000,1247.820000,2029.875000,4091.850000,UDONTHANI,Lose,227
112,Days worked,159,3.238994,0.924074,3.000000,4.000000,4.000000,4.000000,UTTARADIT,Lose,57
113,Daily orders,159,20.540881,13.305915,9.000000,19.000000,29.500000,53.000000,UTTARADIT,Lose,57
114,Daily hours worked,159,3.669832,2.290967,1.590694,3.510556,5.356806,9.235833,UTTARADIT,Lose,57
115,Daily Wage,159,994.694906,646.368063,428.700000,925.200000,1437.000000,2555.400000,UTTARADIT,Lose,57
116,Days worked,236,3.262712,0.839736,3.000000,3.000000,4.000000,4.000000,YASOTHON,Win,81
117,Daily orders,236,22.347458,15.361669,10.750000,20.000000,33.250000,66.000000,YASOTHON,Win,81
118,Daily hours worked,236,4.592166,2.865691,2.311111,4.326111,6.719583,12.205278,YASOTHON,Win,81
119,Daily Wage,236,1198.626102,810.856935,556.335000,1127.145000,1798.785000,3372.150000,YASOTHON,Win,81

In [32]:
region_stats[region_stats['metric'] == 'Daily hours worked'].reset_index().drop(columns=['index']).to_csv('./results/region_daily_hours_worked_stats.csv')

In [33]:
region_stats[region_stats['metric'] == 'Daily orders'].reset_index().drop(columns=['index']).to_csv('./results/region_daily_orders_stats.csv')

In [34]:
region_stats[region_stats['metric'] == 'Days worked'].reset_index().drop(columns=['index']).to_csv('./results/region_days_worked_stats.csv')

In [35]:
region_stats[region_stats['metric'] == 'Daily Wage'].reset_index().drop(columns=['index']).to_csv('./results/region_daily_wage_stats.csv')

In [36]:
region_stats.to_csv('./region_stats_comprehensive.csv')

In [37]:
driver_status_stats = []

for region, group in daily.groupby('Rider Group'):
    for metric, label in [
        ('num_days_worked',    'Days worked'),
        ('num_daily_orders',   'Daily orders'),
        ('total_hours_worked', 'Daily hours worked'),
        ('total_wage', 'Daily Wage')
    ]:
        row = describe_full(group[metric], label)
        row['region'] = region
        driver_status_stats.append(row)

rider_group_drivers = baseline_data_accepted.groupby('Rider Group')['driver_id'].nunique().reset_index()
rider_group_drivers.columns = ['region', 'total_rider_group_drivers']

driver_status_stats = pd.concat(driver_status_stats, ignore_index=True)
driver_status_stats = driver_status_stats.merge(rider_group_drivers, on = 'region', how = 'left')

driver_status_stats

,metric,n,mean,std,min,median,Q3,max,region,total_rider_group_drivers
0,Days worked,4724,3.064352,0.976154,2.000000,3.000000,4.000000,4.000000,Bottom,1824
1,Daily orders,4724,15.354149,11.729813,6.000000,12.000000,22.000000,70.000000,Bottom,1824
2,Daily hours worked,4724,3.331123,2.489742,1.392847,2.746806,4.744931,20.716944,Bottom,1824
3,Daily Wage,4724,914.479052,689.613313,394.290000,742.320000,1267.417500,4466.160000,Bottom,1824
4,Days worked,5773,3.352676,0.830795,3.000000,4.000000,4.000000,4.000000,Mid,1917
5,Daily orders,5773,22.639356,13.414736,12.000000,21.000000,31.000000,70.000000,Mid,1917
6,Daily hours worked,5773,4.738222,2.691974,2.638611,4.484722,6.554444,16.999444,Mid,1917
7,Daily Wage,5773,1311.644031,765.535895,721.800000,1206.180000,1811.880000,5196.450000,Mid,1917
8,Days worked,4809,3.655022,0.634013,3.000000,4.000000,4.000000,4.000000,Top,1390
9,Daily orders,4809,32.244334,14.033015,22.000000,32.000000,43.000000,81.000000,Top,1390
10,Daily hours worked,4809,6.740491,2.856599,4.794722,6.830833,8.725000,15.730833,Top,1390
11,Daily Wage,4809,1854.296039,817.066630,1273.680000,1874.700000,2399.880000,5083.110000,Top,1390

In [38]:
driver_status_stats[driver_status_stats['metric'] == 'Days worked'].reset_index().drop(columns=['index'])

,metric,n,mean,std,min,median,Q3,max,region,total_rider_group_drivers
0,Days worked,4724,3.064352,0.976154,2.0,3.0,4.0,4.0,Bottom,1824
1,Days worked,5773,3.352676,0.830795,3.0,4.0,4.0,4.0,Mid,1917
2,Days worked,4809,3.655022,0.634013,3.0,4.0,4.0,4.0,Top,1390

In [39]:
driver_status_stats.to_csv('./results/driver_status_stats.csv')

In [40]:
region_types_stats = [] 

for (status), group in daily.groupby(['status']):
    for metric, label in [
        ('num_days_worked',    'Days worked'),
        ('num_daily_orders',   'Daily orders'),
        ('total_hours_worked', 'Daily hours worked'),
        ('total_wage', 'Daily Wage')
    ]:
        row = describe_full(group[metric], label)
        row['status'] = status
        region_types_stats.append(row)

status_drivers = baseline_data_accepted.groupby('status')['driver_id'].nunique().reset_index()
status_drivers.columns = ['status', 'total_status_drivers']

region_types_stats = pd.concat(region_types_stats, ignore_index = True)
region_types_stats = region_types_stats.merge(status_drivers, on = 'status', how = 'left')

region_types_stats

,metric,n,mean,std,min,median,Q3,max,status,total_status_drivers
0,Days worked,7850,3.376051,0.859020,3.000000,4.000000,4.000000,4.000000,Lose,2623
1,Daily orders,7850,20.730064,13.888830,9.000000,18.000000,30.000000,77.000000,Lose,2623
2,Daily hours worked,7850,4.554367,2.984595,2.052222,4.180833,6.645000,20.716944,Lose,2623
3,Daily Wage,7850,1369.092099,914.105502,616.500000,1222.200000,1984.395000,5196.450000,Lose,2623
4,Days worked,4012,3.327019,0.862376,3.000000,4.000000,4.000000,4.000000,Swing,1359
5,Daily orders,4012,25.064806,14.651721,13.000000,23.000000,36.000000,71.000000,Swing,1359
6,Daily hours worked,4012,5.152816,2.943566,2.781806,4.955000,7.238819,16.999444,Swing,1359
7,Daily Wage,4012,1319.052914,760.508270,694.800000,1231.380000,1893.862500,4037.280000,Swing,1359
8,Days worked,3444,3.355981,0.846576,3.000000,4.000000,4.000000,4.000000,Win,1150
9,Daily orders,3444,27.584785,15.415235,15.000000,26.000000,40.000000,81.000000,Win,1150
10,Daily hours worked,3444,5.540104,3.006984,3.134236,5.377500,7.734722,15.621667,Win,1150
11,Daily Wage,3444,1385.022186,776.652199,768.120000,1307.700000,1958.280000,4675.470000,Win,1150

In [41]:
region_types_stats[region_types_stats['metric'] == 'Daily Wage'].reset_index().drop(columns=['index'])

,metric,n,mean,std,min,median,Q3,max,status,total_status_drivers
0,Daily Wage,7850,1369.092099,914.105502,616.50,1222.20,1984.3950,5196.45,Lose,2623
1,Daily Wage,4012,1319.052914,760.508270,694.80,1231.38,1893.8625,4037.28,Swing,1359
2,Daily Wage,3444,1385.022186,776.652199,768.12,1307.70,1958.2800,4675.47,Win,1150

In [42]:
region_types_stats.to_csv('./results/region_stats.csv')