In [1]:
import pandas as pd

In [6]:
drivers = pd.read_csv('../rider_log.csv')

In [9]:
#make the first row column names 
drivers.columns = drivers.iloc[0]
drivers = drivers[1:]

In [4]:
drivers.head(2)

,Start Date,End Date,Rider List,Rider Group,Get Incentive,Incentive,Region,Cluster,Incentive Sequence,Column for Vertical Analysis,Column for Horizontal Rider Behavior,"Is Same Rider Between 1,2 / 3,4",Column for Vertical Rider Behavior
1,2025-07-10,2025-07-13,LMDX7OS7Y,Top,TRUE,Daily Productivity,SARABURI_Nongkhae,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity
2,2025-07-10,2025-07-13,LMDN1M7RY,Top,TRUE,Streak,NAKHONSAWAN,EXP - Lose,Streak: First Recovery Week,Recovery Week,-,-,Recovery Week to Streak

In [5]:
drivers['date'] = pd.to_datetime(drivers['Start Date']).dt.date

In [6]:
drivers['date'] = drivers['date'].astype(str)

In [7]:
drivers['date'].unique()

array(['2025-07-10', '2025-07-14', '2025-07-21', '2025-08-11',
       '2025-08-16', '2025-08-23'], dtype=object)

In [8]:
drivers

,Start Date,End Date,Rider List,Rider Group,Get Incentive,Incentive,Region,Cluster,Incentive Sequence,Column for Vertical Analysis,Column for Horizontal Rider Behavior,"Is Same Rider Between 1,2 / 3,4",Column for Vertical Rider Behavior,date
1,2025-07-10,2025-07-13,LMDX7OS7Y,Top,TRUE,Daily Productivity,SARABURI_Nongkhae,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
2,2025-07-10,2025-07-13,LMDN1M7RY,Top,TRUE,Streak,NAKHONSAWAN,EXP - Lose,Streak: First Recovery Week,Recovery Week,-,-,Recovery Week to Streak,2025-07-10
3,2025-07-10,2025-07-13,LMD456V1N,Top,TRUE,No Incentive,RATCHABURI_Banpong,EXP - Swing,No Incentive: First Recovery Week,Recovery Week,-,-,Recovery Week to No Incentive,2025-07-10
4,2025-07-10,2025-07-13,LMDR2EJ9V,Top,TRUE,Daily Productivity,SISAKET,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
5,2025-07-10,2025-07-13,LMD7MRVM6,Top,TRUE,Active Bonus,HAT YAI,EXP - Lose,Active Bonus: First Recovery Week,Recovery Week,-,-,Recovery Week to Active Bonus,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39462,2025-08-23,2025-08-29,LMDAGOC26,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39463,2025-08-23,2025-08-29,LMDKQCYD7,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39464,2025-08-23,2025-08-29,LMDJY06L6,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39465,2025-08-23,2025-08-29,LMDS0VUDZ,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39466,2025-08-23,2025-08-29,LMDB7S34J,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23

In [11]:
#change column names for easy merging
drivers = drivers.rename(columns={'Rider List': 'driver_id'})
drivers = drivers.rename(columns={'Region': 'region'})

In [10]:
data = pd.read_csv('../mainexperiment/weekly/all-0710-0713.csv')

In [11]:
data.columns

Index(['date', 'region', 'zone', 'driver_id', 'rider_level',
       'most_freq_district', 'phone', 'driver_tier', 'dedicated_zones',
       'total_online_hour', 'peak_online_hour', 'offpeak_online_hour',
       'total_assign_hour', 'active_day', 'auto_assigned',
       'auto_assigned_food', 'auto_assigned_mart', 'auto_assigned_messenger',
       'auto_assigned_bike', 'auto_assigned_accepted',
       'auto_assigned_accepted_food', 'auto_assigned_accepted_mart',
       'auto_assigned_accepted_messenger', 'auto_assigned_accepted_bike',
       'completed', 'completed_peak', 'completed_offpeak', 'completed_food',
       'completed_mart', 'completed_messenger', 'completed_bike',
       'cancelled_free', 'cancelled_free_food', 'cancelled_free_mart',
       'cancelled_free_messenger', 'cancelled_free_bike', 'cancelled_not_free',
       'cancelled_not_free_food', 'cancelled_not_free_mart',
       'cancelled_not_free_messenger', 'cancelled_not_free_bike',
       'driver_wage_food', 'driver_wage_mart', 'driver_wage_msg',
       'driver_wage_bike', 'DELIVERY_FEE_DYNAMIC_ON_TOP',
       'DELIVERY_FEE_DYNAMIC_ON_TOP_food', 'DELIVERY_FEE_DYNAMIC_ON_TOP_mart',
       'DELIVERY_FEE_DYNAMIC_ON_TOP_msg', 'DELIVERY_FEE_DYNAMIC_ON_TOP_bike',
       'CONVERT_COIN_TO_CASH_'food','mart','messenger','bike'',
       'guarantee_'food','mart','messenger','bike'',
       'active_bonus_'food','mart','messenger','bike'',
       'streak_'food','mart','messenger','bike'',
       'period_'food','mart','messenger','bike'',
       'daily_'food','mart','messenger','bike'',
       'own_fleet_wage_'food','mart','messenger','bike'',
       'own_fleet_incentive_'food','mart','messenger','bike'',
       'CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike'',
       'main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'',
       'tier_main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'',
       'tier_productivity_incentive_'food','mart','messenger','bike'',
       'tier_productivity_incentive_peak_'food','mart','messenger','bike'',
       'tier_productivity_incentive_offpeak_'food','mart','messenger','bike'',
       'peak_ratio', 'offpeak_ratio', 'tier_productivity_incentive',
       'active_driver', 'active_driver_peak', 'active_driver_offpeak',
       'aa_completed', 'zone_online_day', 'region_online_day',
       'region_active_day', 'total_income', 'extra_non_wage_cost',
       'peak_extra_non_wage_cost', 'offpeak_extra_non_wage_cost'],
      dtype='object')

In [12]:
data.head(5)

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost
0,2025-07-10,NAKHONSAWAN,N,LMDF8Y0DZ,6,Mueang Nakhon Sawan,902367177,GOLD,NaN,5.5237,...,1,1,12,1.0,1.0,1,329.80,0.0,0.0,0.0
1,2025-07-12,LAMPANG,N,LMDKXH3N0,8,Mueang Lampang,992713856,LEGEND,NaN,10.2829,...,1,1,0,1.0,1.0,1,1145.00,0.0,0.0,0.0
2,2025-07-10,SURIN,N,LMDGAIHHI,7,Mueang Surin,972357064,LEGEND,NaN,10.1746,...,1,1,0,1.0,1.0,1,982.60,0.0,0.0,0.0
3,2025-07-10,SONGKHLA_City,N,LMDFQK4XV,8,Mueang Songkhla,928941259,LEGEND,NaN,9.5162,...,1,1,0,1.0,1.0,1,968.44,0.0,0.0,0.0
4,2025-07-11,SARABURI_Phraphutthabat,N,LMDXO0LPC,3,Phra Phutthabat,882324555,BRONZE,NaN,1.3522,...,1,0,5,1.0,1.0,1,125.02,0.0,0.0,NaN

In [4]:
from pathlib import Path
import os

In [ ]:
# get all CSV files
csv_files = sorted(Path('../mainexperiment/weekly/weather_merged').glob('*.csv'))

# display all files
for i, file in enumerate(csv_files, 1):
    print(f"{i}. {file.name}")

# prepare drivers dataframe 
drivers['Start Date'] = pd.to_datetime(drivers['Start Date']).dt.date
drivers['End Date'] = pd.to_datetime(drivers['End Date']).dt.date

# process each file
for i, csv_file in enumerate(csv_files, 1):
    print(f"\n[{i}/{len(csv_files)}] Processing: {csv_file.name}")
    print("-" * 80)
    
    # read the CSV file
    df = pd.read_csv(csv_file)
    df['date'] = pd.to_datetime(df['date']).dt.date
    
    # merge based on date range condition
    df_merged = df.merge(
        drivers,
        on=['region', 'driver_id'],
        how='left'
    )
    
    # Filter to keep only rows where date falls within the range
    df_merged = df_merged[
        (df_merged['date'] >= df_merged['Start Date']) & 
        (df_merged['date'] <= df_merged['End Date'])
    ].copy()
        
    print(f"Rows after filtering by date range: {len(df_merged)}")
    
    output_name = f"tiers_{csv_file.name}"
    output_path = os.path.join('../mainexperiment/weekly/tier_merged', output_name)
    
    # Save to CSV
    df_merged.to_csv(output_path, index=False)

1. merged_all-0710-0713.csv
2. merged_all-0714-0720.csv
3. merged_all-0721-0727.csv
4. merged_all-0728-0810.csv
5. merged_all-0811-0815.csv
6. merged_all-0816-0822.csv
7. merged_all-0823-0829.csv

[1/7] Processing: merged_all-0710-0713.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 15566

[2/7] Processing: merged_all-0714-0720.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 29301

[3/7] Processing: merged_all-0721-0727.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 29583

[4/7] Processing: merged_all-0728-0810.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 20559

[5/7] Processing: merged_all-0811-0815.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 20559

[6/7] Processing: merged_all-0816-0822.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 30336

[7/7] Processing: merged_all-0823-0829.csv
--------------------------------------------------------------------------------
Rows after filtering by date range: 30149

In [15]:
merged = pd.read_csv('../mainexperiment/weekly/tier_merged/tiers_merged_all-0710-0713.csv')
merged.head(5)

/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_72937/3046636061.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  merged = pd.read_csv('../mainexperiment/weekly/tier_merged/tiers_merged_all-0710-0713.csv')

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive
0,2025-07-11,CHANTHABURI,N,LMD07LE7W,7,Mueang Chanthaburi,923394134.0,MASTER,NaN,0.7634,...,0.0,NaN,0.0,CHANTHABURI,0.00,no-rain,Top,2025-07-10,2025-07-13,Guarantee
1,2025-07-12,CHANTHABURI,N,LMD07LE7W,7,Mueang Chanthaburi,923394134.0,MASTER,NaN,1.6204,...,0.0,0.0,0.0,CHANTHABURI,0.00,no-rain,Top,2025-07-10,2025-07-13,Guarantee
2,2025-07-10,CHANTHABURI,N,LMD07LE7W,8,Mueang Chanthaburi,923394134.0,MASTER,NaN,6.9282,...,0.0,0.0,0.0,CHANTHABURI,0.37,Light,Top,2025-07-10,2025-07-13,Guarantee
3,2025-07-11,CHANTHABURI,N,LMD0F7D6F,6,Mueang Chanthaburi,634519461.0,GOLD,NaN,7.5890,...,0.0,0.0,0.0,CHANTHABURI,0.00,no-rain,Mid,2025-07-10,2025-07-13,Guarantee
4,2025-07-13,CHANTHABURI,N,LMD0N5L6G,0,Mueang Chanthaburi,946537473.0,SILVER,NaN,1.9178,...,0.0,0.0,0.0,CHANTHABURI,0.00,no-rain,Bottom,2025-07-10,2025-07-13,Guarantee

In [16]:
merged['Rider Group'].unique()

array(['Top', 'Mid', 'Bottom'], dtype=object)

In [17]:
drivers

,Start Date,End Date,driver_id,Rider Group,Get Incentive,Incentive,region,Cluster,Incentive Sequence,Column for Vertical Analysis,Column for Horizontal Rider Behavior,"Is Same Rider Between 1,2 / 3,4",Column for Vertical Rider Behavior,date
1,2025-07-10,2025-07-13,LMDX7OS7Y,Top,TRUE,Daily Productivity,SARABURI_Nongkhae,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
2,2025-07-10,2025-07-13,LMDN1M7RY,Top,TRUE,Streak,NAKHONSAWAN,EXP - Lose,Streak: First Recovery Week,Recovery Week,-,-,Recovery Week to Streak,2025-07-10
3,2025-07-10,2025-07-13,LMD456V1N,Top,TRUE,No Incentive,RATCHABURI_Banpong,EXP - Swing,No Incentive: First Recovery Week,Recovery Week,-,-,Recovery Week to No Incentive,2025-07-10
4,2025-07-10,2025-07-13,LMDR2EJ9V,Top,TRUE,Daily Productivity,SISAKET,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
5,2025-07-10,2025-07-13,LMD7MRVM6,Top,TRUE,Active Bonus,HAT YAI,EXP - Lose,Active Bonus: First Recovery Week,Recovery Week,-,-,Recovery Week to Active Bonus,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39462,2025-08-23,2025-08-29,LMDAGOC26,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39463,2025-08-23,2025-08-29,LMDKQCYD7,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39464,2025-08-23,2025-08-29,LMDJY06L6,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39465,2025-08-23,2025-08-29,LMDS0VUDZ,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23
39466,2025-08-23,2025-08-29,LMDB7S34J,Bottom,TRUE,Guarantee,YASOTHON,EXP - Win,Guarantee: Fourth Week,-,Streak to Guarantee,FALSE,-,2025-08-23

In [18]:
drivers.head(5)

,Start Date,End Date,driver_id,Rider Group,Get Incentive,Incentive,region,Cluster,Incentive Sequence,Column for Vertical Analysis,Column for Horizontal Rider Behavior,"Is Same Rider Between 1,2 / 3,4",Column for Vertical Rider Behavior,date
1,2025-07-10,2025-07-13,LMDX7OS7Y,Top,TRUE,Daily Productivity,SARABURI_Nongkhae,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
2,2025-07-10,2025-07-13,LMDN1M7RY,Top,TRUE,Streak,NAKHONSAWAN,EXP - Lose,Streak: First Recovery Week,Recovery Week,-,-,Recovery Week to Streak,2025-07-10
3,2025-07-10,2025-07-13,LMD456V1N,Top,TRUE,No Incentive,RATCHABURI_Banpong,EXP - Swing,No Incentive: First Recovery Week,Recovery Week,-,-,Recovery Week to No Incentive,2025-07-10
4,2025-07-10,2025-07-13,LMDR2EJ9V,Top,TRUE,Daily Productivity,SISAKET,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity,2025-07-10
5,2025-07-10,2025-07-13,LMD7MRVM6,Top,TRUE,Active Bonus,HAT YAI,EXP - Lose,Active Bonus: First Recovery Week,Recovery Week,-,-,Recovery Week to Active Bonus,2025-07-10

In [ ]:
# get all CSV files
csv_files = sorted(Path('../orderlevel_updated/weather_merged').glob('*.csv'))

# display all files
for i, file in enumerate(csv_files, 1):
    print(f"{i}. {file.name}")
    
# Process each file
for i, csv_file in enumerate(csv_files, 1):
    print(f"\n[{i}/{len(csv_files)}] Processing: {csv_file.name}")
    print("-" * 80)
 
    #skip because no tier data for these ranges
    if csv_file.name == 'merged_0802-0806.csv' or csv_file.name == 'merged_0807-0811.csv':
        continue 
    
    df = pd.read_csv(csv_file)
    df['assign_created_at'] = pd.to_datetime(df['assign_created_at'])
    df['date'] = df['assign_created_at'].dt.date

    #exploring why we are missing some order data -> found that there exists regions in orders df that are not in 30 cities list
    # in_df_not_drivers = set(df['region']) - set(drivers['region'])
    # in_drivers_not_df = set(drivers['region']) - set(df['region'])

    # print(f"In df but not drivers: {len(in_df_not_drivers)}")
    # print(f"In drivers but not df: {len(in_drivers_not_df)}")

    df_merged = pd.merge(df, drivers[['Rider Group', 'region', 'driver_id', 'Start Date', 'End Date', 'Incentive']],
                on=['driver_id', 'region'],
                how='left')
    
    no_match = df_merged['Start Date'].isna()
    df_merged['date'] = pd.to_datetime(df_merged['date'])

    # Filter to keep only rows where date falls within the range
    in_range = (
        (df_merged['date'] >= pd.to_datetime(df_merged['Start Date'])) & 
        (df_merged['date'] <= pd.to_datetime(df_merged['End Date']))
    )
    
    df_merged = df_merged[in_range | no_match].copy() 

    output_name = f"tiers_{csv_file.name}"
    output_path = os.path.join('../orderlevel_updated/tier_merged', output_name)
    
    # save to CSV
    df_merged.to_csv(output_path, index=False)

1. merged_0710-0713.csv
2. merged_0714-0716.csv
3. merged_0717-0720.csv
4. merged_0721-0725.csv
5. merged_0726-0727.csv
6. merged_0728-0801.csv
7. merged_0802-0806.csv
8. merged_0807-0810.csv
9. merged_0811-0815.csv
10. merged_0816-0820.csv
11. merged_0821-0825.csv
12. merged_0826-0829.csv

[1/12] Processing: merged_0710-0713.csv
--------------------------------------------------------------------------------
In df but not drivers: 18
In drivers but not df: 0

[2/12] Processing: merged_0714-0716.csv
--------------------------------------------------------------------------------
In df but not drivers: 18
In drivers but not df: 0

[3/12] Processing: merged_0717-0720.csv
--------------------------------------------------------------------------------
In df but not drivers: 19
In drivers but not df: 0

[4/12] Processing: merged_0721-0725.csv
--------------------------------------------------------------------------------
In df but not drivers: 16
In drivers but not df: 0

[5/12] Processing: merged_0726-0727.csv
--------------------------------------------------------------------------------
In df but not drivers: 15
In drivers but not df: 0

[6/12] Processing: merged_0728-0801.csv
--------------------------------------------------------------------------------
In df but not drivers: 19
In drivers but not df: 0

[7/12] Processing: merged_0802-0806.csv
--------------------------------------------------------------------------------

[8/12] Processing: merged_0807-0810.csv
--------------------------------------------------------------------------------
In df but not drivers: 12
In drivers but not df: 0

[9/12] Processing: merged_0811-0815.csv
--------------------------------------------------------------------------------
In df but not drivers: 14
In drivers but not df: 0

[10/12] Processing: merged_0816-0820.csv
--------------------------------------------------------------------------------
In df but not drivers: 12
In drivers but not df: 0

[11/12] Processing: merged_0821-0825.csv
--------------------------------------------------------------------------------
In df but not drivers: 13
In drivers but not df: 0

[12/12] Processing: merged_0826-0829.csv
--------------------------------------------------------------------------------
In df but not drivers: 12
In drivers but not df: 0

In [27]:
data_806 = pd.read_csv('../orderlevel_updated/tier_merged/tiers_merged_0802-0806.csv')

In [28]:
data_806.columns

Index(['region', 'driver_id', 'assign_created_at', 'restaurant_name',
       'restaurant_category', 'order_id', 'is_driver_accept', 'wage',
       'on_top_fare', 'basket_size', 'drop_off_distance',
       'distance_rider_to_restaurant', 'placed_to_match_second',
       'rider_matched_to_arrived_restaurant_second',
       'rider_waiting_time_in_restaurant_second',
       'delivery_time_to_user_second', 'total_user_waiting_time_second',
       'order_status', 'date', 'region::multi-filter', 'avg_rain',
       'Rain_Level', 'Rider Group', 'Start Date', 'End Date', 'Incentive'],
      dtype='object')

In [31]:
data_806.drop(['Incentive'], axis=1)

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date
0,SURIN,LMD00BZBZ,2025-08-02 07:57:20.819,มุมส้มตำ (Som Tum Corner),North East,LMF-250802-510164657,True,17.0,3.0,90.0,...,501,1264,COMPLETED,2025-08-02,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
1,SURIN,LMD00BZBZ,2025-08-02 07:57:20.819,มุมส้มตำ (Som Tum Corner),North East,LMF-250802-510164657,True,17.0,3.0,90.0,...,501,1264,COMPLETED,2025-08-02,SURIN,0.0,no-rain,Mid,2025-07-14,2025-07-20
2,SURIN,LMD00BZBZ,2025-08-02 07:57:20.819,มุมส้มตำ (Som Tum Corner),North East,LMF-250802-510164657,True,17.0,3.0,90.0,...,501,1264,COMPLETED,2025-08-02,SURIN,0.0,no-rain,Mid,2025-07-21,2025-07-27
3,SURIN,LMD00BZBZ,2025-08-02 07:57:20.819,มุมส้มตำ (Som Tum Corner),North East,LMF-250802-510164657,True,17.0,3.0,90.0,...,501,1264,COMPLETED,2025-08-02,SURIN,0.0,no-rain,Mid,2025-08-11,2025-08-15
4,SURIN,LMD00BZBZ,2025-08-02 07:57:20.819,มุมส้มตำ (Som Tum Corner),North East,LMF-250802-510164657,True,17.0,3.0,90.0,...,501,1264,COMPLETED,2025-08-02,SURIN,0.0,no-rain,Mid,2025-08-16,2025-08-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3142115,PHAYAO,LMDZZVYF8,2025-08-06 19:43:40.118,กินลำ/ยำแซ่บ (Kin Lam/Yum Zab),À La Carte,LMF-250806-290049347,True,15.0,0.0,205.0,...,278,1567,COMPLETED,2025-08-06,PHAYAO,0.0,no-rain,Mid,2025-08-23,2025-08-29
3142116,PHAYAO,LMDZZVYF8,2025-08-06 19:53:01.488,ถุงเงิน ถุงทอง อาหารตามสั่ง ส้มตำ ยำ ข้าวซอยไก...,À La Carte,LMF-250806-630939610,True,15.0,0.0,138.0,...,316,1604,COMPLETED,2025-08-06,PHAYAO,0.0,no-rain,Mid,2025-07-21,2025-07-27
3142117,PHAYAO,LMDZZVYF8,2025-08-06 19:53:01.488,ถุงเงิน ถุงทอง อาหารตามสั่ง ส้มตำ ยำ ข้าวซอยไก...,À La Carte,LMF-250806-630939610,True,15.0,0.0,138.0,...,316,1604,COMPLETED,2025-08-06,PHAYAO,0.0,no-rain,Mid,2025-08-11,2025-08-15
3142118,PHAYAO,LMDZZVYF8,2025-08-06 19:53:01.488,ถุงเงิน ถุงทอง อาหารตามสั่ง ส้มตำ ยำ ข้าวซอยไก...,À La Carte,LMF-250806-630939610,True,15.0,0.0,138.0,...,316,1604,COMPLETED,2025-08-06,PHAYAO,0.0,no-rain,Mid,2025-08-16,2025-08-22
3142119,PHAYAO,LMDZZVYF8,2025-08-06 19:53:01.488,ถุงเงิน ถุงทอง อาหารตามสั่ง ส้มตำ ยำ ข้าวซอยไก...,À La Carte,LMF-250806-630939610,True,15.0,0.0,138.0,...,316,1604,COMPLETED,2025-08-06,PHAYAO,0.0,no-rain,Mid,2025-08-23,2025-08-29

In [34]:
data_806.to_csv('../orderlevel_updated/tier_merged/tiers_merged_0802-0806.csv')

In [33]:
data_807 = pd.read_csv('../orderlevel_updated/tier_merged/tiers_merged_0807-0810.csv')

In [35]:
data_807.drop(['Incentive'], axis=1)

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date
0,SURIN,LMD00BZBZ,2025-08-07 07:54:48.075,Follow the sun Follow the sun,Café/Coffee Shop,LMF-250807-045601057,True,11.00,3.0,90.0,...,41,1351,COMPLETED,2025-08-07,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
1,SURIN,LMD00BZBZ,2025-08-07 07:54:48.075,Follow the sun Follow the sun,Café/Coffee Shop,LMF-250807-045601057,True,11.00,3.0,90.0,...,41,1351,COMPLETED,2025-08-07,SURIN,0.0,no-rain,Mid,2025-07-14,2025-07-20
2,SURIN,LMD00BZBZ,2025-08-07 07:54:48.075,Follow the sun Follow the sun,Café/Coffee Shop,LMF-250807-045601057,True,11.00,3.0,90.0,...,41,1351,COMPLETED,2025-08-07,SURIN,0.0,no-rain,Mid,2025-07-21,2025-07-27
3,SURIN,LMD00BZBZ,2025-08-07 07:54:48.075,Follow the sun Follow the sun,Café/Coffee Shop,LMF-250807-045601057,True,11.00,3.0,90.0,...,41,1351,COMPLETED,2025-08-07,SURIN,0.0,no-rain,Mid,2025-08-11,2025-08-15
4,SURIN,LMD00BZBZ,2025-08-07 07:54:48.075,Follow the sun Follow the sun,Café/Coffee Shop,LMF-250807-045601057,True,11.00,3.0,90.0,...,41,1351,COMPLETED,2025-08-07,SURIN,0.0,no-rain,Mid,2025-08-16,2025-08-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2400369,PHAYAO,LMDZZVYF8,2025-08-10 13:20:00.438,hind cafe,Café/Coffee Shop,LMF-250810-076439049,True,13.46,0.0,250.8,...,235,2160,COMPLETED,2025-08-10,PHAYAO,0.0,no-rain,Mid,2025-08-23,2025-08-29
2400370,PHAYAO,LMDZZVYF8,2025-08-10 13:29:05.012,ร้านลาบป้านวล (Aunt Nuan's Lab Restaurant),À La Carte,LMF-250810-102602794,True,13.45,0.0,70.0,...,543,1156,COMPLETED,2025-08-10,PHAYAO,0.0,no-rain,Mid,2025-07-21,2025-07-27
2400371,PHAYAO,LMDZZVYF8,2025-08-10 13:29:05.012,ร้านลาบป้านวล (Aunt Nuan's Lab Restaurant),À La Carte,LMF-250810-102602794,True,13.45,0.0,70.0,...,543,1156,COMPLETED,2025-08-10,PHAYAO,0.0,no-rain,Mid,2025-08-11,2025-08-15
2400372,PHAYAO,LMDZZVYF8,2025-08-10 13:29:05.012,ร้านลาบป้านวล (Aunt Nuan's Lab Restaurant),À La Carte,LMF-250810-102602794,True,13.45,0.0,70.0,...,543,1156,COMPLETED,2025-08-10,PHAYAO,0.0,no-rain,Mid,2025-08-16,2025-08-22
2400373,PHAYAO,LMDZZVYF8,2025-08-10 13:29:05.012,ร้านลาบป้านวล (Aunt Nuan's Lab Restaurant),À La Carte,LMF-250810-102602794,True,13.45,0.0,70.0,...,543,1156,COMPLETED,2025-08-10,PHAYAO,0.0,no-rain,Mid,2025-08-23,2025-08-29

In [36]:
data_807.to_csv('../orderlevel_updated/tier_merged/tiers_merged_0807-0811.csv')

In [7]:
#don't have data for this week -> manually merge in No Incentive and set driver to tier to whatever was teh driver tier before 
tiers_merged = pd.read_csv('../mainexperiment/weekly/weather_merged/merged_all-0728-0810.csv')

In [8]:
tiers_merged.head()

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'",region::multi-filter,avg_rain,Rain_Level
0,2025-08-08,UDONTHANI,N,LMDNMIMRD,6,Mueang Udon Thani,930893934,GOLD,NaN,2.6113,...,1.0,1,93.480000,0.0,NaN,0.0,0.0,UDONTHANI,0.00,no-rain
1,2025-08-10,KHONKAEN,N,LMDB0YYEI,9,Mueang Khon Kaen,948166099,LEGEND,NaN,11.4862,...,1.0,1,2104.560000,0.0,0.0,0.0,0.0,KHONKAEN,0.42,Light
2,2025-07-30,KRABI,N,LMDAVGUS0,7,Mueang Krabi,633579013,BRONZE,NaN,4.8034,...,1.0,1,378.800000,0.0,0.0,0.0,0.0,KRABI,0.00,no-rain
3,2025-08-04,TAK_Maesot,N,LMD82SCTG,4,Mae Sot,619208768,GOLD,NaN,7.4731,...,1.0,1,330.429159,0.0,0.0,0.0,0.0,TAK_Maesot,0.00,no-rain
4,2025-08-03,KHONKAEN,N,LMD7CHGCX,0,Mueang Khon Kaen,993924470,BRONZE,NaN,1.0846,...,1.0,1,76.960000,0.0,NaN,0.0,0.0,KHONKAEN,0.00,no-rain

In [11]:
tiers_merged['date'].max()

'2025-08-15'

In [ ]:

DATA_DIR        = "../mainexperiment/weekly/tier_merged"             # folder containing your CSV files
W3_PATTERN      = "*0721-0727*"   # filename pattern for W3
W4_PATTERN      = "*0728-0810*"   # filename pattern for W4
NO_INCENTIVE    = "No Incentive"  # value to set in Incentive column

DRIVER_COL      = "driver_id"
TIER_COL        = "driver_tier"
INCENTIVE_COL   = "Incentive"

In [44]:
"""
Fix W4 (0728_0810):
  1. Overwrite driver_tier with each driver's tier from W3 (0721_0727)
  2. Set all Incentive values to 'No Incentive'
  3. Overwrite the original W4 file
"""

import os
import glob
import pandas as pd

# ═══════════════════════════════════════════════════
# CONFIG
# ═══════════════════════════════════════════════════

DATA_DIR        = "../mainexperiment/weekly/tier_merged"             # folder containing your CSV files
W3_PATTERN      = "*0721-0727*"   # filename pattern for W3
W4_PATTERN      = "*0728-0810*"   # filename pattern for W4
NO_INCENTIVE    = "No Incentive"  # value to set in Incentive column

DRIVER_COL      = "driver_id"
TIER_COL        = "Rider Group"
INCENTIVE_COL   = "Incentive"

# ═══════════════════════════════════════════════════
# LOAD
# ═══════════════════════════════════════════════════

def find_file(data_dir, pattern):
    matches = glob.glob(os.path.join(data_dir, pattern))
    if not matches:
        raise FileNotFoundError(f"No file found matching '{pattern}' in {data_dir}")
    if len(matches) > 1:
        raise ValueError(f"Multiple files matched '{pattern}': {matches}")
    return matches[0]

w3_path = find_file(DATA_DIR, W3_PATTERN)
w4_path = find_file(DATA_DIR, W4_PATTERN)

print(f"W3 file: {w3_path}")
print(f"W4 file: {w4_path}")

w3 = pd.read_csv(w3_path, low_memory=False)
w4 = pd.read_csv(w4_path, low_memory=False)

print(f"\nW3 rows: {len(w3):,}")
print(f"W4 rows: {len(w4):,}")

# ═══════════════════════════════════════════════════
# STEP 1: Build driver → tier lookup from W3
# ═══════════════════════════════════════════════════

tier_lookup = (
    w3.dropna(subset=[TIER_COL])
    .groupby(DRIVER_COL)[TIER_COL]
    .agg(lambda x: x.mode().iloc[0])
    .to_dict()
)

print(f"\nDrivers in W3 tier lookup: {len(tier_lookup):,}")

# ═══════════════════════════════════════════════════
# STEP 2: Overwrite driver_tier in W4
# ═══════════════════════════════════════════════════

new_tiers = w4[DRIVER_COL].map(tier_lookup)
n_matched  = new_tiers.notna().sum()
n_missing  = new_tiers.isna().sum()

w4[TIER_COL] = new_tiers  # create column from scratch using W3 lookup
w4['Start Date'] = '2025-07-28'
w4['End Date'] = '2025-08-10'

no_match = w4['Start Date'].isna()
in_range = (
        (w4['date'] >= pd.to_datetime(w4['Start Date'])) & 
        (w4['date'] <= pd.to_datetime(w4['End Date']))
    )
    
w4 = w4[in_range | no_match].copy() 


print(f"driver_tier mapped from W3: {n_matched:,}")
print(f"driver_tier not found in W3 (will be NaN): {n_missing:,}")

# ═══════════════════════════════════════════════════
# STEP 3: Set all Incentive = 'No Incentive'
# ═══════════════════════════════════════════════════

w4.loc[:, INCENTIVE_COL] = NO_INCENTIVE
print(f"\nIncentive set to '{NO_INCENTIVE}' for all {len(w4):,} rows")

# ═══════════════════════════════════════════════════
# SAVE — overwrite original W4 file
# ═══════════════════════════════════════════════════

w4.to_csv(w4_path, index=False)
print(f"\n✓ Saved (overwritten): {w4_path}")

W3 file: ../mainexperiment/weekly/tier_merged/tiers_merged_all-0721-0727.csv
W4 file: ../mainexperiment/weekly/tier_merged/tiers_merged_all-0728-0810.csv

W3 rows: 29,583
W4 rows: 85,816

Drivers in W3 tier lookup: 5,830
driver_tier mapped from W3: 72,891
driver_tier not found in W3 (will be NaN): 12,925

Incentive set to 'No Incentive' for all 63,437 rows

✓ Saved (overwritten): ../mainexperiment/weekly/tier_merged/tiers_merged_all-0728-0810.csv

In [46]:
saved = pd.read_csv('../mainexperiment/weekly/tier_merged/tiers_merged_all-0728-0810.csv')
saved

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,peak_online_hour,offpeak_online_hour,total_assign_hour,active_day,auto_assigned,auto_assigned_food,auto_assigned_mart,auto_assigned_messenger,auto_assigned_bike,auto_assigned_accepted,auto_assigned_accepted_food,auto_assigned_accepted_mart,auto_assigned_accepted_messenger,auto_assigned_accepted_bike,completed,completed_peak,completed_offpeak,completed_food,completed_mart,completed_messenger,completed_bike,cancelled_free,cancelled_free_food,cancelled_free_mart,cancelled_free_messenger,cancelled_free_bike,cancelled_not_free,cancelled_not_free_food,cancelled_not_free_mart,cancelled_not_free_messenger,cancelled_not_free_bike,driver_wage_food,driver_wage_mart,driver_wage_msg,driver_wage_bike,DELIVERY_FEE_DYNAMIC_ON_TOP,DELIVERY_FEE_DYNAMIC_ON_TOP_food,DELIVERY_FEE_DYNAMIC_ON_TOP_mart,DELIVERY_FEE_DYNAMIC_ON_TOP_msg,DELIVERY_FEE_DYNAMIC_ON_TOP_bike,"CONVERT_COIN_TO_CASH_'food','mart','messenger','bike'","guarantee_'food','mart','messenger','bike'","active_bonus_'food','mart','messenger','bike'","streak_'food','mart','messenger','bike'","period_'food','mart','messenger','bike'","daily_'food','mart','messenger','bike'","own_fleet_wage_'food','mart','messenger','bike'","own_fleet_incentive_'food','mart','messenger','bike'","CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike'","main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'",tier_productivity_incentive,active_driver,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'",region::multi-filter,avg_rain,Rain_Level,Incentive,Rider Group,Start Date,End Date
0,2025-08-08,UDONTHANI,N,LMDNMIMRD,6,Mueang Udon Thani,930893934,GOLD,NaN,2.6113,NaN,2.6113,1.727172,1,5,5,0,0,0,4,4,0,0,0,4,0,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,93.48,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,0,1.0,1.0,1,93.480000,0.0,NaN,0.0,0.0,UDONTHANI,0.00,no-rain,No Incentive,Bottom,2025-07-28,2025-08-10
1,2025-08-10,KHONKAEN,N,LMDB0YYEI,9,Mueang Khon Kaen,948166099,LEGEND,NaN,11.4862,4.2080,7.2782,6.965337,1,56,56,0,0,0,37,37,0,0,0,37,21,16,37,0,0,0,0,0,0,0,0,0,0,0,0,0,794.56,NaN,NaN,NaN,50.0,50.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1260.0,0.0,NaN,1,1,1,0,1.0,1.0,1,2104.560000,0.0,0.0,0.0,0.0,KHONKAEN,0.42,Light,No Incentive,Top,2025-07-28,2025-08-10
2,2025-07-30,KRABI,N,LMDAVGUS0,7,Mueang Krabi,633579013,BRONZE,NaN,4.8034,3.0581,1.7453,3.311744,1,17,17,0,0,0,17,17,0,0,0,17,13,4,17,0,0,0,0,0,0,0,0,0,0,0,0,0,306.80,NaN,NaN,NaN,72.0,72.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,378.800000,0.0,0.0,0.0,0.0,KRABI,0.00,no-rain,No Incentive,Mid,2025-07-28,2025-08-10
3,2025-08-04,TAK_Maesot,N,LMD82SCTG,4,Mae Sot,619208768,SILVER,NaN,7.4731,3.5915,3.8816,3.598495,1,19,18,0,1,0,16,15,0,1,0,16,9,7,15,0,1,0,0,0,0,0,0,0,0,0,0,0,241.56,NaN,49.869159,NaN,39.0,39.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,330.429159,0.0,0.0,0.0,0.0,TAK_Maesot,0.00,no-rain,No Incentive,Bottom,2025-07-28,2025-08-10
4,2025-08-03,KHONKAEN,N,LMD7CHGCX,0,Mueang Khon Kaen,993924470,BRONZE,NaN,1.0846,NaN,1.0846,0.822046,1,3,3,0,0,0,3,3,0,0,0,3,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,76.96,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,0,1.0,1.0,1,76.960000,0.0,NaN,0.0,0.0,KHONKAEN,0.00,no-rain,No Incentive,NaN,2025-07-28,2025-08-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63432,2025-08-09,KRABI,N,LMDD3XVYC,7,Mueang Krabi,634734761,GOLD,NaN,6.8277,2.7283,4.0994,5.571635,1,26,25,1,0,0,20,19,1,0,0,20,10,10,19,1,0,0,0,0,0,0,0,0,0,0,0,0,375.00,35.20,NaN,NaN,96.0,96.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,506.200000,0.0,0.0,0.0,0.0,KRABI,0.00,no-rain,No Incentive,Mid,2025-07-28,2025-08-10
63433,2025-08-05,LAMPANG,N,LMD1O40P2,6,Mueang Lampang,824715336,LEGEND,NaN,5.1939,2.0000,3.1939,3.632990,1,25,25,0,0,0,20,20,0,0,0,20,9,11,20,0,0,0,0,0,0,0,0,0,0,0,0,0,316.80,NaN,NaN,NaN,18.0,18.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,334.800000,0.0,0.0,0.0,0.0,LAMPANG,0.53,Light,No Incentive,Mid,2025-07-28,2025-08-10
63434,2025-08-03,NAKHONNAYOK,N,LMDI1NBV7,2,Mueang Nakhon Nayok,652148872,BRONZE,NaN,3.6844,2.5725,1.1119,2.096867,1,16,16,0,0,0,10,10,0,0,0,10,9,1,10,0,0,0,0,0,0,0,0,0,0,0,0,0,179.53,NaN,NaN,NaN,20.0,20.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,199.530000,0.0,0.0,0.0,0.0,NAKHONNAYOK,0.00,no-rain,No Incentive,Bottom,2025-07-28,2025-08-10
63435,2025-07-28,PRACHINBURI,N,LMDNOYOTS,4,Mueang Prachin Buri,823509335,GOLD,NaN,1.8172,NaN,1.8172,1.638503,1,7,6,0,0,1,7,6,0,0,1,7,0,7,6,0,0,1,0,0,0,0,0,0,0,0,0,0,113.68,NaN,NaN,77.0,22.0,22.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,7,1.0,1.0,1,212.680000,0.0,NaN,0.0,0.0,PRACHINBURI,1.00,Light,No Incentive,Mid,2025-07-28,2025-08-10
63436,2025-08-06,NAKHONPATHOM,N,LMDB9EQRC,7,Mueang Nakhon Pathom,986540591,MASTER,NaN,8.8565,3.0000,5.8565,5.880800,1,29,26,2,1,0,29,26,2,1,0,29,13,16,26,2,1,0,0,0,0,0,0,0,0,0,0,0,777.88,59.61,32.672897,NaN,58.0,54.0,4.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,29,1.0,1.0,1,928.162897,0.0,0.0,0.0,0.0,NAKHONPATHOM,0.00,no-rain,No Incentive,Mid,2025-07-28,2025-08-10

In [47]:
saved['date'].max()

'2025-08-10'

In [18]:
pd.set_option('display.max_columns', None)