In [1]:
import pandas as pd
from pathlib import Path

In [2]:
orders710 = pd.read_csv('../../orderlevel_updated/tier_merged/tiers_merged_0710-0713.csv')

In [3]:
orders710.head(5)

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive
0,SURIN,LMD00BZBZ,2025-07-10 10:27:54.432,ก๋วยเตี๋ยวถนอมมิตร2 (Thanommit Noodles 2),Noodles,LMF-250710-408959062,True,13.50,3.0,30.0,...,687,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
1,SURIN,LMD00BZBZ,2025-07-10 10:32:29.887,ตำซี๊ด&อาหารตามสั่ง (Tum Zeed & Made-to-Order ...,Dessert,LMF-250710-161870697,True,17.80,3.0,95.0,...,1223,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
2,SURIN,LMD00BZBZ,2025-07-10 10:47:04.631,เฉิงกง ติ่มซำ (Chenggong Dim Sum) -,Dim Sum,LMF-250710-166811972,True,12.66,3.0,230.0,...,2458,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
3,SURIN,LMD00BZBZ,2025-07-10 10:56:22.791,Café Amazon - SD3192 (คาเฟ่ อเมซอน - SD3192) ส...,Café/Coffee Shop,LMF-250710-400808907,True,12.37,3.0,120.0,...,1180,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
4,SURIN,LMD00BZBZ,2025-07-10 11:09:04.244,Café Amazon - DD1655 (คาเฟ่ อเมซอน - DD1655) ป...,Café/Coffee Shop,LMF-250710-858627724,True,14.30,3.0,245.0,...,2035,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak

In [4]:
csv_files = sorted(Path('../../orderlevel_updated/tier_merged').glob('*.csv'))
output_dir = Path('./daily_productivity_results')
output_dir.mkdir(parents=True, exist_ok=True)

# display all files
for i, file in enumerate(csv_files, 1):
    print(f"{i}. {file.name}")
    
# Process each file
for i, csv_file in enumerate(csv_files, 1):
    print(f"\n[{i}/{len(csv_files)}] Processing: {csv_file.name}")
    print("-" * 80)
    
    df = pd.read_csv(csv_file)

    df['assign_created_at'] = pd.to_datetime(df['assign_created_at'])

    df = df.sort_values('assign_created_at')

    # Filter only accepted orders for counting 
    accepted_mask = df['is_driver_accept'] == True

    #colum that increments only for accepeted orders 
    df['increment'] = 0 
    df.loc[accepted_mask, 'increment'] = 1


    # running count of orders per week per driver
    df['daily_order_count'] = df.groupby(['driver_id', 'date'])['increment'].cumsum()

    # drop temporary column
    df = df.drop('increment', axis=1)

    #save to csv 
    output_path = output_dir / f'daily_productivity_{csv_file.name}'
    df.to_csv(output_path)
    print(f"Saved: {output_path}")

1. tiers_merged_0710-0713.csv
2. tiers_merged_0714-0716.csv
3. tiers_merged_0717-0720.csv
4. tiers_merged_0721-0725.csv
5. tiers_merged_0726-0727.csv
6. tiers_merged_0728-0801.csv
7. tiers_merged_0802-0806.csv
8. tiers_merged_0807-0810.csv
9. tiers_merged_0811-0815.csv
10. tiers_merged_0816-0820.csv
11. tiers_merged_0821-0825.csv
12. tiers_merged_0826-0829.csv

[1/12] Processing: tiers_merged_0710-0713.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0710-0713.csv

[2/12] Processing: tiers_merged_0714-0716.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0714-0716.csv

[3/12] Processing: tiers_merged_0717-0720.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0717-0720.csv

[4/12] Processing: tiers_merged_0721-0725.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0721-0725.csv

[5/12] Processing: tiers_merged_0726-0727.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0726-0727.csv

[6/12] Processing: tiers_merged_0728-0801.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0728-0801.csv

[7/12] Processing: tiers_merged_0802-0806.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0802-0806.csv

[8/12] Processing: tiers_merged_0807-0810.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0807-0810.csv

[9/12] Processing: tiers_merged_0811-0815.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0811-0815.csv

[10/12] Processing: tiers_merged_0816-0820.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0816-0820.csv

[11/12] Processing: tiers_merged_0821-0825.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0821-0825.csv

[12/12] Processing: tiers_merged_0826-0829.csv
--------------------------------------------------------------------------------
Saved: daily_productivity_results/daily_productivity_tiers_merged_0826-0829.csv

In [5]:
daily_prod_710 = pd.read_csv('./daily_productivity_results/daily_productivity_tiers_merged_0710-0713.csv')

In [6]:
daily_prod_710[(daily_prod_710['driver_id'] == 'LMDCSO52Z') & (daily_prod_710['date'] == '2025-07-10')]

,Unnamed: 0,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,...,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count
0,160727,UDONTHANI,LMDCSO52Z,2025-07-10 00:00:00.969,กะเพราทะลุฟ้า (Kapraotalufha) -,À La Carte,LMF-250709-194339998,True,20.29,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,1
23335,160728,UDONTHANI,LMDCSO52Z,2025-07-10 10:59:50.639,Five Star (ห้าดาว) ดูโฮม อุดรธานี,Barbeque/Grill,LMF-250710-419574625,False,24.00,5.0,...,EXPIRED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,1
26735,160729,UDONTHANI,LMDCSO52Z,2025-07-10 11:16:01.800,ครัวพุงกาง (Pung Kang Kitchen),À La Carte,LMF-250710-984283443,True,19.00,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,2
28067,160730,UDONTHANI,LMDCSO52Z,2025-07-10 11:22:21.890,ตำแซ่บอุดรธานี 1 (หน้าราชภัฏอุดร) (Tam Zaab Ud...,North East,LMF-250710-802551523,False,43.92,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,2
28248,160731,UDONTHANI,LMDCSO52Z,2025-07-10 11:23:11.190,อาหารตามสั่งครัวออโต้ (กะเพราแท้) (Auto Kitche...,À La Carte,LMF-250710-730251463,True,19.00,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
28364,160732,UDONTHANI,LMDCSO52Z,2025-07-10 11:23:44.760,MK Restaurants (เอ็มเค เรสโตรองต์) UD Town อุด...,Sukiyaki/Shabu,LMF-250710-389837582,False,32.34,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
28734,160733,UDONTHANI,LMDCSO52Z,2025-07-10 11:25:09.553,Mister Donut (มิสเตอร์ โดนัท) เซ็นทรัล พลาซ่า ...,Bakery/Cake,LMF-250710-869422156,False,27.89,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
29227,160734,UDONTHANI,LMDCSO52Z,2025-07-10 11:27:28.911,❤️( ขนมจีบ ซาลาเปา ) ❤️เฮง เฮง ติ่มซำ❤️ (Heng ...,Dim Sum,LMF-250710-008052974,False,19.00,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
30637,160735,UDONTHANI,LMDCSO52Z,2025-07-10 11:34:18.485,ครัวคุณยาย (KRUA KHUN YAY) ครัวคุณยาย,À La Carte,LMF-250710-152003343,False,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
31276,160736,UDONTHANI,LMDCSO52Z,2025-07-10 11:37:23.135,คำผัด (เดลิเวอรี่) หน้าหอพักดีเฮ้าส์,À La Carte,LMF-250710-344254779,True,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,4
31906,160737,UDONTHANI,LMDCSO52Z,2025-07-10 11:40:38.308,Café Amazon - CC5158 (คาเฟ่ อเมซอน - CC5158) ส...,Café/Coffee Shop,LMF-250710-636932644,True,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,5
32523,160738,UDONTHANI,LMDCSO52Z,2025-07-10 11:43:35.674,ลองดองยำ (Try Spicy Salad) อุดรธานี,North East,LMF-250710-284759693,False,24.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,5
33690,160739,UDONTHANI,LMDCSO52Z,2025-07-10 11:49:34.793,ครัวหนมน๊าม ไข่ปิ้งห่อหมกย่าง (หมากแข้ง) หมากแข้ง,Thai,LMF-250710-727268029,False,36.92,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,5
35838,160740,UDONTHANI,LMDCSO52Z,2025-07-10 12:00:47.792,ส้มตำสารคาม (Som Tum Sarakham),North East,LMF-250710-506046928,True,19.00,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,6
36003,160741,UDONTHANI,LMDCSO52Z,2025-07-10 12:01:41.439,STYLE SOUP ซุปหม่าล่า ไฮเทคไนซ์บาซาร์ Udon (สไ...,Sukiyaki/Shabu,LMF-250710-040443324,False,33.52,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,6
37374,160742,UDONTHANI,LMDCSO52Z,2025-07-10 12:09:16.266,ส.สมาร์ชอาหารตามสั่ง (sor smart restaurant),À La Carte,LMF-250710-276670424,True,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
40777,160743,UDONTHANI,LMDCSO52Z,2025-07-10 12:26:41.061,ส้มตำสารคาม (Som Tum Sarakham),North East,LMF-250710-374335142,False,24.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
41578,160744,UDONTHANI,LMDCSO52Z,2025-07-10 12:31:04.695,🐣 บ้านไก่อบถังมิสเตอร์ไฮ้ สาขาอุดรธานี สาขาอุด...,Rice Dish,LMF-250710-932327516,False,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
42570,160745,UDONTHANI,LMDCSO52Z,2025-07-10 12:36:35.527,ยำสามก๊ก อุดรธานี (Three Kingdoms Spicy Salad ...,Seafood,LMF-250710-884136179,False,34.93,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
42610,160746,UDONTHANI,LMDCSO52Z,2025-07-10 12:36:48.404,ตำซั่วนัวร์ปลาแดก (Spicy Papaya Salad with Fer...,North East,LMF-250710-853904565,False,30.80,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
42706,160747,UDONTHANI,LMDCSO52Z,2025-07-10 12:37:17.314,ตำซั่วนัวร์ปลาแดก (Spicy Papaya Salad with Fer...,North East,LMF-250710-788712697,False,34.20,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
44815,160748,UDONTHANI,LMDCSO52Z,2025-07-10 12:49:35.800,ร้านข้าวเปียกเส้นหัวเหลือง (Kao Piak Sen Hua L...,Noodles,LMF-250710-077303154,False,24.52,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
46024,160749,UDONTHANI,LMDCSO52Z,2025-07-10 12:57:15.270,ครัวหนมน๊าม ไข่ปิ้งห่อหมกย่าง (หมากแข้ง) หมากแข้ง,Thai,LMF-250710-154422325,True,20.28,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,8
46373,160750,UDONTHANI,LMDCSO52Z,2025-07-10 12:59:31.767,ยำสามก๊ก อุดรธานี (Three Kingdoms Spicy Salad ...,Seafood,LMF-250710-884136179,False,34.93,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,8
46405,160751,UDONTHANI,LMDCSO52Z,2025-07-10 12:59:45.773,ไก่ทอดซอสเกาหลี Indy Fried Chicken พรหมประกายอ...,Thai,LMF-250710-667392347,True,20.28,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,9
47338,160752,UDONTHANI,LMDCSO52Z,2025-07-10 13:04:00.837,เต็งหนึ่ง โรตี&ชาชัก (Teng Nueng Roti & Cha Ch...,Dessert,LMF-250710-702984709,True,20.28,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,10
51407,160753,UDONTHANI,LMDCSO52Z,2025-07-10 13:29:41.511,อิจิบังฉะ Ichibancha,Café/Coffee Shop,LMF-250710-192848185,True,19.00,10.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,11
53298,160754,UDONTHANI,LMDCSO52Z,2025-07-10 13:42:36.252,ตำซั่วนัวร์ปลาแดก (Spicy Papaya Salad with Fer...,North East,LMF-250710-700668494,True,19.00,5.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,12
55697,160755,UDONTHANI,LMDCSO52Z,2025-07-10 14:00:30.987,บะหมี่จ่าเปี๊ยก (Sergeant Piak Noodles),Noodles,LMF-250710-732020529,True,18.47,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,13
57089,160756,UDONTHANI,LMDCSO52Z,2025-07-10 14:06:47.867,"McDonald's (แมคโดนัลด์) ยูดีทาวน์, อุดรธานี (ไ...",Fastfood,LMF-250710-571599780,True,18.47,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,14
57214,160757,UDONTHANI,LMDCSO52Z,2025-07-10 14:07:37.334,PunThai Coffee (กาแฟพันธุ์ไทย) ยูดี ทาวน์ ฟู๊ด...,Café/Coffee Shop,LMF-250710-699465536,True,18.46,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,15
59171,160758,UDONTHANI,LMDCSO52Z,2025-07-10 14:21:14.996,เทสดี หม่าล่าทั่ง,Sukiyaki/Shabu,LMF-250710-408620051,True,51.20,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,16
68283,160759,UDONTHANI,LMDCSO52Z,2025-07-10 15:39:42.123,ต้าน้ำสุกี้โบราณ ซอยบ้านดอนอุดม 23/1 ม.7 ต.หมา...,À La Carte,LMF-250710-116932312,True,19.47,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,17
68390,160760,UDONTHANI,LMDCSO52Z,2025-07-10 15:40:38.096,ทะเลใต้ซีฟู้ด (โรตีชาใต้) (Thaleytaiseefood (R...,Muslim,LMF-250710-645674519,True,20.57,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,18
69815,160761,UDONTHANI,LMDCSO52Z,2025-07-10 15:54:50.772,คำผัด (เดลิเวอรี่) หน้าหอพักดีเฮ้าส์,À La Carte,LMF-250710-649164110,True,53.24,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,19
79191,160762,UDONTHANI,LMDCSO52Z,2025-07-10 17:26:56.179,ต.กระเพราระเบิด (Spicy Lab Udon Made-to-Order ...,À La Carte,LMF-250710-507795050,True,19.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,20
80418,160763,UDONTHANI,LMDCSO52Z,2025-07-10 17:37:42.071,บักหล่า อาหารอีสาน (Bakla),North East,LMF-250710-303413341,True,19.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,21
81434,160764,UDONTHANI,LMDCSO52Z,2025-07-10 17:47:03.107,ส้มตำเจ๊ไก่อุดร สาขา2 (4แยกวัดบ้านจิก) (Jae Ka...,North East,LMF-250710-748738813,True,30.80,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,22
82206,160765,UDONTHANI,LMDCSO52Z,2025-07-10 17:54:09.136,สเต็กหมีใหญ่ใจดี @อุดร (Big Bear Steak @Udon) ...,Steak House/Barbeque,LMF-250710-777298720,True,24.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,23
84861,160766,UDONTHANI,LMDCSO52Z,2025-07-10 18:16:54.163,ตำเหลาเมืองสกล (Tamlaomuangsakhon) อุดรธานี,North East,LMF-250710-928306850,True,24.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,24
85520,160767,UDONTHANI,LMDCSO52Z,2025-07-10 18:22:15.640,The Pizza Company (เดอะ พิซซ่า คอมปะนี) ทุ่งศร...,Pizza,LMF-250710-578336997,True,24.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,25
85988,160768,UDONTHANI,LMDCSO52Z,2025-07-10 18:25:58.837,ตำเหลาเมืองสกล (Tamlaomuangsakhon) อุดรธานี,North East,LMF-250710-974224008,True,24.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,26
89242,160769,UDONTHANI,LMDCSO52Z,2025-07-10 18:53:12.936,ยูดี แซลมอน สาขา 2 (Ud Salmon 2) บ้านบ่อน้ำ 2,Thai,LMF-250710-866918473,True,38.96,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,27
100586,160770,UDONTHANI,LMDCSO52Z,2025-07-10 20:53:12.872,หมิวบะหมี่เกี้ยว (Mew Wonton Noodles),Noodles,LMF-250710-137212388,True,23.43,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,28
100609,160771,UDONTHANI,LMDCSO52Z,2025-07-10 20:53:36.067,ก๋วยเตี๋ยวเนื้ออุดร-สามแยกยูดีทาวน์,Noodles,LMF-250710-275900985,True,24.09,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,29
102354,160772,UDONTHANI,LMDCSO52Z,2025-07-10 21:31:31.157,The Pizza Company (เดอะ พิซซ่า คอมปะนี) เมืองท...,Pizza,LMF-250710-386068374,True,23.76,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,30
102791,160773,UDONTHANI,LMDCSO52Z,2025-07-10 21:42:42.207,ข้าวยำไก่แซ่บประชาสันติ (Spicy Chicken Rice Pr...,Rice Dish,LMF-250710-737982658,True,23.76,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,31
103375,160774,UDONTHANI,LMDCSO52Z,2025-07-10 21:58:16.731,ลาบก้อย ดงอุดม (Lab Goi Dong Udom),North East,LMF-250710-680538070,True,24.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,32
104001,160775,UDONTHANI,LMDCSO52Z,2025-07-10 22:16:36.890,ข้าวยำไก่แซ่บประชาสันติ (Spicy Chicken Rice Pr...,Rice Dish,LMF-250710-462076729,True,22.40,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,33
104597,160776,UDONTHANI,LMDCSO52Z,2025-07-10 22:34:05.083,แจ่วฮ้อนสูตรเข้มข้น หมูกะทะ เจ๊จ้าว (ดงอุดม-หน...,Sukiyaki/Shabu,LMF-250710-268419103,True,43.72,3.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,34
105301,160777,UDONTHANI,LMDCSO52Z,2025-07-10 22:57:43.799,หม่าล่าพอแดกได้ สาขา 3 - บ้านเก่าน้อย สาขาบ้าน...,Barbeque/Grill,LMF-250710-357432448,True,41.00,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,35
105997,160778,UDONTHANI,LMDCSO52Z,2025-07-10 23:31:01.955,KFC (เคเอฟซี) GSDT Bangchak Udon Thani,Fastfood,LMF-250710-586684308,True,24.00,3.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,36
106078,160779,UDONTHANI,LMDCSO52Z,2025-07-10 23:35:37.098,KAPHRAO DEAWDAI - กะเพราเดียวดาย,À La Carte,LMF-250710-162397709,True,28.76,0.0,...,COMPLETED,2025-07-10,UDONTHANI,0.095333,Light,Top,2025-07-10,2025-07-13,Daily Productivity,37

In [7]:
daily_prod_711_LMD = daily_prod_710[(daily_prod_710['driver_id'] == 'LMDCSO52Z') & (daily_prod_710['date'] == '2025-07-11')]

In [8]:
daily_prod_711_LMD

,Unnamed: 0,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,...,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count
127814,160780,UDONTHANI,LMDCSO52Z,2025-07-11 10:39:00.410,ตามสั่ง 3.ก (Made-to-Order 3.K),À La Carte,LMF-250711-627428908,True,22.06,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,1
128044,160781,UDONTHANI,LMDCSO52Z,2025-07-11 10:40:27.216,ครัวยายเล็ก ฐานันดร (Grandma Lek's Kitchen Tha...,À La Carte,LMF-250711-393265155,True,22.06,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,2
134420,160782,UDONTHANI,LMDCSO52Z,2025-07-11 11:12:13.912,UD Salmon ยูดี แซลมอน,Japanese,LMF-250711-914683460,True,21.38,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,3
134616,160783,UDONTHANI,LMDCSO52Z,2025-07-11 11:13:06.377,UD Salmon ยูดี แซลมอน,Japanese,LMF-250711-841456818,True,21.38,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,4
138200,160784,UDONTHANI,LMDCSO52Z,2025-07-11 11:30:01.148,ก๋วยเตี๋ยวคุณกุ้ง(แม่สด) (Khun Kung's Noodles ...,Thai,LMF-250711-546358710,True,29.63,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,5
138544,160785,UDONTHANI,LMDCSO52Z,2025-07-11 11:31:33.658,🐣 บ้านไก่อบถังมิสเตอร์ไฮ้ สาขาอุดรธานี สาขาอุด...,Rice Dish,LMF-250711-387850906,True,20.39,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,6
139818,160786,UDONTHANI,LMDCSO52Z,2025-07-11 11:37:28.059,รสมือแม่อาหารอีสาน สูตรโบราณ,North East,LMF-250711-114530406,True,24.42,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,7
144451,160787,UDONTHANI,LMDCSO52Z,2025-07-11 12:01:38.077,ดงจุนเซ (Dong Jun Se) อุดรธานี,Korean,LMF-250711-341895447,True,20.70,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,8
147061,160788,UDONTHANI,LMDCSO52Z,2025-07-11 12:15:38.067,กินหมูกันมั้ย(ตลาดปรีชา),Rice Dish,LMF-250711-084456337,True,20.70,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,9
147581,160789,UDONTHANI,LMDCSO52Z,2025-07-11 12:18:19.728,Mister Donut (มิสเตอร์ โดนัท) เซ็นทรัล พลาซ่า ...,Bakery/Cake,LMF-250711-321304883,True,22.22,5.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,10
149658,160790,UDONTHANI,LMDCSO52Z,2025-07-11 12:28:20.602,🐣 บ้านไก่อบถังมิสเตอร์ไฮ้ สาขาอุดรธานี สาขาอุด...,Rice Dish,LMF-250711-040460491,True,17.33,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,11
151056,160791,UDONTHANI,LMDCSO52Z,2025-07-11 12:35:23.171,🐣 บ้านไก่อบถังมิสเตอร์ไฮ้ สาขาอุดรธานี สาขาอุด...,Rice Dish,LMF-250711-332239329,True,17.34,5.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,12
152009,160792,UDONTHANI,LMDCSO52Z,2025-07-11 12:40:27.190,ครัวแม่นอม อาหารตามสั่ง ก๋วยเตี๋ยว (Mae Nom's ...,À La Carte,LMF-250711-089315355,True,19.00,5.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,13
152329,160793,UDONTHANI,LMDCSO52Z,2025-07-11 12:42:15.899,🐣 บ้านไก่อบถังมิสเตอร์ไฮ้ สาขาอุดรธานี สาขาอุด...,Rice Dish,LMF-250711-790093792,True,17.33,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,14
154675,160794,UDONTHANI,LMDCSO52Z,2025-07-11 12:54:32.515,ฝากท้อง อาหารตามสั่ง (Fak Thong Made-to-Order ...,À La Carte,LMF-250711-367999948,True,19.00,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,15
162098,160795,UDONTHANI,LMDCSO52Z,2025-07-11 13:32:06.788,ก๋วยเตี๋ยวเรือสายเเข็ง สาขาต้นตำรับ (Boat Nood...,Noodles,LMF-250711-800825408,True,28.08,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,16
185869,160796,UDONTHANI,LMDCSO52Z,2025-07-11 16:30:08.760,The Pizza Company (เดอะ พิซซ่า คอมปะนี) ทุ่งศร...,Pizza,LMF-250711-443653666,True,34.47,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,17
188548,160797,UDONTHANI,LMDCSO52Z,2025-07-11 16:55:21.247,ชาพะยอมต้นตำรับ @หมากแข้ง (Cha Payom Original ...,Bubble Milk Tea,LMF-250711-822487461,True,19.85,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,18
189361,160798,UDONTHANI,LMDCSO52Z,2025-07-11 17:01:50.475,Café Amazon - DD2635 (คาเฟ่ อเมซอน - DD2635) ส...,Café/Coffee Shop,LMF-250711-086901469,True,24.00,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,19
192694,160799,UDONTHANI,LMDCSO52Z,2025-07-11 17:31:07.868,ก๋วยเตี๋ยวเรือรสนิยม รสเจ็บใจเสาะ,Noodles,LMF-250711-760770794,True,19.34,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,20
193208,160800,UDONTHANI,LMDCSO52Z,2025-07-11 17:35:03.859,ก๋วยจั๊บอุบล สูตรโบราณ เจ้แอ๋วห้าแยก (Ubon Thi...,Rice Dish,LMF-250711-007367267,True,34.88,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,21
194355,160801,UDONTHANI,LMDCSO52Z,2025-07-11 17:44:55.496,ลาบวัวคึก3 (Larb Beef Kuek 3),Delivery Only,LMF-250711-800056287,True,19.34,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,22
200516,160802,UDONTHANI,LMDCSO52Z,2025-07-11 18:37:58.566,ยูดี แซลมอน สาขา 2 (Ud Salmon 2) บ้านบ่อน้ำ 2,Thai,LMF-250711-010314900,True,26.72,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,23
200595,160803,UDONTHANI,LMDCSO52Z,2025-07-11 18:38:54.533,ศิวพรแหนมเนือง เจ้อ้วนเจ้าเก่า ตลาดห้าแยก (SIW...,Fastfood,LMF-250711-920208161,True,32.16,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,24
202502,160804,UDONTHANI,LMDCSO52Z,2025-07-11 18:55:28.097,"เหลา จาน เดียว ข้าวผัดปู (Single Dish, Crab Fr...",Chinese,LMF-250711-584773019,True,24.00,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,25
205084,160805,UDONTHANI,LMDCSO52Z,2025-07-11 19:16:08.374,เอ ไก่ทอด (ตลาดโพธิ์ศรี)แผงที่82 (A Fried Chic...,Food Truck,LMF-250711-121116942,True,19.00,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,26
206837,160806,UDONTHANI,LMDCSO52Z,2025-07-11 19:31:05.238,ตำบักหยืด by zeusmilk (Tam Bak Yued),North East,LMF-250711-486152762,True,19.00,0.0,...,COMPLETED,2025-07-11,UDONTHANI,0.502,Light,Top,2025-07-10,2025-07-13,Daily Productivity,27

In [9]:
tiers0710 = pd.read_csv('../../orderlevel_updated/tier_merged/tiers_merged_0710-0713.csv')

In [10]:
tiers0710

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive
0,SURIN,LMD00BZBZ,2025-07-10 10:27:54.432,ก๋วยเตี๋ยวถนอมมิตร2 (Thanommit Noodles 2),Noodles,LMF-250710-408959062,True,13.50,3.0,30.0,...,687,COMPLETED,2025-07-10,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13,Streak
1,SURIN,LMD00BZBZ,2025-07-10 10:32:29.887,ตำซี๊ด&อาหารตามสั่ง (Tum Zeed & Made-to-Order ...,Dessert,LMF-250710-161870697,True,17.80,3.0,95.0,...,1223,COMPLETED,2025-07-10,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13,Streak
2,SURIN,LMD00BZBZ,2025-07-10 10:47:04.631,เฉิงกง ติ่มซำ (Chenggong Dim Sum) -,Dim Sum,LMF-250710-166811972,True,12.66,3.0,230.0,...,2458,COMPLETED,2025-07-10,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13,Streak
3,SURIN,LMD00BZBZ,2025-07-10 10:56:22.791,Café Amazon - SD3192 (คาเฟ่ อเมซอน - SD3192) ส...,Café/Coffee Shop,LMF-250710-400808907,True,12.37,3.0,120.0,...,1180,COMPLETED,2025-07-10,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13,Streak
4,SURIN,LMD00BZBZ,2025-07-10 11:09:04.244,Café Amazon - DD1655 (คาเฟ่ อเมซอน - DD1655) ป...,Café/Coffee Shop,LMF-250710-858627724,True,14.30,3.0,245.0,...,2035,COMPLETED,2025-07-10,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13,Streak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446839,KHONKAEN,LMDZZTVOL,2025-07-13 18:02:20.882,ไก่ย่าง คุณชายพงษ์ สาขา2 (Grilled Chicken Khun...,Barbeque/Grill,LMF-250713-886872839,True,28.15,0.0,80.0,...,2204,COMPLETED,2025-07-13,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13,Streak
446840,KHONKAEN,LMDZZTVOL,2025-07-13 18:12:20.941,ชายเอ็ม อาหารป่าตามสั่ง,À La Carte,LMF-250713-215283708,True,19.37,0.0,73.0,...,1213,COMPLETED,2025-07-13,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13,Streak
446841,KHONKAEN,LMDZZTVOL,2025-07-13 18:27:40.802,ล่อแซลม่อน (Lor’ salmon) >> ข้าวแซลม่อนดอง,Japanese,LMF-250713-869785683,True,27.52,0.0,305.0,...,2372,COMPLETED,2025-07-13,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13,Streak
446842,KHONKAEN,LMDZZTVOL,2025-07-13 18:34:57.430,Café Amazon - SC5179 (คาเฟ่ อเมซอน - SC5179) G...,Café/Coffee Shop,LMF-250713-256834900,True,19.32,0.0,105.0,...,1709,COMPLETED,2025-07-13,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13,Streak
446843,KHONKAEN,LMDZZTVOL,2025-07-13 18:53:03.799,สักกำบ๋อ (Sak Kam Bo),Café/Coffee Shop,LMF-250713-958786884,True,24.00,0.0,97.0,...,1966,COMPLETED,2025-07-13,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13,Streak

In [11]:
tiers0710[tiers0710['is_driver_accept'] == False]

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive
23,SURIN,LMD00BZBZ,2025-07-10 17:20:36.966,Starbucks (สตาร์บัคส์) Robinson Surin,Café/Coffee Shop,LMF-250710-252882921,False,27.00,3.0,325.00,...,1441,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
27,SURIN,LMD00BZBZ,2025-07-10 18:09:48.049,ยำแซ่บนัวร์(Yumzapnuar)-หลังมอ (Yum Zap Nuar),Street Food/Food Stands,LMF-250710-256156316,False,18.32,3.0,141.00,...,2026,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
45,SURIN,LMD00BZBZ,2025-07-11 10:59:38.584,Kamu Tea (คามุ) PTT Surin,Bubble Milk Tea,LMF-250711-029405877,False,17.00,3.0,90.00,...,1442,COMPLETED,2025-07-11,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
48,SURIN,LMD00BZBZ,2025-07-11 11:22:10.834,ส้มตำ ทบ.อุบลฯ สาขาสุรินทร์ 1-ถนนสุรินทร์ ศรีข...,Thai,LMF-250711-071206850,False,17.00,8.0,347.00,...,2376,COMPLETED,2025-07-11,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
50,SURIN,LMD00BZBZ,2025-07-11 11:38:52.481,Oishi Kitchen (โออิชิ คิทเช่น) ภายใต้ครัว ชาบู...,Japanese,LMF-250711-764456431,False,12.73,3.0,198.00,...,2480,COMPLETED,2025-07-11,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13,Streak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446582,RATCHABURI_Banpong,LMDZZICT6,2025-07-11 17:42:02.257,หม่าล่านายหนึ่ง & กระเพรา 39 (Mala Nai Nueng &...,Street Food/Food Stands,LMF-250711-680297407,False,24.70,0.0,75.00,...,2919,COMPLETED,2025-07-11,RATCHABURI_Banpong,0.0,no-rain,Bottom,2025-07-10,2025-07-13,No Incentive
446637,KRABI,LMDZZPA6L,2025-07-11 12:23:51.891,Sabai Day Cafe' สบายเดย์คาเฟ่ (สะ-บาย-เดย์ คาเ...,Cafe,LMF-250711-673379711,False,21.80,5.0,145.00,...,1305,COMPLETED,2025-07-11,KRABI,0.0,no-rain,Bottom,2025-07-10,2025-07-13,No Incentive
446638,KRABI,LMDZZPA6L,2025-07-11 12:33:59.628,ก๋วยเตี๋ยวสุโขทัย by คุณจันทร์ สาขาเหนือคลอง (...,Noodles,LMF-250711-115817735,False,20.20,5.0,131.35,...,1202,COMPLETED,2025-07-11,KRABI,0.0,no-rain,Bottom,2025-07-10,2025-07-13,No Incentive
446797,KHONKAEN,LMDZZTVOL,2025-07-12 18:37:24.528,อร่อยท้ายซอย/ร้านลุงเหลิม (Aroi Tai Soi / Uncl...,À La Carte,LMF-250712-031899843,False,24.00,5.0,89.00,...,1530,COMPLETED,2025-07-12,KHONKAEN,0.0,no-rain,Top,2025-07-10,2025-07-13,Streak
446802,KHONKAEN,LMDZZTVOL,2025-07-12 19:39:46.024,แซบม่วน ร.8 (แซบม่วน) ร.8 -,North East,LMF-250712-734325846,False,17.33,5.0,195.00,...,1856,COMPLETED,2025-07-12,KHONKAEN,0.0,no-rain,Top,2025-07-10,2025-07-13,Streak