In [16]:
import pandas as pd
import numpy as np

In [17]:
streak_results = pd.read_csv('./streak/streak_results/streak_results_with_incentives.csv')

In [18]:
streak_results.columns

Index(['Unnamed: 0', 'Region', 'driver_id', 'assign_created_at',
       'restaurant_name', 'restaurant_category', 'order_id',
       'is_driver_accept', 'wage', 'on_top_fare', 'basket_size',
       'drop_off_distance', 'distance_rider_to_restaurant',
       'placed_to_match_second', 'rider_matched_to_arrived_restaurant_second',
       'rider_waiting_time_in_restaurant_second',
       'delivery_time_to_user_second', 'total_user_waiting_time_second',
       'order_status', 'date', 'region::multi-filter', 'avg_rain',
       'Rain_Level', 'Tier', 'Start Date_x', 'End Date_x', 'Incentive',
       'daily_order_count', 'time_per_order_sec', 'time_worked_sec', 'hour',
       'daily_cumulative_time_sec', 'time_worked_in_window_sec',
       'window_cumulative_sec', 'daily_cumulative_time_hr',
       'window_cumulative_hr', 'Unnamed: 0.1', 'day_of_week',
       'day_of_week_short', 'week_start_date', 'year', 'week',
       'days_worked_count', 'days_worked_list', 'has_required_days',
       'is_target1_day', 'is_target2_day', 'is_target3_day',
       'is_accepted_target1', 'is_accepted_target2', 'is_accepted_target3',
       'orders_target1_cumulative', 'orders_target2_cumulative',
       'orders_target3_cumulative', 'worked_target1_days',
       'worked_target2_days', 'worked_target3_days', 'Start Date_y',
       'End Date_y', 'Daily Guarantee Required Online Hour',
       'Daily Guarantee Hunting hour period',
       'Daily Guarantee Required Hunting Hour', 'Daily Guarantee amount',
       'Active Hour Required Online Hour', 'Active Hour Hunting hour period',
       'Active Hour Required Hunting Hour', 'Active Hour Required day',
       'Active Hour Require Dow', 'Active Hour Reward',
       'Daily Productivity target', 'Daily Productivity Reward',
       'Streak target', 'Streak Reward', 'streak target P1',
       'streak reward P1', 'streak target P2', 'streak reward P2',
       'streak target P3', 'streak reward P3', 'Start Date', 'End Date'],
      dtype='object')

In [19]:
streak_results

,Unnamed: 0,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Start Date_x,End Date_x,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Unnamed: 0.1,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,is_accepted_target1,is_accepted_target2,is_accepted_target3,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Start Date_y,End Date_y,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date
0,0,SURIN,LMD00BZBZ,2025-07-14 18:09:26.890,ซัซกูว ชาบูวากิว บุฟเฟต์ (Sasgoo Shabu Wagyu B...,Sukiyaki/Shabu,LMF-250714-380442187,True,19.80,3.0,129.00,4657.0,1763.1,1557,357,27,861,2802,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,1,888,888.0,18,888.0,888.0,888.0,0.246667,0.246667,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,1,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
1,1,SURIN,LMD00BZBZ,2025-07-14 18:12:10.263,ผัดไทยสะบัดเส้น (Patthausabutsent) หลังมอ,Rice Dish,LMF-250714-460422944,True,17.00,3.0,111.80,3507.0,1882.8,1031,461,60,414,1966,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,2,474,474.0,18,1362.0,474.0,1362.0,0.378333,0.378333,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,2,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
2,2,SURIN,LMD00BZBZ,2025-07-14 18:43:50.165,"หมูกรอบบอกต่อ (Crispy Pork, Spread the Word)",Street Food/Food Stands,LMF-250714-270459334,True,14.93,3.0,80.00,4379.0,214.9,1142,550,12,547,2251,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,3,559,559.0,18,1921.0,559.0,1921.0,0.533611,0.533611,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,3,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
3,3,SURIN,LMD00BZBZ,2025-07-14 18:55:45.210,ผัดไทยหอยทอดแม่ทองตลาดไอคิว (Pad Thai Mea Thon...,Thai,LMF-250714-678571326,True,18.47,3.0,124.00,5455.0,2515.9,426,455,660,225,1766,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,4,885,885.0,18,2806.0,885.0,2806.0,0.779444,0.779444,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,4,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
4,4,SURIN,LMD00BZBZ,2025-07-14 19:19:20.788,รอยยิ้มที่หายไป หลังบิ๊กซี,À La Carte,LMF-250714-345482995,True,21.40,3.0,77.40,5115.0,385.5,860,19,109,615,1603,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,5,724,724.0,19,3530.0,724.0,3530.0,0.980556,0.980556,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,5,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3008769,300180,PHAYAO,LMDZZVYF8,2025-08-28 14:38:39.851,scene café,Café/Coffee Shop,LMF-250828-956989397,True,18.12,0.0,144.15,3798.0,3690.4,161,1285,720,137,2303,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,9,857,857.0,14,8154.0,0.0,0.0,2.265000,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,25,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008770,300181,PHAYAO,LMDZZVYF8,2025-08-28 15:07:40.477,สวนสลัด ( ลุยสวน & สลัด ) (Salad Garden (Garde...,Healthy Food,LMF-250828-063418171,True,12.50,0.0,145.00,1924.0,326.1,981,82,48,386,1497,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,10,434,434.0,15,8588.0,0.0,0.0,2.385556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,26,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008771,300182,PHAYAO,LMDZZVYF8,2025-08-28 15:14:52.401,ร้านมีดี (Mee Dee Shop) ร้านครัวมีดี,Rice Dish,LMF-250828-506015986,True,12.50,0.0,94.00,1262.0,1536.6,550,116,430,344,1440,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,11,774,774.0,15,9362.0,0.0,0.0,2.600556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,27,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008772,300183,PHAYAO,LMDZZVYF8,2025-08-28 16:16:31.814,Café Amazon - DD559 (คาเฟ่ อเมซอน - DD559) ปตท...,Café/Coffee Shop,LMF-250828-744565394,True,15.00,0.0,55.00,1343.0,2211.7,4,412,230,346,992,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,12,576,576.0,16,9938.0,0.0,0.0,2.760556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,28,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008773,300184,PHAYAO,LMDZZVYF8,2025-08-28 16:41:20.837,เครปป้าดาว - หลังโรงเรียนบ้านร่องห้า (Aunt Dao...,Dessert,LMF-250828-926983153,True,16.20,0.0,105.00,3331.0,2619.7,5,813,13,438,1269,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,13,451,451.0,16,10389.0,0.0,0.0,2.885833,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,29,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29

In [20]:
# Display all rows and columns
pd.set_option('display.max_columns', None)
streak_results

,Unnamed: 0,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Start Date_x,End Date_x,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Unnamed: 0.1,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,is_accepted_target1,is_accepted_target2,is_accepted_target3,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Start Date_y,End Date_y,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date
0,0,SURIN,LMD00BZBZ,2025-07-14 18:09:26.890,ซัซกูว ชาบูวากิว บุฟเฟต์ (Sasgoo Shabu Wagyu B...,Sukiyaki/Shabu,LMF-250714-380442187,True,19.80,3.0,129.00,4657.0,1763.1,1557,357,27,861,2802,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,1,888,888.0,18,888.0,888.0,888.0,0.246667,0.246667,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,1,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
1,1,SURIN,LMD00BZBZ,2025-07-14 18:12:10.263,ผัดไทยสะบัดเส้น (Patthausabutsent) หลังมอ,Rice Dish,LMF-250714-460422944,True,17.00,3.0,111.80,3507.0,1882.8,1031,461,60,414,1966,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,2,474,474.0,18,1362.0,474.0,1362.0,0.378333,0.378333,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,2,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
2,2,SURIN,LMD00BZBZ,2025-07-14 18:43:50.165,"หมูกรอบบอกต่อ (Crispy Pork, Spread the Word)",Street Food/Food Stands,LMF-250714-270459334,True,14.93,3.0,80.00,4379.0,214.9,1142,550,12,547,2251,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,3,559,559.0,18,1921.0,559.0,1921.0,0.533611,0.533611,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,3,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
3,3,SURIN,LMD00BZBZ,2025-07-14 18:55:45.210,ผัดไทยหอยทอดแม่ทองตลาดไอคิว (Pad Thai Mea Thon...,Thai,LMF-250714-678571326,True,18.47,3.0,124.00,5455.0,2515.9,426,455,660,225,1766,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,4,885,885.0,18,2806.0,885.0,2806.0,0.779444,0.779444,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,4,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
4,4,SURIN,LMD00BZBZ,2025-07-14 19:19:20.788,รอยยิ้มที่หายไป หลังบิ๊กซี,À La Carte,LMF-250714-345482995,True,21.40,3.0,77.40,5115.0,385.5,860,19,109,615,1603,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,2025-07-14,2025-07-20,Streak,5,724,724.0,19,3530.0,724.0,3530.0,0.980556,0.980556,NaN,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,True,False,False,5,0,0,False,False,False,2025-07-14,2025-07-20,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3008769,300180,PHAYAO,LMDZZVYF8,2025-08-28 14:38:39.851,scene café,Café/Coffee Shop,LMF-250828-956989397,True,18.12,0.0,144.15,3798.0,3690.4,161,1285,720,137,2303,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,9,857,857.0,14,8154.0,0.0,0.0,2.265000,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,25,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008770,300181,PHAYAO,LMDZZVYF8,2025-08-28 15:07:40.477,สวนสลัด ( ลุยสวน & สลัด ) (Salad Garden (Garde...,Healthy Food,LMF-250828-063418171,True,12.50,0.0,145.00,1924.0,326.1,981,82,48,386,1497,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,10,434,434.0,15,8588.0,0.0,0.0,2.385556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,26,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008771,300182,PHAYAO,LMDZZVYF8,2025-08-28 15:14:52.401,ร้านมีดี (Mee Dee Shop) ร้านครัวมีดี,Rice Dish,LMF-250828-506015986,True,12.50,0.0,94.00,1262.0,1536.6,550,116,430,344,1440,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,11,774,774.0,15,9362.0,0.0,0.0,2.600556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,27,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008772,300183,PHAYAO,LMDZZVYF8,2025-08-28 16:16:31.814,Café Amazon - DD559 (คาเฟ่ อเมซอน - DD559) ปตท...,Café/Coffee Shop,LMF-250828-744565394,True,15.00,0.0,55.00,1343.0,2211.7,4,412,230,346,992,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,12,576,576.0,16,9938.0,0.0,0.0,2.760556,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,28,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29
3008773,300184,PHAYAO,LMDZZVYF8,2025-08-28 16:41:20.837,เครปป้าดาว - หลังโรงเรียนบ้านร่องห้า (Aunt Dao...,Dessert,LMF-250828-926983153,True,16.20,0.0,105.00,3331.0,2619.7,5,813,13,438,1269,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,2025-08-23,2025-08-29,Daily Productivity,13,451,451.0,16,10389.0,0.0,0.0,2.885833,0.000000,NaN,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,False,True,False,31,29,0,True,False,False,2025-08-23,2025-08-29,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29

In [21]:
streak_results = streak_results.drop(['hour', 'time_worked_sec', 'Unnamed: 0.1', 'Unnamed: 0', 'is_accepted_target1', 'is_accepted_target2', 'is_accepted_target3', 'Start Date_x', 'End Date_x', 'Start Date_y', 'End Date_y'], axis=1)

In [22]:
def count_matching_days(row):
    # Convert string to list by splitting on comma
    if pd.isna(row['days_worked_list']) or pd.isna(row['Active Hour Require Dow']):
        return 0
    
    # Split and clean the strings
    days_worked = [day.strip() for day in str(row['days_worked_list']).split(',')]
    required_dow = [day.strip() for day in str(row['Active Hour Require Dow']).split(',')]
    
    # Count matches
    return sum(1 for day in days_worked if day in required_dow)

streak_results['days_required_worked_count'] = streak_results.apply(count_matching_days, axis=1)

In [23]:
streak_results

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count
0,SURIN,LMD00BZBZ,2025-07-14 18:09:26.890,ซัซกูว ชาบูวากิว บุฟเฟต์ (Sasgoo Shabu Wagyu B...,Sukiyaki/Shabu,LMF-250714-380442187,True,19.80,3.0,129.00,4657.0,1763.1,1557,357,27,861,2802,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,1,888,888.0,888.0,888.0,0.246667,0.246667,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,1,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1
1,SURIN,LMD00BZBZ,2025-07-14 18:12:10.263,ผัดไทยสะบัดเส้น (Patthausabutsent) หลังมอ,Rice Dish,LMF-250714-460422944,True,17.00,3.0,111.80,3507.0,1882.8,1031,461,60,414,1966,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,2,474,1362.0,474.0,1362.0,0.378333,0.378333,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,2,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1
2,SURIN,LMD00BZBZ,2025-07-14 18:43:50.165,"หมูกรอบบอกต่อ (Crispy Pork, Spread the Word)",Street Food/Food Stands,LMF-250714-270459334,True,14.93,3.0,80.00,4379.0,214.9,1142,550,12,547,2251,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,3,559,1921.0,559.0,1921.0,0.533611,0.533611,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,3,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1
3,SURIN,LMD00BZBZ,2025-07-14 18:55:45.210,ผัดไทยหอยทอดแม่ทองตลาดไอคิว (Pad Thai Mea Thon...,Thai,LMF-250714-678571326,True,18.47,3.0,124.00,5455.0,2515.9,426,455,660,225,1766,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,4,885,2806.0,885.0,2806.0,0.779444,0.779444,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,4,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1
4,SURIN,LMD00BZBZ,2025-07-14 19:19:20.788,รอยยิ้มที่หายไป หลังบิ๊กซี,À La Carte,LMF-250714-345482995,True,21.40,3.0,77.40,5115.0,385.5,860,19,109,615,1603,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,5,724,3530.0,724.0,3530.0,0.980556,0.980556,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,5,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3008769,PHAYAO,LMDZZVYF8,2025-08-28 14:38:39.851,scene café,Café/Coffee Shop,LMF-250828-956989397,True,18.12,0.0,144.15,3798.0,3690.4,161,1285,720,137,2303,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,Daily Productivity,9,857,8154.0,0.0,0.0,2.265000,0.000000,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,31,25,0,True,False,False,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29,1
3008770,PHAYAO,LMDZZVYF8,2025-08-28 15:07:40.477,สวนสลัด ( ลุยสวน & สลัด ) (Salad Garden (Garde...,Healthy Food,LMF-250828-063418171,True,12.50,0.0,145.00,1924.0,326.1,981,82,48,386,1497,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,Daily Productivity,10,434,8588.0,0.0,0.0,2.385556,0.000000,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,31,26,0,True,False,False,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29,1
3008771,PHAYAO,LMDZZVYF8,2025-08-28 15:14:52.401,ร้านมีดี (Mee Dee Shop) ร้านครัวมีดี,Rice Dish,LMF-250828-506015986,True,12.50,0.0,94.00,1262.0,1536.6,550,116,430,344,1440,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,Daily Productivity,11,774,9362.0,0.0,0.0,2.600556,0.000000,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,31,27,0,True,False,False,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29,1
3008772,PHAYAO,LMDZZVYF8,2025-08-28 16:16:31.814,Café Amazon - DD559 (คาเฟ่ อเมซอน - DD559) ปตท...,Café/Coffee Shop,LMF-250828-744565394,True,15.00,0.0,55.00,1343.0,2211.7,4,412,230,346,992,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,Daily Productivity,12,576,9938.0,0.0,0.0,2.760556,0.000000,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,31,28,0,True,False,False,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29,1
3008773,PHAYAO,LMDZZVYF8,2025-08-28 16:41:20.837,เครปป้าดาว - หลังโรงเรียนบ้านร่องห้า (Aunt Dao...,Dessert,LMF-250828-926983153,True,16.20,0.0,105.00,3331.0,2619.7,5,813,13,438,1269,COMPLETED,2025-08-28,PHAYAO,0.00,no-rain,Mid,Daily Productivity,13,451,10389.0,0.0,0.0,2.885833,0.000000,Thursday,Thu,2025-08-25,2025,35,4,"Mon, Thu, Tue, Wed",False,False,True,False,31,29,0,True,False,False,7.0,6.0,5.0,965.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2170.0,35.0,365.0,34.0,2530.0,35.0,800.0,35.0,1085.0,33.0,655.0,2025-08-23,2025-08-29,1

In [24]:
streak_results[streak_results['days_required_worked_count'] == 3]

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count
79,SURIN,LMD00BZBZ,2025-07-19 10:13:59.577,อาหารตามสั่งปากซอยทรัพย์ธานี,À La Carte,LMF-250719-113473948,True,21.80,3.0,65.0,5204.0,2900.8,2139,515,25,706,3385,COMPLETED,2025-07-19,SURIN,0.16,Light,Mid,Streak,1,731,731.0,731.0,731.0,0.203056,0.203056,Saturday,Sat,2025-07-14,2025,29,4,"Fri, Mon, Sat, Tue",False,False,False,True,46,30,1,True,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,3
80,SURIN,LMD00BZBZ,2025-07-19 11:10:12.491,ตำแซ่บนัว - สาขาหลังมอ | By ยำแซ่บนัว ตำแซ่บนัว,North East,LMF-250719-637503082,True,11.00,3.0,53.1,1550.0,2723.3,112,253,492,89,946,COMPLETED,2025-07-19,SURIN,0.16,Light,Mid,Streak,2,581,1312.0,581.0,1312.0,0.364444,0.364444,Saturday,Sat,2025-07-14,2025,29,4,"Fri, Mon, Sat, Tue",False,False,False,True,46,30,2,True,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,3
81,SURIN,LMD00BZBZ,2025-07-19 11:10:15.852,ทองหล่อ คาเฟ่ นอกเมือง,Bubble Milk Tea,LMF-250719-838887240,True,11.00,3.0,45.0,473.0,336.0,299,469,185,153,1106,COMPLETED,2025-07-19,SURIN,0.16,Light,Mid,Streak,3,338,1650.0,338.0,1650.0,0.458333,0.458333,Saturday,Sat,2025-07-14,2025,29,4,"Fri, Mon, Sat, Tue",False,False,False,True,46,30,3,True,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,3
82,SURIN,LMD00BZBZ,2025-07-19 11:11:59.057,Hop Chafe,Bubble Milk Tea,LMF-250719-473059405,True,11.00,3.0,63.0,1249.0,1787.8,49,635,367,145,1196,COMPLETED,2025-07-19,SURIN,0.16,Light,Mid,Streak,4,512,2162.0,512.0,2162.0,0.600556,0.600556,Saturday,Sat,2025-07-14,2025,29,4,"Fri, Mon, Sat, Tue",False,False,False,True,46,30,4,True,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,3
83,SURIN,LMD00BZBZ,2025-07-19 11:24:35.800,เลเลอ 2 @ซอยภาคะ บ้านเจียมเนียง (Le Le 2 @Soi ...,Rice Dish,LMF-250719-747551227,True,12.33,3.0,180.0,2866.0,305.0,404,1522,390,303,2619,COMPLETED,2025-07-19,SURIN,0.16,Light,Mid,Streak,5,693,2855.0,693.0,2855.0,0.793056,0.793056,Saturday,Sat,2025-07-14,2025,29,4,"Fri, Mon, Sat, Tue",False,False,False,True,46,30,5,True,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3008596,PHAYAO,LMDZZVYF8,2025-08-17 12:27:54.270,ก๋วยเตี๋ยวอันเจริญหลังตลาดพะเยา (เฮียน้อย) (อั...,Noodles,LMF-250817-802122167,True,25.46,2.0,150.0,5845.0,0.0,0,1121,971,418,2510,COMPLETED,2025-08-17,PHAYAO,0.21,Light,Mid,No Incentive,24,1389,15132.0,1389.0,9354.0,4.203333,2.598333,Sunday,Sun,2025-08-11,2025,33,6,"Mon, Sat, Sun, Thu, Tue, Wed",False,False,False,True,50,29,34,True,False,True,7.0,6.0,5.0,790.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",1530.0,30.0,255.0,30.0,1785.0,31.0,565.0,31.0,765.0,29.0,460.0,2025-08-16,2025-08-22,3
3008597,PHAYAO,LMDZZVYF8,2025-08-17 15:55:20.776,MK Restaurants (เอ็มเค เรสโตรองต์) เทสโก้ โลตั...,Sukiyaki/Shabu,LMF-250817-211622216,True,12.51,0.0,683.0,786.0,0.0,831,893,7,289,2020,COMPLETED,2025-08-17,PHAYAO,0.21,Light,Mid,No Incentive,25,296,15428.0,0.0,9354.0,4.285556,2.598333,Sunday,Sun,2025-08-11,2025,33,6,"Mon, Sat, Sun, Thu, Tue, Wed",False,False,False,True,50,29,35,True,False,True,7.0,6.0,5.0,790.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",1530.0,30.0,255.0,30.0,1785.0,31.0,565.0,31.0,765.0,29.0,460.0,2025-08-16,2025-08-22,3
3008598,PHAYAO,LMDZZVYF8,2025-08-17 16:01:01.116,KFC (เคเอฟซี) โลตัส พะเยา,Fastfood,LMF-250817-051160816,True,13.18,0.0,913.0,3204.0,737.8,490,843,744,289,2365,COMPLETED,2025-08-17,PHAYAO,0.21,Light,Mid,No Incentive,26,1033,16461.0,0.0,9354.0,4.572500,2.598333,Sunday,Sun,2025-08-11,2025,33,6,"Mon, Sat, Sun, Thu, Tue, Wed",False,False,False,True,50,29,36,True,False,True,7.0,6.0,5.0,790.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",1530.0,30.0,255.0,30.0,1785.0,31.0,565.0,31.0,765.0,29.0,460.0,2025-08-16,2025-08-22,3
3008599,PHAYAO,LMDZZVYF8,2025-08-17 16:32:06.501,แกงกะทิแม่ทิม@ถนนคนเดิน&งานแฟร์ (Coconut Curry...,Thai,LMF-250817-590836033,True,20.50,0.0,65.0,4735.0,729.8,336,840,1263,506,2945,COMPLETED,2025-08-17,PHAYAO,0.21,Light,Mid,No Incentive,27,1769,18230.0,0.0,9354.0,5.063889,2.598333,Sunday,Sun,2025-08-11,2025,33,6,"Mon, Sat, Sun, Thu, Tue, Wed",False,False,False,True,50,29,37,True,False,True,7.0,6.0,5.0,790.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",1530.0,30.0,255.0,30.0,1785.0,31.0,565.0,31.0,765.0,29.0,460.0,2025-08-16,2025-08-22,3
3008600,PHAYAO,LMDZZVYF8,2025-08-17 16:37:09.917,Neko Don (เนโกะ ด้ง) 1,Japanese,LMF-250817-725139803,True,14.10,0.0,566.0,1080.0,962.3,5,1656,48,390,2099,COMPLETED,2025-08-17,PHAYAO,0.21,Light,Mid,No Incentive,28,438,18668.0,0.0,9354.0,5.185556,2.598333,Sunday,Sun,2025-08-11,2025,33,6,"Mon, Sat, Sun, Thu, Tue, Wed",False,False,False,True,50,29,38,True,False,True,7.0,6.0,5.0,790.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",1530.0,30.0,255.0,30.0,1785.0,31.0,565.0,31.0,765.0,29.0,460.0,2025-08-16,2025-08-22,3

In [25]:
streak_results.to_csv('./streak/streak_results/streak_results_with_incentives_cleaned.csv')

In [26]:
conditions = [
    streak_results['Incentive'] == 'Daily Productivity',
    streak_results['Incentive'] == 'Active Bonus',
    streak_results['Incentive'] == 'Guarantee',
    streak_results['Incentive'] == 'Streak'
]

# We take average of all metrics to get progress towards completion of incentive
choices = [
    # Daily productivity 
    streak_results['daily_order_count'] / streak_results['Daily Productivity target'],
    
    # Active hour
    (
        (streak_results['daily_cumulative_time_hr'] / streak_results['Active Hour Required Online Hour']) +
        (streak_results['window_cumulative_hr'] / streak_results['Active Hour Required Hunting Hour']) +
        (streak_results['days_required_worked_count'] / 4) +
        (streak_results['days_worked_count'] / streak_results['Active Hour Required day'])
    ) / 4,
    
    # Daily guarantee
    (
        (streak_results['daily_cumulative_time_hr'] / streak_results['Daily Guarantee Required Online Hour']) +
        (streak_results['window_cumulative_hr'] / streak_results['Daily Guarantee Required Hunting Hour'])
    ) / 2,
    
    # Streak productivity
    (
        (streak_results['orders_target1_cumulative'] / streak_results['streak target P1']) +
        (streak_results['orders_target2_cumulative'] / streak_results['streak target P2']) +
        (streak_results['orders_target3_cumulative'] / streak_results['streak target P3'])
    ) / 3
]

streak_results['progress'] = np.select(conditions, choices, default=np.nan)

In [27]:
streak_results[streak_results['progress'] >= 1]['Incentive'].unique()

array(['Streak', 'Daily Productivity', 'Active Bonus', 'Guarantee'],
      dtype=object)

In [28]:
streak_results.to_csv('./results/incentive_progress.csv')

In [29]:
progress = pd.read_csv('./results/incentive_progress.csv')

In [30]:
progress.columns

Index(['Unnamed: 0', 'Region', 'driver_id', 'assign_created_at',
       'restaurant_name', 'restaurant_category', 'order_id',
       'is_driver_accept', 'wage', 'on_top_fare', 'basket_size',
       'drop_off_distance', 'distance_rider_to_restaurant',
       'placed_to_match_second', 'rider_matched_to_arrived_restaurant_second',
       'rider_waiting_time_in_restaurant_second',
       'delivery_time_to_user_second', 'total_user_waiting_time_second',
       'order_status', 'date', 'region::multi-filter', 'avg_rain',
       'Rain_Level', 'Tier', 'Incentive', 'daily_order_count',
       'time_per_order_sec', 'daily_cumulative_time_sec',
       'time_worked_in_window_sec', 'window_cumulative_sec',
       'daily_cumulative_time_hr', 'window_cumulative_hr', 'day_of_week',
       'day_of_week_short', 'week_start_date', 'year', 'week',
       'days_worked_count', 'days_worked_list', 'has_required_days',
       'is_target1_day', 'is_target2_day', 'is_target3_day',
       'orders_target1_cumulative', 'orders_target2_cumulative',
       'orders_target3_cumulative', 'worked_target1_days',
       'worked_target2_days', 'worked_target3_days',
       'Daily Guarantee Required Online Hour',
       'Daily Guarantee Hunting hour period',
       'Daily Guarantee Required Hunting Hour', 'Daily Guarantee amount',
       'Active Hour Required Online Hour', 'Active Hour Hunting hour period',
       'Active Hour Required Hunting Hour', 'Active Hour Required day',
       'Active Hour Require Dow', 'Active Hour Reward',
       'Daily Productivity target', 'Daily Productivity Reward',
       'Streak target', 'Streak Reward', 'streak target P1',
       'streak reward P1', 'streak target P2', 'streak reward P2',
       'streak target P3', 'streak reward P3', 'Start Date', 'End Date',
       'days_required_worked_count', 'progress'],
      dtype='object')